import Sz8.Galois.Descent
import Sz8.Galois.TwoPunctures
import Mathlib.Analysis.Normed.Module.Connected
import Mathlib.LinearAlgebra.Complex.FiniteDimensional

/-!
# Filling the node punctures

`R ⊆ ℂ` is the plane with the two genuine punctures `ζ₃`, `ζ₃²` and a finite set `A` of further
punctures removed. A representation of `π₁(R, 0)` that kills every based conjugate of a loop in a
small disc about each point of `A` has image generated by the images of the two recorded
polylines: `range_eq_closure`.

Proof: include `R` into `X2 = ℂ ∖ {ζ₃, ζ₃²}`. There the two polylines generate
(`TwoPunctures.polylines_generate`), so every class of `R` agrees in `X2` with a word in them;
`Descent.kernel_descent`, applied with `D` a union of pairwise disjoint small discs about the
points of `A`, says the representation cannot tell the two apart.
-/

open Set Metric

namespace Sz8.Galois.Filling

/-! ### Radii -/

section radii
variable (A : Finset ℂ)

/-- The finitely many special points: the base point, the two genuine punctures and `A`. -/
noncomputable def E : Finset ℂ :=
  insert 0 (insert (TwoPunctures.pz true) (insert (TwoPunctures.pz false) A))

/-- Distance from `a` to the other special points. -/
noncomputable def d (a : ℂ) : ℝ := infDist a ((E A).erase a : Set ℂ)

/-- The disc radius at `a`: at most `r a`, and at most half the distance to the other special
points, so discs are pairwise disjoint and avoid every other special point. -/
noncomputable def ε (r : ℂ → ℝ) (a : ℂ) : ℝ := min (r a) (d A a / 2)

theorem d_pos {a : ℂ} (ha0 : a ≠ 0) : 0 < d A a := by
  have hcl : IsClosed ((E A).erase a : Set ℂ) := ((E A).erase a).finite_toSet.isClosed
  refine (hcl.notMem_iff_infDist_pos ⟨0, ?_⟩).1 (by simp)
  simp [E, Ne.symm ha0]

theorem d_le {a b : ℂ} (hb : b ∈ E A) (hba : b ≠ a) : d A a ≤ dist a b :=
  infDist_le_dist_of_mem (by simp [hb, hba])

variable {A}

theorem ε_pos {r : ℂ → ℝ} {a : ℂ} (hr : 0 < r a) (ha0 : a ≠ 0) : 0 < ε A r a :=
  lt_min hr (half_pos (d_pos A ha0))

/-- A point of the disc about `a` other than `a` is no other special point. -/
theorem not_special {r : ℂ → ℝ} {a z : ℂ} (ha0 : a ≠ 0) (hz : z ∈ ball a (ε A r a)) (hza : z ≠ a) :
    z ∉ E A := by
  intro hzE
  have h1 := d_le A hzE hza
  have h2 : dist z a < d A a / 2 := lt_of_lt_of_le hz (min_le_right _ _)
  have h3 := d_pos A ha0
  rw [dist_comm] at h1
  linarith

/-- The discs about two points of `A` meet only if the points coincide. -/
theorem disc_unique {r : ℂ → ℝ} {a b z : ℂ} (ha : a ∈ A) (hb : b ∈ A)
    (hza : z ∈ ball a (ε A r a)) (hzb : z ∈ ball b (ε A r b)) : a = b := by
  by_contra hab
  have haE : a ∈ E A := by simp [E, ha]
  have hbE : b ∈ E A := by simp [E, hb]
  have h1 := d_le A hbE (Ne.symm hab)
  have h2 := d_le A haE hab
  have h3 : dist z a < d A a / 2 := lt_of_lt_of_le hza (min_le_right _ _)
  have h4 : dist z b < d A b / 2 := lt_of_lt_of_le hzb (min_le_right _ _)
  have h5 := dist_triangle a z b
  rw [dist_comm a z, dist_comm b a] at *
  linarith

end radii

/-! ### A punctured disc is path connected -/

theorem isPathConnected_ball_diff (a : ℂ) {e : ℝ} (he : 0 < e) :
    IsPathConnected (ball a e \ {a}) := by
  set P1 := ball a e ∩ {z : ℂ | z.im < a.im}
  set P2 := ball a e ∩ {z : ℂ | a.im < z.im}
  set P3 := ball a e ∩ {z : ℂ | z.re < a.re}
  set P4 := ball a e ∩ {z : ℂ | a.re < z.re}
  have c1 : Convex ℝ P1 := (convex_ball _ _).inter (convex_halfSpace_lt Complex.imLm.isLinear _)
  have c2 : Convex ℝ P2 := (convex_ball _ _).inter (convex_halfSpace_gt Complex.imLm.isLinear _)
  have c3 : Convex ℝ P3 := (convex_ball _ _).inter (convex_halfSpace_lt Complex.reLm.isLinear _)
  have c4 : Convex ℝ P4 := (convex_ball _ _).inter (convex_halfSpace_gt Complex.reLm.isLinear _)
  have hb : ∀ s t : ℝ, |s| + |t| < e → a + ⟨s, t⟩ ∈ ball a e := by
    intro s t h
    rw [mem_ball, dist_eq_norm, add_sub_cancel_left]
    exact (Complex.norm_le_abs_re_add_abs_im _).trans_lt h
  have q : ∀ s t : ℝ, |s| = e / 4 → |t| = e / 4 → |s| + |t| < e := by
    intro s t hs ht; rw [hs, ht]; linarith
  have p4 : |e / 4| = e / 4 := abs_of_pos (by positivity)
  have m4 : |-(e / 4)| = e / 4 := by rw [abs_neg, p4]
  have w13 : (P1 ∩ P3).Nonempty :=
    ⟨a + ⟨-(e / 4), -(e / 4)⟩, ⟨hb _ _ (q _ _ m4 m4), by simp; linarith⟩,
      hb _ _ (q _ _ m4 m4), by simp; linarith⟩
  have w2 : ((P1 ∪ P3) ∩ P2).Nonempty :=
    ⟨a + ⟨-(e / 4), e / 4⟩, Or.inr ⟨hb _ _ (q _ _ m4 p4), by simp; linarith⟩,
      hb _ _ (q _ _ m4 p4), by simp; linarith⟩
  have w4 : ((P1 ∪ P3 ∪ P2) ∩ P4).Nonempty :=
    ⟨a + ⟨e / 4, e / 4⟩, Or.inr ⟨hb _ _ (q _ _ p4 p4), by simp; linarith⟩,
      hb _ _ (q _ _ p4 p4), by simp; linarith⟩
  have ne1 : P1.Nonempty := w13.mono inter_subset_left
  have ne3 : P3.Nonempty := w13.mono inter_subset_right
  have ne2 : P2.Nonempty := w2.mono inter_subset_right
  have ne4 : P4.Nonempty := w4.mono inter_subset_right
  have hunion : ball a e \ {a} = P1 ∪ P3 ∪ P2 ∪ P4 := by
    ext z
    simp only [mem_sdiff, mem_singleton_iff, mem_union, mem_inter_iff, P1, P2, P3, P4,
      mem_ofPred_eq]
    constructor
    · rintro ⟨hz, hne⟩
      rcases lt_trichotomy z.im a.im with h | h | h
      · exact Or.inl (Or.inl (Or.inl ⟨hz, h⟩))
      · rcases lt_trichotomy z.re a.re with h' | h' | h'
        · exact Or.inl (Or.inl (Or.inr ⟨hz, h'⟩))
        · exact absurd (Complex.ext h' h) hne
        · exact Or.inr ⟨hz, h'⟩
      · exact Or.inl (Or.inr ⟨hz, h⟩)
    · rintro (((⟨hz, h⟩ | ⟨hz, h⟩) | ⟨hz, h⟩) | ⟨hz, h⟩)
      · exact ⟨hz, fun e => by rw [e] at h; exact lt_irrefl _ h⟩
      · exact ⟨hz, fun e => by rw [e] at h; exact lt_irrefl _ h⟩
      · exact ⟨hz, fun e => by rw [e] at h; exact lt_irrefl _ h⟩
      · exact ⟨hz, fun e => by rw [e] at h; exact lt_irrefl _ h⟩
  rw [hunion]
  exact (((c1.isPathConnected ne1).union (c3.isPathConnected ne3) w13).union
    (c2.isPathConnected ne2) w2).union (c4.isPathConnected ne4) w4

/-- The two genuine punctures are exactly the roots of `t² + t + 1`. -/
theorem sq_add_add_one_eq_zero_iff (z : ℂ) :
    z ^ 2 + z + 1 = 0 ↔ z = TwoPunctures.pz true ∨ z = TwoPunctures.pz false := by
  have h3 : Real.sqrt 3 * Real.sqrt 3 = 3 := Real.mul_self_sqrt (by norm_num)
  have hsum : TwoPunctures.pz true + TwoPunctures.pz false = -1 := by
    apply Complex.ext <;> simp [TwoPunctures.pz]
  have hprod : TwoPunctures.pz true * TwoPunctures.pz false = 1 := by
    apply Complex.ext <;> simp [TwoPunctures.pz, Complex.mul_re, Complex.mul_im] <;> nlinarith
  have hfac : z ^ 2 + z + 1 = (z - TwoPunctures.pz true) * (z - TwoPunctures.pz false) := by
    linear_combination z * hsum - hprod
  rw [hfac, mul_eq_zero, sub_eq_zero, sub_eq_zero]

/-! ### Paths in a subset of `ℂ` -/

/-- A path in `ℂ` staying in `S`, as a path in `S`. -/
noncomputable def liftP {S : Set ℂ} {y z : S} (γ : Path (y : ℂ) (z : ℂ)) (h : ∀ u, γ u ∈ S) : Path y z where
  toFun u := ⟨γ u, h u⟩
  continuous_toFun := γ.continuous.subtype_mk _
  source' := Subtype.ext γ.source
  target' := Subtype.ext γ.target

theorem mapOfEq_mk {Y Z : Type*} [TopologicalSpace Y] [TopologicalSpace Z] (f : C(Y, Z)) {y : Y}
    {z : Z} (h : f y = z) (p : Path y y) :
    FundamentalGroup.mapOfEq f h (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk p))
      = FundamentalGroup.fromPath
          (Path.Homotopic.Quotient.mk ((p.map f.continuous).cast h.symm h.symm)) := by
  rw [FundamentalGroup.mapOfEq_apply]
  rfl

/-! ### The filling theorem -/

/-- The data of the filling theorem: `R` is `ℂ` minus `ζ₃`, `ζ₃²` and the finite set `A`, it
contains the base point `0`, and `r` gives a positive radius at each point of `A`. -/
structure Setup where
  R : Set ℂ
  A : Finset ℂ
  hR : ∀ z, z ∈ R ↔ (z ≠ TwoPunctures.pz true ∧ z ≠ TwoPunctures.pz false) ∧ z ∉ A
  h0 : (0 : ℂ) ∈ R
  r : ℂ → ℝ
  hr : ∀ a ∈ A, 0 < r a

namespace Setup
variable (S : Setup)

theorem R_eq : S.R = ((insert (TwoPunctures.pz true) (insert (TwoPunctures.pz false) S.A) :
    Finset ℂ) : Set ℂ)ᶜ := by
  ext z; rw [S.hR]; simp [not_or, and_assoc]

theorem isOpen_R : IsOpen S.R := by
  rw [S.R_eq]; exact (Finset.finite_toSet _).isClosed.isOpen_compl

theorem isPathConnected_R : IsPathConnected S.R := by
  rw [S.R_eq]
  exact (Finset.finite_toSet _).countable.isPathConnected_compl_of_one_lt_rank
    (by rw [Complex.rank_real_complex]; norm_num)

theorem ne_zero_of_mem {a : ℂ} (ha : a ∈ S.A) : a ≠ 0 := by
  rintro rfl; exact ((S.hR 0).1 S.h0).2 ha

/-- The disc radius at `a`. -/
noncomputable abbrev e (a : ℂ) : ℝ := ε S.A S.r a

theorem e_pos {a : ℂ} (ha : a ∈ S.A) : 0 < S.e a := ε_pos (S.hr a ha) (S.ne_zero_of_mem ha)

theorem mem_R_of_disc {a z : ℂ} (ha : a ∈ S.A) (hz : z ∈ ball a (S.e a)) (hza : z ≠ a) :
    z ∈ S.R := by
  have h := not_special (S.ne_zero_of_mem ha) hz hza
  simp only [E, Finset.mem_insert, not_or] at h
  exact (S.hR z).2 ⟨⟨h.2.1, h.2.2.1⟩, h.2.2.2⟩

/-- The base point. -/
def b0 : S.R := ⟨0, S.h0⟩

/-- The inclusion `R → X2`. -/
def toX : C(S.R, TwoPunctures.X2) := ⟨fun z => ⟨z.1, ((S.hR z.1).1 z.2).1⟩, by fun_prop⟩

/-- A point of the punctured disc about `a`: the junction for all connecting paths into it. -/
noncomputable def pa (a : ℂ) : ℂ := a + ((S.e a / 2 : ℝ) : ℂ)

theorem pa_mem {a : ℂ} (ha : a ∈ S.A) : S.pa a ∈ ball a (S.e a) \ {a} := by
  have he := S.e_pos ha
  refine ⟨?_, ?_⟩
  · rw [mem_ball, pa, dist_eq_norm, add_sub_cancel_left, Complex.norm_real, Real.norm_eq_abs,
      abs_of_pos (by positivity)]
    linarith
  · simp only [pa, mem_singleton_iff, add_eq_left, Complex.ofReal_eq_zero]
    exact ne_of_gt (by positivity)

/-- The junction point as a point of `R`. -/
noncomputable def paR {a : ℂ} (ha : a ∈ S.A) : S.R :=
  ⟨S.pa a, S.mem_R_of_disc ha (S.pa_mem ha).1 (S.pa_mem ha).2⟩

/-- A path in `R` from the base point to the junction of the disc about `a`. -/
noncomputable def δ {a : ℂ} (ha : a ∈ S.A) : Path S.b0 (S.paR ha) :=
  liftP _ (S.isPathConnected_R.joinedIn 0 S.h0 _ (S.paR ha).2).somePath_mem

/-- A path inside the punctured disc about `a`, from its junction to `y`. -/
noncomputable def σ {a : ℂ} (ha : a ∈ S.A) (y : S.R) (hy : (y : ℂ) ∈ ball a (S.e a)) :
    Path (S.paR ha) y :=
  liftP ((isPathConnected_ball_diff a (S.e_pos ha)).joinedIn _ (S.pa_mem ha) _
      ⟨hy, fun h => ((S.hR _).1 (h ▸ y.2)).2 ha⟩).somePath
    (fun u => S.mem_R_of_disc ha
      (((isPathConnected_ball_diff a (S.e_pos ha)).joinedIn _ (S.pa_mem ha) _
        ⟨hy, fun h => ((S.hR _).1 (h ▸ y.2)).2 ha⟩).somePath_mem u).1
      (((isPathConnected_ball_diff a (S.e_pos ha)).joinedIn _ (S.pa_mem ha) _
        ⟨hy, fun h => ((S.hR _).1 (h ▸ y.2)).2 ha⟩).somePath_mem u).2)

theorem σ_mem {a : ℂ} (ha : a ∈ S.A) (y : S.R) (hy : (y : ℂ) ∈ ball a (S.e a)) (u : unitInterval) :
    (S.σ ha y hy u : ℂ) ∈ ball a (S.e a) :=
  (((isPathConnected_ball_diff a (S.e_pos ha)).joinedIn _ (S.pa_mem ha) _
    ⟨hy, fun h => ((S.hR _).1 (h ▸ y.2)).2 ha⟩).somePath_mem u).1

open Classical in
/-- The connecting path to `y`: through the junction of its disc if `y` lies in one, and any path
in `R` otherwise. -/
noncomputable def conn (y : S.R) : Path S.b0 y :=
  if h : ∃ a, a ∈ S.A ∧ (y : ℂ) ∈ ball a (S.e a) then
    (S.δ h.choose_spec.1).trans (S.σ h.choose_spec.1 y h.choose_spec.2)
  else
    liftP _ (S.isPathConnected_R.joinedIn 0 S.h0 _ y.2).somePath_mem

theorem conn_spec {a : ℂ} (ha : a ∈ S.A) (y : S.R) (hy : (y : ℂ) ∈ ball a (S.e a)) :
    ∃ σ' : Path (S.paR ha) y, (∀ u, (σ' u : ℂ) ∈ ball a (S.e a)) ∧
      S.conn y = (S.δ ha).trans σ' := by
  have h : ∃ a, a ∈ S.A ∧ (y : ℂ) ∈ ball a (S.e a) := ⟨a, ha, hy⟩
  have key : ∀ (a' : ℂ) (ha' : a' ∈ S.A) (hy' : (y : ℂ) ∈ ball a' (S.e a')), a' = a →
      ∃ σ' : Path (S.paR ha) y, (∀ u, (σ' u : ℂ) ∈ ball a (S.e a)) ∧
        (S.δ ha').trans (S.σ ha' y hy') = (S.δ ha).trans σ' := by
    rintro a' ha' hy' rfl
    exact ⟨S.σ ha' y hy', S.σ_mem ha' y hy', rfl⟩
  unfold conn
  rw [dite_eq_left_of_eq_true (eq_true h)]
  exact key _ _ _ (disc_unique h.choose_spec.1 ha h.choose_spec.2 hy)

/-- A path whose every point lies in some disc, and which starts in the disc about `a`, stays in
that disc: the discs are disjoint and open, and the path is connected. -/
theorem stay {a : ℂ} (ha : a ∈ S.A) {y z : S.R} (β : Path y z)
    (hβ : ∀ u, ∃ b ∈ S.A, (β u : ℂ) ∈ ball b (S.e b)) (hy : (y : ℂ) ∈ ball a (S.e a)) :
    ∀ u, (β u : ℂ) ∈ ball a (S.e a) := by
  have hs : IsPreconnected (range fun u => (β u : ℂ)) :=
    isPreconnected_range (continuous_subtype_val.comp β.continuous)
  have hsub := hs.subset_left_of_subset_union (u := ball a (S.e a))
    (v := ⋃ b ∈ S.A.erase a, ball b (S.e b)) isOpen_ball
    (isOpen_biUnion fun _ _ => isOpen_ball) ?disj ?cov ?ne
  · intro u; exact hsub ⟨u, rfl⟩
  · refine Set.disjoint_left.2 fun w hw hw' => ?_
    obtain ⟨b, hb, hwb⟩ := mem_iUnion₂.1 hw'
    exact (Finset.mem_erase.1 hb).1 (disc_unique ha (Finset.mem_erase.1 hb).2 hw hwb).symm
  · rintro _ ⟨u, rfl⟩
    obtain ⟨b, hb, h⟩ := hβ u
    by_cases hba : b = a
    · subst hba; exact Or.inl h
    · exact Or.inr (mem_iUnion₂.2 ⟨b, Finset.mem_erase.2 ⟨hba, hb⟩, h⟩)
  · exact ⟨(β 0 : ℂ), ⟨0, rfl⟩, by simpa using hy⟩

variable {H : Type*} [Group H] (ρ : FundamentalGroup S.R S.b0 →* H)

/-- The hypothesis on `ρ`: it kills every based conjugate of a loop within `r a` of a point `a`
of `A`. -/
def KillsDiscs : Prop :=
  ∀ a ∈ S.A, ∀ (b : S.R) (c : Path S.b0 b) (δ : Path b b), (∀ u, (δ u : ℂ) ∈ ball a (S.r a)) →
    ρ (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (c.trans (δ.trans c.symm)))) = 1

theorem conn_kill (hρ : S.KillsDiscs ρ) {y z : S.R} (β : Path y z)
    (hβ : ∀ u, ∃ b ∈ S.A, (β u : ℂ) ∈ ball b (S.e b)) :
    ρ (FundamentalGroup.fromPath
      (Path.Homotopic.Quotient.mk ((S.conn y).trans (β.trans (S.conn z).symm)))) = 1 := by
  obtain ⟨a, ha, hya⟩ := hβ 0
  simp only [Path.source] at hya
  have hall := S.stay ha β hβ hya
  have hza : (z : ℂ) ∈ ball a (S.e a) := by simpa using hall 1
  obtain ⟨σy, hσy, ey⟩ := S.conn_spec ha y hya
  obtain ⟨σz, hσz, ez⟩ := S.conn_spec ha z hza
  have eq : Path.Homotopic.Quotient.mk ((S.conn y).trans (β.trans (S.conn z).symm))
      = Path.Homotopic.Quotient.mk
          ((S.δ ha).trans ((σy.trans (β.trans σz.symm)).trans (S.δ ha).symm)) := by
    rw [ey, ez, Path.trans_symm]
    simp only [Path.Homotopic.Quotient.mk_trans, Path.Homotopic.Quotient.mk_symm,
      PathQ.trans_assoc]
  rw [eq]
  refine hρ a ha _ _ _ (fun u => ?_)
  have hm : ∀ u, (σy.trans (β.trans σz.symm)) u ∈ {w : S.R | (w : ℂ) ∈ ball a (S.e a)} :=
    PathQ.mem_of_trans _ _ hσy (PathQ.mem_of_trans _ _ hall (PathQ.mem_of_symm _ hσz))
  exact ball_subset_ball (min_le_left _ _) (hm u)

/-- `R` inside `X2`. -/
def UX : Set TwoPunctures.X2 := {w | (w : ℂ) ∈ S.R}

/-- The discs, inside `X2`. -/
noncomputable def DX : Set TwoPunctures.X2 := {w | ∃ a ∈ S.A, (w : ℂ) ∈ ball a (S.e a)}

noncomputable def toR : C(S.UX, S.R) := ⟨fun w => ⟨w.1.1, w.2⟩, by fun_prop⟩

noncomputable def toU : C(S.R, S.UX) := ⟨fun z => ⟨S.toX z, z.2⟩, by fun_prop⟩

theorem x0_mem : TwoPunctures.x0 ∈ S.UX := S.h0

theorem toX_b0 : S.toX S.b0 = TwoPunctures.x0 := rfl

/-- The connecting paths, read in `UX`. -/
noncomputable def connU (y : S.UX) : Path (⟨TwoPunctures.x0, S.x0_mem⟩ : S.UX) y where
  toFun u := S.toU (S.conn (S.toR y) u)
  continuous_toFun := S.toU.continuous.comp (S.conn (S.toR y)).continuous
  source' := by simp only [Path.source]; rfl
  target' := by simp only [Path.target]; rfl

/-- **Kernel form of filling.** Loops in `R` that become homotopic in `ℂ ∖ {ζ₃, ζ₃²}` have the
same image under a representation killing the small loops about `A`. -/
theorem kernel (hρ : S.KillsDiscs ρ) (p q : Path S.b0 S.b0)
    (hpq : (p.map S.toX.continuous).Homotopic (q.map S.toX.continuous)) :
    ρ (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk p))
      = ρ (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk q)) := by
  have hUo : IsOpen S.UX := S.isOpen_R.preimage continuous_subtype_val
  have hDo : IsOpen S.DX := by
    have : S.DX = Subtype.val ⁻¹' (⋃ a ∈ (S.A : Set ℂ), ball a (S.e a)) := by
      ext w; simp [DX]
    rw [this]
    exact (isOpen_biUnion fun _ _ => isOpen_ball).preimage continuous_subtype_val
  have hcov : ∀ w, w ∈ S.UX ∨ w ∈ S.DX := by
    intro w
    by_cases hw : (w : ℂ) ∈ S.A
    · exact Or.inr ⟨w, hw, mem_ball_self (S.e_pos hw)⟩
    · exact Or.inl ((S.hR w).2 ⟨w.2, hw⟩)
  have K := Descent.kernel_descent S.UX S.DX hUo hDo hcov S.x0_mem
    (ρ.comp (FundamentalGroup.mapOfEq S.toR rfl)) S.connU
    (fun y z β hβ => by
      have e : ((S.connU y).trans (β.trans (S.connU z).symm)).map S.toR.continuous
          = (S.conn (S.toR y)).trans ((β.map S.toR.continuous).trans (S.conn (S.toR z)).symm) := by
        rw [Path.map_trans, Path.map_trans, ← Path.map_symm]; rfl
      rw [MonoidHom.comp_apply]
      refine (congrArg ρ (mapOfEq_mk S.toR _ _)).trans ?_
      exact (congrArg (fun P => ρ (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk P))) e).trans
        (S.conn_kill ρ hρ (β.map S.toR.continuous) (fun u => hβ u)))
    (p.map S.toU.continuous) (q.map S.toU.continuous) hpq
  rw [MonoidHom.comp_apply, MonoidHom.comp_apply] at K
  exact (congrArg ρ (mapOfEq_mk S.toR _ _)).symm.trans (K.trans (congrArg ρ (mapOfEq_mk S.toR _ _)))

/-- **Filling the punctures.** A representation of `π₁(R, 0)` killing the small loops about the points of
`A` has image generated by the images of the two recorded polylines. -/
theorem range_eq_closure (hρ : S.KillsDiscs ρ) (γ₁ γ₂ : Path S.b0 S.b0)
    (hγ₁ : ∀ u, (γ₁ u : ℂ) = Sz8.Monodromy.Meridian1.chain.poly 40 (Sz8.Monodromy.Meridian1.chain.n - 1) u)
    (hγ₂ : ∀ u, (γ₂ u : ℂ) = Sz8.Monodromy.Meridian1.chain2.poly 40 (Sz8.Monodromy.Meridian1.chain2.n - 1) u) :
    ρ.range = Subgroup.closure
      {ρ (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₁)),
        ρ (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₂))} := by
  obtain ⟨g₁, g₂, hg₁, hg₂, hgen⟩ := TwoPunctures.polylines_generate
  set j : FundamentalGroup S.R S.b0 →* FundamentalGroup TwoPunctures.X2 TwoPunctures.x0 :=
    FundamentalGroup.mapOfEq S.toX S.toX_b0 with hj
  have e₁ : j (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₁))
      = FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk g₁) := by
    rw [hj, mapOfEq_mk]
    exact congrArg _ (congrArg _ (Path.ext (funext fun u => Subtype.ext ((hγ₁ u).trans (hg₁ u).symm))))
  have e₂ : j (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₂))
      = FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk g₂) := by
    rw [hj, mapOfEq_mk]
    exact congrArg _ (congrArg _ (Path.ext (funext fun u => Subtype.ext ((hγ₂ u).trans (hg₂ u).symm))))
  refine le_antisymm ?_ ?_
  · rintro _ ⟨g, rfl⟩
    have hjg : j g ∈ (Subgroup.closure {FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₁),
        FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₂)}).map j := by
      rw [MonoidHom.map_closure, Set.image_insert_eq, Set.image_singleton, e₁, e₂, hgen]
      exact Subgroup.mem_top _
    obtain ⟨h, hh, hjh⟩ := hjg
    have key : ρ h = ρ g := by
      induction g using Path.Homotopic.Quotient.ind with | _ q =>
      induction h using Path.Homotopic.Quotient.ind with | _ p =>
      have hjh' : FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (p.map S.toX.continuous))
          = FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (q.map S.toX.continuous)) := by
        have := hjh
        rw [hj, mapOfEq_mk, mapOfEq_mk] at this
        exact this
      exact S.kernel ρ hρ p q (Quotient.exact hjh')
    rw [← key]
    have : ρ h ∈ (Subgroup.closure {FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₁),
        FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₂)}).map ρ := ⟨h, hh, rfl⟩
    rwa [MonoidHom.map_closure, Set.image_insert_eq, Set.image_singleton] at this
  · rw [Subgroup.closure_le]
    rintro _ (rfl | rfl)
    exacts [⟨_, rfl⟩, ⟨_, rfl⟩]

end Setup

end Sz8.Galois.Filling
