import Sz8.Monodromy.PaperCovering
import Sz8.Monodromy.MonodromyData
import Sz8.Monodromy.GroupCerts
import Sz8.Monodromy.NinetyOneCerts
import Sz8.Monodromy.NormalizerCerts
import Sz8.Monodromy.Irreducibility
import Sz8.Monodromy.Meridian.Gamma2
import Sz8.Galois.Filling
import Sz8.Galois.Identity
import Sz8.Galois.GaloisDescent
import Sz8.Galois.RelNormal
import Sz8.Galois.Bridge
import Sz8.Galois.Converse
import Sz8.Galois.Specialize
import Sz8.Galois.SpecFamily
import Sz8.Galois.Resolvent
import Sz8.Galois.DegreeBound
import Sz8.Galois.IntModel
import Sz8.Galois.GermEval
import Sz8.Galois.NSum
import Sz8.Galois.Pinning
import Sz8.Galois.Enclose
import Sz8.Galois.ZList
import Sz8.Galois.EncData0
import Sz8.Galois.ThetaData0
import Sz8.Galois.EncData1
import Sz8.Galois.ThetaData1
import Sz8.Galois.EncData2
import Sz8.Galois.ThetaData2
import Sz8.Galois.EncData3
import Sz8.Galois.ThetaData3
import Sz8.Galois.EncData4
import Sz8.Galois.ThetaData4
import Sz8.Galois.EncData5
import Sz8.Galois.ThetaData5
import Sz8.Galois.EncData6
import Sz8.Galois.ThetaData6
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.FieldTheory.RatFunc.AsPolynomial
import Mathlib.GroupTheory.Commutator.Basic

/-!
# The specialization theorem

The Galois group of `f(X, -7/5)` over `ℚ`, acting on its 65 roots, is the explicit group
`N = [G, G]`, `G = ⟨σ₁, σ₂⟩` (`gal_specialization_eq_N`, `card_gal_specialization`); with
`Sz8.Galois.SuzukiGalois` it is isomorphic to Suzuki's group `Sz(8)`.

Structure of the proof:

* Explicit group certificates: `card_G`, `card_N` and `eq_N_of_ninetyOne_dvd` from stabiliser
  chains and Sylow's theorem (`Sz8.Monodromy.GroupCerts`, `Sz8.Monodromy.NinetyOneCerts`), `normalizer_G` from
  a certified backtrack search (`Sz8.Monodromy.NormalizerCerts`).
* Certified meridians: `zero_regular` and `meridian_monodromy` from
  `Sz8.Monodromy.Meridian1.meridian_monodromy`.
* The Galois–monodromy bridge: `monodromy_eq_geometric_galois` (lower inclusion and converse,
  `Sz8.Galois.Germs` … `Sz8.Galois.Converse`), `geometric_normal_in_arithmetic`
  (`Sz8.Galois.GaloisDescent`, `Sz8.Galois.RelNormal`), and the geometric inputs
  `meridian_generation` (`Sz8.Galois.Filling`), `bad_set_eq` (the resultant identity,
  `Sz8.Galois.Identity`) and `node_monodromy_trivial` (`Sz8.Galois.Nodes`). `generic_galois`
  follows from these and `normalizer_G`.
* Specialization: `specialization_le_decomposition` puts `Gal(h/ℚ)` inside the labelled image of
  the decomposition group of a prime over `t = -7/5` (`Sz8.Galois.Specialize`,
  `Sz8.Galois.SpecFamily`). `decomposition_le_N` (that group acts in `N`) follows from
  `resolvent_identity` through `decomposition_le_of_split_witness` and the resolvent data
  (`Sz8.Galois.Resolvent`), and `specialization_embeds` from those and `generic_galois`.
* The resolvent identity, the exact cubic resolvent of an explicit relative invariant of `N` in `G`,
  combines (R1) `sym_int` (integer polynomials; `Sz8.Galois.IntModel`), (R2) `sym_natDegree_le`
  (degree bounds; `Sz8.Galois.DegreeBound`), the `germ_link` (some labelling with image `G`
  transfers every polynomial relation among the roots over `ℚ(t)` to the certified disc roots on the
  step-0 ball), and (R3) `sym_near`, certified approximate values at seven pinning points in that
  ball (`near_point`, `Sz8.Galois.PointBound`, data `EncData0–6`, `ThetaData0–6`). No Kummer theory,
  no local fields at infinity and no twist selection are used.
-/

open Polynomial
open scoped Pointwise Topology

namespace Sz8.Galois
open Sz8.Monodromy

/-! ## The explicit permutation groups -/

/-- The group generated by the recorded meridian permutations; the paper's `Sz(8) ⋊ C₃`. -/
def G : Subgroup (Equiv.Perm (Fin 65)) := Subgroup.closure {σ₁, σ₂}

/-- Its derived subgroup; the paper's `Sz(8)`. No abstract identification is needed below. -/
def N : Subgroup (Equiv.Perm (Fin 65)) := ⁅G, G⁆

/-! ## Explicit group certificates (no classification import) -/

/-- From a verified base and strong generating set
(`Sz8.Monodromy.card_closure_sigma`). -/
theorem card_G : Nat.card G = 87360 := Sz8.Monodromy.card_closure_sigma

/-- The derived subgroup is the group generated by two recorded
commutators, whose stabiliser chain gives its order (`Sz8.Monodromy.card_commutator_sigma`). -/
theorem card_N : Nat.card N = 29120 := Sz8.Monodromy.card_commutator_sigma

/-- Needed for arithmetic = geometric monodromy. From a certified backtrack
search: a normalizing permutation can be moved by `G` to one fixing the two base points of the
chain, and is then determined by the automorphism it induces on the two-point stabiliser
together with the images of five points (`Sz8.Monodromy.normalizer_eq`). -/
theorem normalizer_G : Subgroup.normalizer (G : Set (Equiv.Perm (Fin 65))) = G := by
  have hG : G = Sz8.Monodromy.lclosure Sz8.Monodromy.Ggens0 := Sz8.Monodromy.closure_sigma_eq
  rw [hG]
  exact Sz8.Monodromy.normalizer_eq

/-- `N` is generated by any subgroup whose order is divisible by 91. From
Sylow's theorem and word certificates, with no maximal-subgroup classification: a subgroup of
order 13 is conjugated onto a recorded one, a subgroup of order 7 is the pointwise stabiliser
of a pair of points, and for each of the 48 orbits of pairs the two together generate `N`
(`Sz8.Monodromy.eq_of_ninetyOne_dvd`). -/
theorem eq_N_of_ninetyOne_dvd {H : Subgroup (Equiv.Perm (Fin 65))} (hH : H ≤ N)
    (h91 : 91 ∣ Nat.card H) : H = N := by
  have hN : N = Sz8.Monodromy.lclosure Sz8.Monodromy.Ngens0 := by
    show ⁅Subgroup.closure ({σ₁, σ₂} : Set (Equiv.Perm (Fin 65))),
      Subgroup.closure ({σ₁, σ₂} : Set (Equiv.Perm (Fin 65)))⁆ = _
    rw [Sz8.Monodromy.closure_sigma_eq, Sz8.Monodromy.commutator_eq]
  rw [hN] at hH ⊢
  exact Sz8.Monodromy.eq_of_ninetyOne_dvd hH h91

/-! ## Certified meridians, in Mathlib's covering-space sense -/

/-- The base point `t = 0` is regular: 65 disjoint certified root discs. -/
theorem zero_regular : (0 : ℂ) ∈ paperMonicFamily.regular := Meridian1.zero_regular

/-- The base point of the monodromy action. -/
noncomputable abbrev base : paperMonicFamily.Base := ⟨0, zero_regular⟩

/-- The certified meridians (the polylines around `ζ₃` and `ζ₃²`, the paper's loops
with dyadic vertices) and the labelling of the 65 roots over `t = 0` by the paper's root
order, under which Mathlib's monodromy is exactly the recorded `σ₁`, `σ₂`. -/
theorem meridian_monodromy : ∃ (e : paperMonicFamily.Fiber base ≃ Fin 65)
    (γ₁ γ₂ : Path base base),
    (∀ i, e (paperMonicFamily.isCoveringMap.monodromy (Path.Homotopic.Quotient.mk γ₁)
      (e.symm i)) = σ₁ i) ∧
    (∀ i, e (paperMonicFamily.isCoveringMap.monodromy (Path.Homotopic.Quotient.mk γ₂)
      (e.symm i)) = σ₂ i) := by
  obtain ⟨e, γ₁, γ₂, -, -, h₁, h₂⟩ := Meridian1.meridian_monodromy
  exact ⟨e, γ₁, γ₂, h₁, h₂⟩

/-! ## The Galois–monodromy bridge

`generic_galois` is proved below from five statements:

* `bad_set_eq` — the exact bad set: the resultant identity
  `Res_X(f, f_X) = c̃ (t² + t + 1)^40 S̃²` (813 kernel evaluations, degree bound 812 from an
  assignment certificate, a verified Euclidean resultant algorithm), with separability of `S̃`
  and coprimality with `t² + t + 1` from Bézout certificates modulo `1000003`.
* `node_monodromy_trivial` — local analysis at an apparent branch point. The
  residual quadratic is certified separately (`X³ - t` has discriminant `-27 t²` and monodromy a
  3-cycle, so order two alone does not suffice): the fixed Sylvester minor gives one double root
  at each node, and continuous root branches give trivial local monodromy.
* `meridian_generation` — the topological input, from the certified polylines,
  `Sz8.Galois.TwoPunctures.polylines_generate` and `Sz8.Galois.Descent.kernel_descent`. It is
  stated for the *certified polylines themselves*, not for abstract conjugates of small
  loops. An abstract generating system of meridians is not enough: it would leave the two
  distinguished members conjugate to `σ₁`, `σ₂` by unknown elements of the monodromy group `M`,
  and `M = ⟪G⟫ᴹ` with `G` self-normalizing does not force `M = G` — take `G = Sz(8):3 < M = S₆₅`,
  where the normal closure of `G` is everything.
* `monodromy_eq_geometric_galois` — the analytic bridge from root germs to the Galois group of
  `f` over `ℂ(t)`, carrying the fibre labelling explicitly, via `monodromy_converse`;
  the lower inclusion `monodromy_le_geometric_galois` is proved directly (`Sz8.Galois.Germs`,
  `Continuation`, `Relations`, `Bridge`).
* `geometric_normal_in_arithmetic` — the comparison between `ℚ(t)` and `ℂ(t)`.
  Restriction embeds `Gal(f/ℂ(t))` in `Gal(f/ℚ(t))` with image the fixing group of
  `L ∩ ℂ(t)`, and that field is stable under `Gal(f/ℚ(t))` because every element of `ℂ(t)`
  algebraic over `ℚ(t)` has split minimal polynomial (`RelNormal.relNormal`: a denominator
  multiple is a polynomial by the rational root theorem, with algebraic values at rational points,
  hence built from `t` and algebraic constants by Lagrange interpolation). No linear disjointness,
  no constant field and no `ℚ̄(t)` Galois group is used.

Every interface below carries its root labelling explicitly, so the five statements compose
with no silent relabelling: `monodromy_eq_geometric_galois` consumes the fibre labelling `e`
produced by the certified meridians and produces the geometric root labelling `βC`, which
`geometric_normal_in_arithmetic` consumes in turn to produce the arithmetic labelling `β`.
-/

/-- `f(X, t)` over `ℚ(t)`, from the exact input terms. -/
noncomputable def fRat : (RatFunc ℚ)[X] :=
  famTerms.foldr (fun a acc =>
    C (algebraMap ℚ (RatFunc ℚ) a.2.2 * RatFunc.X ^ a.2.1) * X ^ a.1 + acc) 0

instance fRat_splits : Fact ((fRat.map (algebraMap (RatFunc ℚ) fRat.SplittingField)).Splits) :=
  ⟨SplittingField.splits _⟩

/-- `f(X, t)` over `ℂ(t)`, from the same exact input terms as `fRat`. The geometric (monodromy)
Galois group lives here; `fRat` carries the arithmetic one. -/
noncomputable def fCx : (RatFunc ℂ)[X] :=
  famTerms.foldr (fun a acc =>
    C (algebraMap ℚ (RatFunc ℂ) a.2.2 * RatFunc.X ^ a.2.1) * X ^ a.1 + acc) 0

instance fCx_splits : Fact ((fCx.map (algebraMap (RatFunc ℂ) fCx.SplittingField)).Splits) :=
  ⟨SplittingField.splits _⟩

/-- `fCx` is `fRat` read over `ℂ(t)`. -/
theorem fRat_map_eq : fRat.map (algebraMap (RatFunc ℚ) (RatFunc ℂ)) = fCx := by
  have hc : ∀ c : ℚ, algebraMap (RatFunc ℚ) (RatFunc ℂ) (algebraMap ℚ (RatFunc ℚ) c) =
      algebraMap ℚ (RatFunc ℂ) c := fun c =>
    congrArg (· c) (RingHom.ext_rat ((algebraMap (RatFunc ℚ) (RatFunc ℂ)).comp
      (algebraMap ℚ (RatFunc ℚ))) (algebraMap ℚ (RatFunc ℂ)))
  have hX : algebraMap (RatFunc ℚ) (RatFunc ℂ) RatFunc.X = RatFunc.X := RelNormal.φ_X
  unfold fRat fCx
  induction famTerms with
  | nil => simp
  | cons a l ih =>
    rw [List.foldr_cons, List.foldr_cons, Polynomial.map_add, ih, Polynomial.map_mul,
      Polynomial.map_pow, map_C, map_X, map_mul, map_pow, hc, hX]

/-- The monodromy group of the paper's covering at the base point, read in `Equiv.Perm (Fin 65)`
through a labelling `e` of the fibre. -/
noncomputable def monodromyGroup (e : paperMonicFamily.Fiber base ≃ Fin 65) :
    Subgroup (Equiv.Perm (Fin 65)) :=
  (paperMonicFamily.isCoveringMap.monodromyPerm base).range.map
    (Equiv.permCongrHom e).toMonoidHom

/-- The paper's bad-set data: `nodes` are the 342 apparent branch points, disjoint from the two
primitive cube roots of unity, and together with those two they are exactly the parameters at
which `f` has a repeated root. -/
def IsBadSet (nodes : Finset ℂ) : Prop :=
  nodes.card = 342 ∧ (∀ a ∈ nodes, a ^ 2 + a + 1 ≠ 0) ∧
    paperMonicFamily.regularᶜ = {t : ℂ | t ^ 2 + t + 1 = 0} ∪ ↑nodes

/-- `γ` is a based conjugate of a loop that stays within distance `r` of `s`. -/
def SupportedWithin (s : ℂ) (r : ℝ) (γ : FundamentalGroup paperMonicFamily.Base base) : Prop :=
  ∃ (b : paperMonicFamily.Base) (c : Path base b) (δ : Path b b),
    (∀ u, ((δ u : paperMonicFamily.Base) : ℂ) ∈ Metric.ball s r) ∧
      γ = FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (c.trans (δ.trans c.symm)))

/-- `γ` is supported at the puncture `s`: a based conjugate of a loop in an arbitrarily small
disc about `s`. This is what a meridian at `s` satisfies, and it is the only property of the
node meridians that the assembly consumes. -/
def SupportedAt (s : ℂ) (γ : FundamentalGroup paperMonicFamily.Base base) : Prop :=
  ∀ r > 0, SupportedWithin s r γ

/-- **Exact bad set.** The parameters at which `f(·, t)` has a repeated root are exactly
the two primitive cube roots of unity together with the 342 roots of the node polynomial `S̃`.

Proved from the resultant identity `Res_X(f, f_X) = c̃ (t² + t + 1)^40 S̃²` (`ResEval.identity`:
813 kernel evaluations, the assignment degree bound 812, and a verified resultant algorithm),
separability of `S̃` and its coprimality with `t² + t + 1` (two Bézout certificates modulo
`1000003`, `NodeSep`). -/
theorem bad_set_eq : ∃ nodes : Finset ℂ, IsBadSet nodes :=
  ⟨Nodes.nodesS, Nodes.nodesS_card, fun _ ha => Nodes.nodesS_q ha,
    Nodes.regular_compl ResEval.identity⟩

/-- **Local analysis at a node.** Near an apparent branch point every loop supported in a
small enough disc about it has trivial monodromy.

Any set satisfying `IsBadSet` consists of roots of `S̃` (`Nodes.mem_nodesS_of_bad`, uniqueness of
the node set). At such a root the fibre has exactly one double root and otherwise simple roots
(`NodeM2.node_M2`, from the fixed Sylvester minor and seven residue witnesses modulo `1000003`),
and `Res(f_t, f_t') = (t - a)² V(t)` with `V` continuous and `V(a) ≠ 0` (the resultant identity and
separability of `S̃`). `NodeLocal.local_monodromy_trivial` then gives trivial monodromy for loops
in a small disc, and conjugation by the connecting path gives the `SupportedWithin` form. -/
theorem node_monodromy_trivial {nodes : Finset ℂ} (hbad : IsBadSet nodes) {a : ℂ}
    (ha : a ∈ nodes) :
    ∃ r > 0, ∀ γ : FundamentalGroup paperMonicFamily.Base base,
      SupportedWithin a r γ → paperMonicFamily.isCoveringMap.monodromyPerm base γ = 1 := by
  have haS := Nodes.mem_nodesS_of_bad ResEval.identity hbad.2.1 hbad.2.2 ha
  obtain ⟨r, hr, htriv⟩ := Nodes.node_local ResEval.identity haS
  refine ⟨r, hr, fun γ hγ => ?_⟩
  obtain ⟨b, c, δ, hδ, rfl⟩ := hγ
  refine Equiv.ext fun e => ?_
  rw [IsCoveringMap.coe_monodromyPerm, Equiv.Perm.one_apply]
  show paperMonicFamily.isCoveringMap.monodromy
    (Path.Homotopic.Quotient.mk (c.trans (δ.trans c.symm))) e = e
  rw [Path.Homotopic.Quotient.mk_trans, IsCoveringMap.monodromy_trans_apply,
    Path.Homotopic.Quotient.mk_trans, IsCoveringMap.monodromy_trans_apply, htriv b δ hδ,
    ← IsCoveringMap.monodromy_trans_apply, Path.Homotopic.Quotient.mk_symm, PathQ.trans_symm,
    IsCoveringMap.monodromy_refl]
  rfl

/-- **Topology.** A representation of the fundamental group of the regular locus that
kills every based conjugate of a loop within `r a` of each node `a` has image generated by the
images of the certified polylines `γ₁`, `γ₂` — passed in with the explicit polyline
descriptions that `Meridian1.meridian_monodromy` supplies, so that the connection cannot be lost.

The consumer `monodromyGroup_eq` needs only this representation form; it does not ask whether the
recorded loops extend to a generating system of `π₁` with one meridian per node.

Proof: the two polylines generate `π₁(ℂ ∖ {ζ₃, ζ₃²})` (`TwoPunctures.polylines_generate`), and a
representation killing the small loops about the nodes cannot distinguish loops in the regular
locus that become homotopic once the nodes are filled in (`Descent.kernel_descent`, the grid
argument, applied with pairwise disjoint small discs in `Filling.Setup.range_eq_closure`). -/
theorem meridian_generation {nodes : Finset ℂ} (hbad : IsBadSet nodes)
    {γ₁ γ₂ : Path base base}
    (hγ₁ : ∀ u, (γ₁ u).1 = Meridian1.chain.poly 40 (Meridian1.chain.n - 1) u)
    (hγ₂ : ∀ u, (γ₂ u).1 = Meridian1.chain2.poly 40 (Meridian1.chain2.n - 1) u)
    (r : ℂ → ℝ) (hr : ∀ a ∈ nodes, 0 < r a) {H : Type*} [Group H]
    (ρ : FundamentalGroup paperMonicFamily.Base base →* H)
    (hρ : ∀ a ∈ nodes, ∀ g, SupportedWithin a (r a) g → ρ g = 1) :
    ρ.range = Subgroup.closure
      {ρ (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₁)),
        ρ (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₂))} := by
  have hR : ∀ z, z ∈ paperMonicFamily.regular ↔
      (z ≠ TwoPunctures.pz true ∧ z ≠ TwoPunctures.pz false) ∧ z ∉ nodes := by
    intro z
    have h := Set.ext_iff.1 hbad.2.2 z
    simp only [Set.mem_compl_iff, Set.mem_union, Set.mem_ofPred_eq, Finset.mem_coe,
      Filling.sq_add_add_one_eq_zero_iff] at h
    constructor
    · intro hz
      exact ⟨⟨fun e => h.2 (Or.inl (Or.inl e)) hz, fun e => h.2 (Or.inl (Or.inr e)) hz⟩,
        fun hn => h.2 (Or.inr hn) hz⟩
    · rintro ⟨⟨h1, h2⟩, h3⟩
      by_contra hz
      rcases h.1 hz with (e | e) | e
      exacts [h1 e, h2 e, h3 e]
  let S : Filling.Setup := ⟨paperMonicFamily.regular, nodes, hR, zero_regular, r, hr⟩
  exact S.range_eq_closure ρ (fun a ha b c δ hδ => hρ a ha _ ⟨b, c, δ, hδ, rfl⟩) γ₁ γ₂ hγ₁ hγ₂

/-- `fCx` has polynomial coefficients in `t`. -/
theorem fCx_eq : fCx = (Bridge.Fterms famTerms).map (algebraMap ℂ[X] (RatFunc ℂ)) :=
  Bridge.foldr_eq_Fterms famTerms

/-- **Lower inclusion**: the monodromy group sits inside the geometric Galois group, under
a root labelling built from the fibre labelling. Root germs split `f` over the field of
meromorphic germs at the base point (`Germs.splits_rootGerm`), and analytic continuation preserves
every relation among them with coefficients in `ℂ(t)` (`Relations.relations_monodromy`). -/
theorem monodromy_le_geometric_galois (e : paperMonicFamily.Fiber base ≃ Fin 65) :
    ∃ βC : fCx.rootSet fCx.SplittingField ≃ Fin 65,
      monodromyGroup e ≤ (Gal.galActionHom fCx fCx.SplittingField).range.map
        (Equiv.permCongrHom βC).toMonoidHom := by
  have h := Bridge.bridge paperMonicFamily base _ Bridge.paper_hF e
  rw [← fCx_eq] at h
  obtain ⟨βC, hle, -⟩ := h
  exact ⟨βC, hle⟩

/-- **The converse of the analytic bridge**. A permutation of the fibre that preserves every
polynomial relation over `ℂ(t)` among the root germs at the base point is a monodromy
(`Converse.converse`): the orbit polynomial `∏_{h ∈ M} (Z - Σ cₓ r_{h x})` has path-independent
holomorphic coefficients on the regular locus, bounded near the finitely many bad points and of
polynomial growth, hence polynomial (`PolyGrowth.eq_polynomial_of_growth`); it is then a relation,
and separating weights identify the permutation with a monodromy. -/
theorem monodromy_converse : Bridge.Converse paperMonicFamily base :=
  Converse.converse (Bridge.Fterms famTerms) Bridge.paper_hF

/-- **Analytic bridge** (from `monodromy_converse`). The labelling is carried across: the
fibre labelling `e` over the base point goes in, and the root labelling `βC` of the splitting field
comes out. -/
theorem monodromy_eq_geometric_galois (e : paperMonicFamily.Fiber base ≃ Fin 65) :
    ∃ βC : fCx.rootSet fCx.SplittingField ≃ Fin 65,
      (Gal.galActionHom fCx fCx.SplittingField).range.map
        (Equiv.permCongrHom βC).toMonoidHom = monodromyGroup e := by
  have h := Bridge.bridge paperMonicFamily base _ Bridge.paper_hF e
  rw [← fCx_eq] at h
  obtain ⟨βC, -, heq, -⟩ := h
  exact ⟨βC, heq monodromy_converse⟩

/-- **Constant-field comparison and arithmetic descent**. Under compatible root
labellings, the geometric Galois group sits inside the arithmetic one as a normal subgroup.
`GaloisDescent.geometric_normal_in_arithmetic_of_rel` does this for any `F → F'` under relative
normality; `RelNormal.relNormal` supplies relative normality for `ℚ(t) → ℂ(t)`. -/
theorem geometric_normal_in_arithmetic (βC : fCx.rootSet fCx.SplittingField ≃ Fin 65) :
    ∃ β : fRat.rootSet fRat.SplittingField ≃ Fin 65,
      ((Gal.galActionHom fCx fCx.SplittingField).range.map
          (Equiv.permCongrHom βC).toMonoidHom ≤
        (Gal.galActionHom fRat fRat.SplittingField).range.map
          (Equiv.permCongrHom β).toMonoidHom) ∧
      ∀ a ∈ (Gal.galActionHom fRat fRat.SplittingField).range.map
              (Equiv.permCongrHom β).toMonoidHom,
        ∀ g ∈ (Gal.galActionHom fCx fCx.SplittingField).range.map
              (Equiv.permCongrHom βC).toMonoidHom,
          a * g * a⁻¹ ∈ (Gal.galActionHom fCx fCx.SplittingField).range.map
              (Equiv.permCongrHom βC).toMonoidHom := by
  have : Fact ((fRat.map (algebraMap (RatFunc ℚ) fCx.SplittingField)).Splits) :=
    ⟨by rw [IsScalarTower.algebraMap_eq (RatFunc ℚ) (RatFunc ℂ) fCx.SplittingField,
      ← Polynomial.map_map, fRat_map_eq]; exact SplittingField.splits _⟩
  exact (GaloisDescent.geometric_normal_in_arithmetic_of_rel fRat fCx fRat_map_eq
    RelNormal.relNormal βC).imp fun _ h => h.1

/-- The monodromy group is `G`: the loops near the nodes act trivially, so the monodromy image is
generated by the two certified polylines, whose monodromies are `σ₁` and `σ₂`. -/
theorem monodromyGroup_eq_of (e : paperMonicFamily.Fiber base ≃ Fin 65) {γ₁ γ₂ : Path base base}
    (hp₁ : ∀ u, (γ₁ u).1 = Meridian1.chain.poly 40 (Meridian1.chain.n - 1) u)
    (hp₂ : ∀ u, (γ₂ u).1 = Meridian1.chain2.poly 40 (Meridian1.chain2.n - 1) u)
    (h₁ : ∀ i, e (paperMonicFamily.isCoveringMap.monodromy (Path.Homotopic.Quotient.mk γ₁)
      (e.symm i)) = σ₁ i)
    (h₂ : ∀ i, e (paperMonicFamily.isCoveringMap.monodromy (Path.Homotopic.Quotient.mk γ₂)
      (e.symm i)) = σ₂ i) :
    monodromyGroup e = G := by
  obtain ⟨nodes, hbad⟩ := bad_set_eq
  set F := paperMonicFamily.isCoveringMap.monodromyPerm base with hF
  set g₁ := FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₁) with hg₁
  set g₂ := FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ₂) with hg₂
  -- at each node, a radius within which every supported loop acts trivially
  have hrad : ∀ a : ℂ, ∃ r > 0, a ∈ nodes → ∀ γ, SupportedWithin a r γ → F γ = 1 := by
    intro a
    by_cases ha : a ∈ nodes
    · obtain ⟨r, hr, htriv⟩ := node_monodromy_trivial hbad ha
      exact ⟨r, hr, fun _ => htriv⟩
    · exact ⟨1, one_pos, fun h => absurd h ha⟩
  choose r hr htriv using hrad
  -- the monodromy image is generated by the two certified loops
  have hrange : F.range = Subgroup.closure {F g₁, F g₂} :=
    meridian_generation hbad hp₁ hp₂ r (fun a _ => hr a) F (fun a ha g hg => htriv a ha g hg)
  -- transport along the labelling
  have hσ₁ : (Equiv.permCongrHom e).toMonoidHom (F g₁) = σ₁ := Equiv.ext h₁
  have hσ₂ : (Equiv.permCongrHom e).toMonoidHom (F g₂) = σ₂ := Equiv.ext h₂
  rw [monodromyGroup, ← hF, hrange, MonoidHom.map_closure, Set.image_insert_eq,
    Set.image_singleton, hσ₁, hσ₂]
  rfl

theorem monodromyGroup_eq :
    ∃ e : paperMonicFamily.Fiber base ≃ Fin 65, monodromyGroup e = G := by
  obtain ⟨e, γ₁, γ₂, hp₁, hp₂, h₁, h₂⟩ := Meridian1.meridian_monodromy
  exact ⟨e, monodromyGroup_eq_of e hp₁ hp₂ h₁ h₂⟩

/-- **The generic theorem.** The Galois group of `f` over `ℚ(t)`, acting on its 65 roots, is the
explicit group `G`. From the five statements above together with `normalizer_G`: the
monodromy group is `G`, it is the geometric Galois group, and the arithmetic group normalizes
it, hence is contained in `N(G) = G`. -/
theorem generic_galois : ∃ β : fRat.rootSet fRat.SplittingField ≃ Fin 65,
    (Gal.galActionHom fRat fRat.SplittingField).range.map
      (Equiv.permCongrHom β).toMonoidHom = G := by
  obtain ⟨e, hM⟩ := monodromyGroup_eq
  obtain ⟨βC, hβC⟩ := monodromy_eq_geometric_galois e
  obtain ⟨β, hle, hnorm⟩ := geometric_normal_in_arithmetic βC
  rw [hM] at hβC
  rw [hβC] at hle hnorm
  refine ⟨β, le_antisymm (fun a ha => ?_) hle⟩
  have : a ∈ Subgroup.normalizer (G : Set (Equiv.Perm (Fin 65))) := by
    rw [Subgroup.mem_normalizer_iff]
    intro g
    constructor
    · exact fun hg => hnorm a ha g hg
    · intro hg
      have h2 := hnorm a⁻¹ (inv_mem ha) _ hg
      simpa [mul_assoc] using h2
  rwa [normalizer_G] at this

/-! ## Cubic quotient and specialization -/

instance paperSpecialization_splits_ℂ :
    Fact ((paperSpecialization.map (algebraMap ℚ ℂ)).Splits) :=
  ⟨IsAlgClosed.splits _⟩

/-- `fRat` has coefficients in `ℚ[t]`. -/
theorem fRat_eq : SpecFamily.fQ.map (algebraMap ℚ[X] (RatFunc ℚ)) = fRat := SpecFamily.fQ_map

instance fRat_isGalois : IsGalois (RatFunc ℚ) fRat.SplittingField := {}

/-- The specialization `t ↦ -7/5` as an algebra structure. -/
@[instance_reducible]
noncomputable def specAlg : Algebra ℚ[X] ℚ := (evalRingHom (-7 / 5 : ℚ)).toAlgebra

/-- **Specialization into the decomposition group**. For any labelling `β` of the roots of
`f` over `ℚ(t)`, some maximal ideal `P` of the integral closure of `ℚ[t]` in the splitting field lies
over `t = -7/5`, and under some labelling of the roots of `h = f(X, -7/5)` in `ℂ`, `Gal(h/ℚ)` lies in
the labelled image of the decomposition group `Stab(P)`. General theorem:
`Specialize.image_le_decomposition`; inputs: `fQ` monic, `fQ_map`, `fQ_spec`, separability of `h`. -/
theorem specialization_le_decomposition (β : fRat.rootSet fRat.SplittingField ≃ Fin 65) :
    ∃ P : Ideal (integralClosure ℚ[X] fRat.SplittingField), P.IsMaximal ∧
      P.comap (algebraMap ℚ[X] (integralClosure ℚ[X] fRat.SplittingField)) =
        RingHom.ker (evalRingHom (-7 / 5 : ℚ)) ∧
      ∃ β₀ : paperSpecialization.rootSet ℂ ≃ Fin 65,
        (Gal.galActionHom paperSpecialization ℂ).range.map (Equiv.permCongrHom β₀).toMonoidHom ≤
          (MulAction.stabilizer Gal(fRat.SplittingField/RatFunc ℚ) P).map
            ((Equiv.permCongrHom β).toMonoidHom.comp
              ((Gal.galActionHom fRat fRat.SplittingField).comp
                (Gal.restrict fRat fRat.SplittingField))) := by
  let := specAlg
  have hχ : Function.Surjective (algebraMap ℚ[X] ℚ) := fun q => ⟨C q, eval_C⟩
  have hspec : SpecFamily.fQ.map (algebraMap ℚ[X] ℚ) = paperSpecialization := SpecFamily.fQ_spec
  have hsep : (SpecFamily.fQ.map (algebraMap ℚ[X] ℚ)).Separable := by
    rw [hspec]; exact paperSpecialization_separable
  have : Fact (((SpecFamily.fQ.map (algebraMap ℚ[X] (RatFunc ℚ))).map
      (algebraMap (RatFunc ℚ) fRat.SplittingField)).Splits) := by
    rw [fRat_eq]; infer_instance
  have : Fact (((SpecFamily.fQ.map (algebraMap ℚ[X] ℚ)).map (algebraMap ℚ ℂ)).Splits) :=
    ⟨IsAlgClosed.splits _⟩
  have key : ∀ (q : (RatFunc ℚ)[X]) (hq : SpecFamily.fQ.map (algebraMap ℚ[X] (RatFunc ℚ)) = q)
      (h₀ : ℚ[X]) (hh : SpecFamily.fQ.map (algebraMap ℚ[X] ℚ) = h₀)
      [Fact ((q.map (algebraMap (RatFunc ℚ) fRat.SplittingField)).Splits)]
      [Fact ((h₀.map (algebraMap ℚ ℂ)).Splits)] (β : q.rootSet fRat.SplittingField ≃ Fin 65),
      ∃ P : Ideal (integralClosure ℚ[X] fRat.SplittingField), P.IsMaximal ∧
        P.comap (algebraMap ℚ[X] (integralClosure ℚ[X] fRat.SplittingField)) =
          RingHom.ker (algebraMap ℚ[X] ℚ) ∧
        ∃ β₀ : h₀.rootSet ℂ ≃ Fin 65,
          (Gal.galActionHom h₀ ℂ).range.map (Equiv.permCongrHom β₀).toMonoidHom ≤
            (MulAction.stabilizer Gal(fRat.SplittingField/RatFunc ℚ) P).map
              ((Equiv.permCongrHom β).toMonoidHom.comp
                ((Gal.galActionHom q fRat.SplittingField).comp
                  (Gal.restrict q fRat.SplittingField))) := by
    intro q hq h₀ hh _ _ β
    subst hq hh
    exact Specialize.image_le_decomposition hχ SpecFamily.fQ SpecFamily.fQ_monic hsep β
  exact key fRat fRat_eq paperSpecialization hspec β

/-- **Split-witness consumer**. To show that a decomposition element over `t = -7/5` acts in
`N`, it suffices to have an integral element `θ`, a polynomial `c ∈ ℚ[t][Y]` killing it whose
specialization at `t = -7/5` splits into distinct rational linear factors, and the fact that every
element of `Gal(L/ℚ(t))` fixing `θ` acts in `N`. -/
theorem decomposition_le_of_split_witness (β : fRat.rootSet fRat.SplittingField ≃ Fin 65)
    (θ : integralClosure ℚ[X] fRat.SplittingField) (c : ℚ[X][X]) {ι : Type*} [Fintype ι]
    (a : ι → ℚ) (ha : Function.Injective a) (hroot : aeval θ c = 0)
    (hfibre : c.map (evalRingHom (-7 / 5 : ℚ)) = ∏ i, (X - C (a i)))
    (hdetect : ∀ g : Gal(fRat.SplittingField/RatFunc ℚ), g • θ = θ →
      Equiv.permCongr β (Gal.galActionHom fRat _ (Gal.restrict fRat _ g)) ∈ N)
    (P : Ideal (integralClosure ℚ[X] fRat.SplittingField)) [P.IsPrime]
    (hP : P.comap (algebraMap ℚ[X] (integralClosure ℚ[X] fRat.SplittingField)) =
      RingHom.ker (evalRingHom (-7 / 5 : ℚ)))
    (g : Gal(fRat.SplittingField/RatFunc ℚ)) (hg : g ∈ MulAction.stabilizer _ P) :
    Equiv.permCongr β (Gal.galActionHom fRat _ (Gal.restrict fRat _ g)) ∈ N := by
  let := specAlg
  have hχ : Function.Surjective (algebraMap ℚ[X] ℚ) := fun q => ⟨C q, eval_C⟩
  exact hdetect g (Specialize.smul_eq_self_of_split (K := RatFunc ℚ) hχ hP hroot ha hfibre hg)

/-- The roots of `f` over `ℚ(t)` under a labelling, scaled by `13³`. -/
noncomputable def yRoot (β : fRat.rootSet fRat.SplittingField ≃ Fin 65) (i : Fin 65) :
    fRat.SplittingField :=
  13 ^ 3 * (β.symm i : fRat.SplittingField)

/-- The elementary symmetric functions of the three values `Θ(1), Θ(σ₁), Θ(σ₁²)`. -/
noncomputable def symΘ (β : fRat.rootSet fRat.SplittingField ≃ Fin 65) :
    Fin 3 → fRat.SplittingField :=
  ![Resolvent.Θ (yRoot β) N 1 + Resolvent.Θ (yRoot β) N σ₁ + Resolvent.Θ (yRoot β) N (σ₁ ^ 2),
    Resolvent.Θ (yRoot β) N 1 * Resolvent.Θ (yRoot β) N σ₁ +
      Resolvent.Θ (yRoot β) N 1 * Resolvent.Θ (yRoot β) N (σ₁ ^ 2) +
      Resolvent.Θ (yRoot β) N σ₁ * Resolvent.Θ (yRoot β) N (σ₁ ^ 2),
    Resolvent.Θ (yRoot β) N 1 * Resolvent.Θ (yRoot β) N σ₁ * Resolvent.Θ (yRoot β) N (σ₁ ^ 2)]

/-- The claimed values, over `ℤ`. -/
noncomputable def symZ : Fin 3 → ℤ[X] := ![Resolvent.Z1, Resolvent.Z2, Resolvent.Z3]

/-- `ℚ[t] → L` is injective. -/
theorem algebraMap_poly_injective : Function.Injective (algebraMap ℚ[X] fRat.SplittingField) := by
  rw [IsScalarTower.algebraMap_eq ℚ[X] (RatFunc ℚ) fRat.SplittingField]
  exact (algebraMap (RatFunc ℚ) fRat.SplittingField).injective.comp
    (IsFractionRing.injective ℚ[X] (RatFunc ℚ))

/-- Evaluating the family's foldr under a ring hom from `ℚ(t)`. -/
theorem eval₂_foldr {E : Type*} [Field E] [Algebra ℚ E] (g : RatFunc ℚ →+* E) {tE : E}
    (hg : ∀ c : ℚ, g (algebraMap ℚ (RatFunc ℚ) c) = algebraMap ℚ E c) (hX : g RatFunc.X = tE)
    (x : E) (ts : List (ℕ × ℕ × ℚ)) :
    (ts.foldr (fun (a : ℕ × ℕ × ℚ) (acc : (RatFunc ℚ)[X]) =>
      C (algebraMap ℚ (RatFunc ℚ) a.2.2 * RatFunc.X ^ a.2.1) * X ^ a.1 + acc) 0).eval₂ g x =
      ts.foldr (fun (a : ℕ × ℕ × ℚ) (acc : E) => algebraMap ℚ E a.2.2 * tE ^ a.2.1 * x ^ a.1 + acc)
        0 := by
  induction ts with
  | nil => simp
  | cons a l ih =>
    rw [List.foldr_cons, List.foldr_cons, eval₂_add, ih, eval₂_mul, eval₂_C, eval₂_X_pow, map_mul,
      map_pow, hg, hX]

/-- **Degree bound (R2)**. The `m`-th symmetric function (`m = 0, 1, 2`) has degree at
most `2(m + 1)`.

Proof: in the algebraic closure `E` of `L`, pick `τ` with `τ¹³ t = 1`. The roots satisfy the family's
equation at `t`, so `τ²⁸ Θ` is integral over `ℚ[τ]` (`DegreeBound.isIntegralElem_Θ`), hence so is
`τ^(28(m+1))` times the `m`-th symmetric function, which is `Q(t)`; and `t` is transcendental, so
`13 · deg Q ≤ 28 (m + 1)` (`DegreeBound.natDegree_le_of_isIntegralElem`). -/
theorem sym_natDegree_le (β : fRat.rootSet fRat.SplittingField ≃ Fin 65)
    (_hβ : (Gal.galActionHom fRat fRat.SplittingField).range.map
      (Equiv.permCongrHom β).toMonoidHom = G) (m : Fin 3) (Q : ℚ[X])
    (hQ : symΘ β m = algebraMap ℚ[X] fRat.SplittingField Q) : Q.natDegree ≤ 2 * ((m : ℕ) + 1) := by
  classical
  let E := AlgebraicClosure fRat.SplittingField
  let φ : fRat.SplittingField →+* E := algebraMap _ _
  let tE : E := φ (algebraMap (RatFunc ℚ) fRat.SplittingField RatFunc.X)
  -- evaluation at `tE` is `φ ∘ algebraMap`
  have hev : ∀ R : ℚ[X], R.eval₂ (algebraMap ℚ E) tE = φ (algebraMap ℚ[X] fRat.SplittingField R) := by
    intro R
    have h := Polynomial.ringHom_ext (f := eval₂RingHom (algebraMap ℚ E) tE)
      (g := φ.comp (algebraMap ℚ[X] fRat.SplittingField))
      (fun c => by
        simp only [coe_eval₂RingHom, eval₂_C, RingHom.coe_comp, Function.comp_apply]
        exact congrArg (· c) (RingHom.ext_rat (algebraMap ℚ E)
          (φ.comp ((algebraMap ℚ[X] fRat.SplittingField).comp C))))
      (by
        simp only [coe_eval₂RingHom, eval₂_X, RingHom.coe_comp, Function.comp_apply, tE,
          IsScalarTower.algebraMap_apply ℚ[X] (RatFunc ℚ) fRat.SplittingField, RatFunc.algebraMap_X])
    exact congrArg (· R) h
  have ht : ∀ R : ℚ[X], R ≠ 0 → R.eval₂ (algebraMap ℚ E) tE ≠ 0 := fun R hR => by
    rw [hev, map_ne_zero_iff _ φ.injective, map_ne_zero_iff _ algebraMap_poly_injective]; exact hR
  have htE0 : tE ≠ 0 := by
    have := ht X X_ne_zero; rwa [eval₂_X] at this
  -- `τ¹³ t = 1`
  obtain ⟨τ, hτroot⟩ := IsAlgClosed.exists_root (X ^ 13 - C tE⁻¹ : E[X])
    (by rw [degree_X_pow_sub_C (by norm_num)]; norm_num)
  have hτ : τ ^ 13 * tE = 1 := by
    have h := hτroot
    rw [IsRoot, eval_sub, eval_pow, eval_X, eval_C, sub_eq_zero] at h
    rw [h, inv_mul_cancel₀ htE0]
  -- the roots in `E`
  let x : Fin 65 → E := fun i => φ (β.symm i : fRat.SplittingField)
  have hx : ∀ i, famTerms.foldr
      (fun a acc => algebraMap ℚ E a.2.2 * tE ^ a.2.1 * x i ^ a.1 + acc) 0 = 0 := by
    intro i
    have hr := (mem_rootSet'.1 (β.symm i).2).2
    rw [aeval_def] at hr
    have h := congrArg φ hr
    rw [Polynomial.hom_eval₂, map_zero] at h
    have hg : ∀ c : ℚ, (φ.comp (algebraMap (RatFunc ℚ) fRat.SplittingField))
        (algebraMap ℚ (RatFunc ℚ) c) = algebraMap ℚ E c := fun c =>
      congrArg (fun f => f c) (RingHom.ext_rat
        ((φ.comp (algebraMap (RatFunc ℚ) fRat.SplittingField)).comp (algebraMap ℚ (RatFunc ℚ)))
        (algebraMap ℚ E))
    rw [← eval₂_foldr (φ.comp (algebraMap (RatFunc ℚ) fRat.SplittingField)) (tE := tE) hg rfl (x i)]
    exact h
  -- transport of the invariant values
  have hΘ : ∀ π, φ (Resolvent.Θ (yRoot β) N π) = Resolvent.Θ (fun i => 13 ^ 3 * x i) N π := by
    intro π
    have h := Resolvent.map_Θ φ (yRoot β) (fun i => 13 ^ 3 * x i) 1 (fun i => by
      simp only [yRoot, x, map_mul, map_pow, map_ofNat, Equiv.Perm.coe_one, id_eq]) N π
    rwa [one_mul] at h
  have hint : ∀ π, (DegreeBound.ev τ).IsIntegralElem
      (τ ^ 28 * Resolvent.Θ (fun i => 13 ^ 3 * x i) N π) :=
    fun π => DegreeBound.isIntegralElem_Θ hτ hx N π
  set a0 := τ ^ 28 * Resolvent.Θ (fun i => 13 ^ 3 * x i) N 1
  set a1 := τ ^ 28 * Resolvent.Θ (fun i => 13 ^ 3 * x i) N σ₁
  set a2 := τ ^ 28 * Resolvent.Θ (fun i => 13 ^ 3 * x i) N (σ₁ ^ 2)
  have hQE : Q.eval₂ (algebraMap ℚ E) tE = φ (symΘ β m) := by rw [hev, hQ]
  have hkey : (DegreeBound.ev τ).IsIntegralElem
      (τ ^ (28 * ((m : ℕ) + 1)) * Q.eval₂ (algebraMap ℚ E) tE) := by
    rw [hQE]
    fin_cases m
    · have : τ ^ (28 * ((0 : ℕ) + 1)) * φ (symΘ β 0) = a0 + a1 + a2 := by
        simp only [symΘ, Matrix.cons_val_zero, map_add, hΘ, a0, a1, a2]; ring
      simp only [Fin.zero_eta] at this ⊢
      rw [this]
      exact DegreeBound.isIntegralElem_add (DegreeBound.isIntegralElem_add (hint _) (hint _))
        (hint _)
    · have : τ ^ (28 * ((1 : ℕ) + 1)) * φ (symΘ β 1) = a0 * a1 + a0 * a2 + a1 * a2 := by
        simp only [symΘ, Matrix.cons_val_one, Matrix.cons_val_zero, map_add, map_mul, hΘ, a0, a1,
          a2]
        ring
      simp only [Fin.mk_one] at this ⊢
      rw [this]
      exact DegreeBound.isIntegralElem_add (DegreeBound.isIntegralElem_add
        (DegreeBound.isIntegralElem_mul (hint _) (hint _))
        (DegreeBound.isIntegralElem_mul (hint _) (hint _)))
        (DegreeBound.isIntegralElem_mul (hint _) (hint _))
    · have : τ ^ (28 * ((2 : ℕ) + 1)) * φ (symΘ β 2) = a0 * a1 * a2 := by
        simp only [symΘ, Matrix.cons_val_two, Matrix.head_cons, Matrix.tail_cons, map_mul, hΘ, a0,
          a1, a2]
        ring
      simp only [Fin.reduceFinMk, Fin.isValue] at this ⊢
      rw [this]
      exact DegreeBound.isIntegralElem_mul (DegreeBound.isIntegralElem_mul (hint _) (hint _))
        (hint _)
  have h13 := DegreeBound.natDegree_le_of_isIntegralElem hτ ht hkey
  have := m.isLt
  omega

/-- `N ≤ G`. -/
theorem N_le_G : N ≤ G := by
  rw [N, Subgroup.commutator_le]
  intro g₁ hg₁ g₂ hg₂
  rw [commutatorElement_def]
  exact G.mul_mem (G.mul_mem (G.mul_mem hg₁ hg₂) (G.inv_mem hg₁)) (G.inv_mem hg₂)

theorem card_G_eq : Nat.card G = 3 * Nat.card N := by rw [card_G, card_N]

theorem sigma1_mem_G : σ₁ ∈ G := Subgroup.subset_closure (by simp)

/-- `σ₁` and `σ₁²` have order 3, which does not divide `|N| = 29120`. -/
theorem sigma1_not_mem_N : σ₁ ∉ N ∧ σ₁ ^ 2 ∉ N := by
  have h3 : σ₁ ^ 3 = 1 := by decide +kernel
  have h1 : σ₁ ≠ 1 := by decide +kernel
  have h2 : σ₁ ^ 2 ≠ 1 := by decide +kernel
  have key : ∀ x : Equiv.Perm (Fin 65), x ^ 3 = 1 → x ≠ 1 → x ∉ N := fun x hx3 hx1 hx => by
    have ho : orderOf x = 3 := orderOf_eq_prime hx3 hx1
    have hd := orderOf_dvd_natCard (⟨x, hx⟩ : N)
    rw [← orderOf_submonoid, card_N] at hd
    simp only at hd
    rw [ho] at hd
    norm_num at hd
  exact ⟨key σ₁ h3 h1, key (σ₁ ^ 2) (by rw [← pow_mul, show 2 * 3 = 3 * 2 from rfl, pow_mul, h3,
    one_pow]) h2⟩

/-- **Integer polynomials (R1)**. Each symmetric function lies in `ℤ[t]`.

Proof: every Galois element acts on labels as some `ρ ∈ G` and sends `Θ(σ₁^j)` to `Θ(ρ σ₁^j)`, and
left multiplication by `ρ` permutes the three cosets `σ₁^j N` (`Resolvent.exists_perm_pow_mul`), so
the symmetric functions are fixed and lie in `ℚ(t)`. The roots scaled by `13³` are roots of the monic
`IntModel.fZ ∈ ℤ[t][X]`, so the symmetric functions are integral over `ℤ[t]`; `ℚ[t]` is integrally
closed, and a polynomial over `ℚ` integral over `ℤ[X]` has integer coefficients. -/
theorem sym_int (β : fRat.rootSet fRat.SplittingField ≃ Fin 65)
    (hβ : (Gal.galActionHom fRat fRat.SplittingField).range.map
      (Equiv.permCongrHom β).toMonoidHom = G) (m : Fin 3) :
    ∃ Q : ℤ[X], symΘ β m = algebraMap ℚ[X] fRat.SplittingField (Q.map (Int.castRingHom ℚ)) := by
  classical
  obtain ⟨hs1, hs2⟩ := sigma1_not_mem_N
  let θ : Fin 3 → fRat.SplittingField := fun j => Resolvent.Θ (yRoot β) N (σ₁ ^ (j : ℕ))
  have hθ0 : θ 0 = Resolvent.Θ (yRoot β) N 1 := by simp [θ]
  have hθ1 : θ 1 = Resolvent.Θ (yRoot β) N σ₁ := by simp [θ]
  have hθ2 : θ 2 = Resolvent.Θ (yRoot β) N (σ₁ ^ 2) := by simp [θ]
  have hs0 : symΘ β 0 = ∑ j, θ j := by
    simp only [symΘ, Matrix.cons_val_zero, Fin.sum_univ_three, hθ0, hθ1, hθ2]
  have hsq : 2 * symΘ β 1 = (∑ j, θ j) ^ 2 - ∑ j, θ j ^ 2 := by
    simp only [symΘ, Matrix.cons_val_one, Matrix.cons_val_zero, Fin.sum_univ_three, hθ0, hθ1, hθ2]
    ring
  have hs2' : symΘ β 2 = ∏ j, θ j := by
    simp only [symΘ, Matrix.cons_val_two, Matrix.tail_cons, Matrix.head_cons, Fin.prod_univ_three,
      hθ0, hθ1, hθ2]
  -- Galois invariance
  have hfix : ∀ g : Gal(fRat.SplittingField/RatFunc ℚ), g (symΘ β m) = symΘ β m := by
    intro g
    set ρ := Equiv.permCongr β (Gal.galActionHom fRat _ (Gal.restrict fRat _ g)) with hρ
    have hρG : ρ ∈ G := by rw [← hβ]; exact ⟨_, ⟨Gal.restrict fRat _ g, rfl⟩, rfl⟩
    have hmap : ∀ π, g (Resolvent.Θ (yRoot β) N π) = Resolvent.Θ (yRoot β) N (ρ * π) := by
      intro π
      refine Resolvent.map_Θ (g : fRat.SplittingField →+* fRat.SplittingField) (yRoot β) (yRoot β)
        ρ (fun i => ?_) N π
      simp only [yRoot, RingHom.coe_coe, map_mul, map_pow, map_ofNat, hρ, Equiv.permCongr_apply,
        Equiv.symm_apply_apply]
      rw [Gal.galActionHom_restrict]
    obtain ⟨k, hk⟩ := Resolvent.exists_perm_pow_mul N_le_G card_G_eq sigma1_mem_G hs1 hs2 hρG
    have hgθ : ∀ j, g (θ j) = θ (k j) := fun j => by
      obtain ⟨n, hn, h⟩ := hk j
      simp only [θ]
      rw [hmap, h, Resolvent.Θ_mul_mem _ _ _ hn]
    have hsum : g (∑ j, θ j) = ∑ j, θ j := by
      rw [map_sum]; simp only [hgθ]; exact Equiv.sum_comp k θ
    have hsumsq : g (∑ j, θ j ^ 2) = ∑ j, θ j ^ 2 := by
      rw [map_sum]; simp only [map_pow, hgθ]; exact Equiv.sum_comp k (fun j => θ j ^ 2)
    have hprod : g (∏ j, θ j) = ∏ j, θ j := by
      rw [map_prod]; simp only [hgθ]; exact Equiv.prod_comp k θ
    fin_cases m
    · simp only [Fin.zero_eta]; rw [hs0, hsum]
    · simp only [Fin.mk_one]
      have h2 : (2 : fRat.SplittingField) ≠ 0 := two_ne_zero
      apply mul_left_cancel₀ h2
      have := congrArg g hsq
      rw [map_mul, map_ofNat, map_sub, map_pow, hsum, hsumsq] at this
      rw [this, hsq]
    · simp only [Fin.reduceFinMk, Fin.isValue]; rw [hs2', hprod]
  -- so it lies in `ℚ(t)`
  have hK : symΘ β m ∈ (⊥ : IntermediateField (RatFunc ℚ) fRat.SplittingField) := by
    rw [IsGalois.mem_bot_iff_fixed]; exact hfix
  obtain ⟨r, hr⟩ := IntermediateField.mem_bot.1 hK
  -- integrality over `ℤ[t]`
  let κK : ℤ[X] →+* RatFunc ℚ := (algebraMap ℚ[X] (RatFunc ℚ)).comp (mapRingHom (Int.castRingHom ℚ))
  let κ : ℤ[X] →+* fRat.SplittingField := (algebraMap (RatFunc ℚ) fRat.SplittingField).comp κK
  have hκX : κ X = algebraMap (RatFunc ℚ) fRat.SplittingField RatFunc.X := by
    simp [κ, κK, RatFunc.algebraMap_X]
  have hy : ∀ i, κ.IsIntegralElem (yRoot β i) := by
    intro i
    have hr0 := (mem_rootSet'.1 (β.symm i).2).2
    rw [aeval_def] at hr0
    have hg : ∀ c : ℚ, algebraMap (RatFunc ℚ) fRat.SplittingField (algebraMap ℚ (RatFunc ℚ) c) =
        algebraMap ℚ fRat.SplittingField c := fun c =>
      congrArg (fun f => f c) (RingHom.ext_rat
        ((algebraMap (RatFunc ℚ) fRat.SplittingField).comp (algebraMap ℚ (RatFunc ℚ)))
        (algebraMap ℚ fRat.SplittingField))
    have hroot := eval₂_foldr (algebraMap (RatFunc ℚ) fRat.SplittingField)
      (tE := algebraMap (RatFunc ℚ) fRat.SplittingField RatFunc.X) hg rfl
      (β.symm i : fRat.SplittingField) famTerms
    refine ⟨IntModel.fZ, IntModel.fZ_monic, ?_⟩
    rw [yRoot, IntModel.fZ_eval κ hκX, ← hroot]
    change _ * fRat.eval₂ _ _ = 0
    rw [hr0, mul_zero]
  have hθint : ∀ j, κ.IsIntegralElem (θ j) := fun j => IntModel.isIntegralElem_Θ κ hy N _
  have hsymint : κ.IsIntegralElem (symΘ β m) := by
    fin_cases m
    · rw [show symΘ β ⟨0, by norm_num⟩ = symΘ β 0 from rfl, hs0, Fin.sum_univ_three]
      exact IntModel.isIntegralElem_add κ (IntModel.isIntegralElem_add κ (hθint 0) (hθint 1))
        (hθint 2)
    · show κ.IsIntegralElem (symΘ β 1)
      simp only [symΘ, Matrix.cons_val_one, Matrix.cons_val_zero]
      rw [← hθ0, ← hθ1, ← hθ2]
      exact IntModel.isIntegralElem_add κ (IntModel.isIntegralElem_add κ
        (IntModel.isIntegralElem_mul κ (hθint 0) (hθint 1))
        (IntModel.isIntegralElem_mul κ (hθint 0) (hθint 2)))
        (IntModel.isIntegralElem_mul κ (hθint 1) (hθint 2))
    · show κ.IsIntegralElem (symΘ β 2)
      rw [hs2', Fin.prod_univ_three]
      exact IntModel.isIntegralElem_mul κ (IntModel.isIntegralElem_mul κ (hθint 0) (hθint 1))
        (hθint 2)
  -- descend to `ℚ(t)`, then to `ℚ[t]`, then to `ℤ[t]`
  rw [← hr] at hsymint
  have hrint : κK.IsIntegralElem r :=
    IntModel.isIntegralElem_of_comp κK _ (algebraMap (RatFunc ℚ) fRat.SplittingField).injective
      hsymint
  obtain ⟨p, hpm, hp⟩ := hrint
  have hrQ : IsIntegral ℚ[X] r := by
    refine ⟨p.map (mapRingHom (Int.castRingHom ℚ)), hpm.map _, ?_⟩
    rw [eval₂_map]; exact hp
  obtain ⟨Q, hQ⟩ := IsIntegrallyClosed.algebraMap_eq_of_integral hrQ
  have hQint : (mapRingHom (Int.castRingHom ℚ)).IsIntegralElem Q := by
    refine ⟨p, hpm, IsFractionRing.injective ℚ[X] (RatFunc ℚ) ?_⟩
    rw [Polynomial.hom_eval₂, map_zero, hQ]; exact hp
  obtain ⟨Z, hZ⟩ := IntModel.int_of_isIntegral hQint
  refine ⟨Z, ?_⟩
  rw [hZ, ← hr, ← hQ, ← IsScalarTower.algebraMap_apply]

/-! ### The germ link -/

/-- Step 0 of the first certified meridian: the 65 discs over `t = 0` in the paper's root order. -/
abbrev st0 : StepDatum := Meridian1.chain.st 0

/-- **Germ link** for a labelling `β` of the roots of `f` over `ℚ(t)`: every polynomial relation with
coefficients in `ℚ[t]` among the labelled roots holds for the certified roots at every parameter `t`
of the step-0 ball, where the root labelled `i` is the unique root of `f(·, t)` in disc `i`. -/
def GermLink (β : fRat.rootSet fRat.SplittingField ≃ Fin 65) : Prop :=
  ∀ P : MvPolynomial (Fin 65) ℚ[X],
    MvPolynomial.aeval (fun i => (β.symm i : fRat.SplittingField)) P = 0 →
    ∀ t : ℂ, ‖t‖ < (st0.S : ℝ) / 2 ^ 40 → ∀ z : Fin 65 → ℂ,
      (∀ i, (paperFamily t).eval (z i) = 0 ∧ InDisc 20 st0 i (z i)) →
      MvPolynomial.eval₂ (eval₂RingHom (algebraMap ℚ ℂ) t) z P = 0

/-- **Labelled meridians**. The fibre labelling of the certified meridians is the step-0
disc labelling. -/
theorem meridian_monodromy_labelled : ∃ (e : paperMonicFamily.Fiber base ≃ Fin 65)
    (γ₁ γ₂ : Path base base),
    (∀ u, (γ₁ u).1 = Meridian1.chain.poly 40 (Meridian1.chain.n - 1) u) ∧
    (∀ u, (γ₂ u).1 = Meridian1.chain2.poly 40 (Meridian1.chain2.n - 1) u) ∧
    (∀ i, e (paperMonicFamily.isCoveringMap.monodromy (Path.Homotopic.Quotient.mk γ₁)
      (e.symm i)) = σ₁ i) ∧
    (∀ i, e (paperMonicFamily.isCoveringMap.monodromy (Path.Homotopic.Quotient.mk γ₂)
      (e.symm i)) = σ₂ i) ∧
    ∀ i : Fin 65, InDisc 20 st0 i (e.symm i).root := by
  have hb0 : ((base : paperMonicFamily.Base) : ℂ) = ptC 40 (Meridian1.chain.wp 0) := by
    rw [Meridian1.wp_zero]; simp [ptC]
  have hb0' : ((base : paperMonicFamily.Base) : ℂ) = ptC 40 (Meridian1.chain2.wp 0) := by
    rw [Meridian1.wp2_zero]; simp [ptC]
  obtain ⟨hc, ht, γ₁, hγ₁, hmono₁⟩ := Chain.loop_monodromy Meridian1.chain_steps_cert
    Meridian1.chain_legs_all (by rw [Meridian1.chain_n_eq]; norm_num) Meridian1.closed base hb0 st0 rfl
  obtain ⟨hc', ht', γ₂, hγ₂, hmono₂⟩ := Chain.loop_monodromy Meridian1.steps2_cert
    Meridian1.chain2_legs_all (by rw [Meridian1.chain2_n_eq]; norm_num) Meridian1.closed2 base hb0'
    st0 rfl
  exact ⟨labelEquiv hc ht, γ₁, γ₂, hγ₁, hγ₂,
    fun i => Fin.ext ((hmono₁ i).trans (Meridian1.lab_eq i)),
    fun i => Fin.ext ((hmono₂ i).trans (Meridian1.lab2_eq i)), labelEquiv_symm_spec hc ht⟩

/-- **The generic theorem, labelled**. A labelling `β` with image `G`, the step-0 disc
labelling `e` of the fibre over `t = 0`, and a ring hom from the splitting field over `ℚ(t)` to the
field of meromorphic germs at `0` that sends the root labelled `i` to the germ of the root branch
labelled `i` and is compatible with `ℚ(t) → ℂ(t)`. -/
theorem generic_galois_labelled : ∃ (e : paperMonicFamily.Fiber base ≃ Fin 65)
    (β : fRat.rootSet fRat.SplittingField ≃ Fin 65)
    (Φ : fRat.SplittingField →+* Germs.Mer (base : ℂ)),
    (Gal.galActionHom fRat fRat.SplittingField).range.map (Equiv.permCongrHom β).toMonoidHom = G ∧
    (∀ i : Fin 65, InDisc 20 st0 i (e.symm i).root) ∧
    (∀ i, Φ (β.symm i : fRat.SplittingField) = Germs.rootGerm paperMonicFamily base (e.symm i)) ∧
    ∀ r : RatFunc ℚ, Φ (algebraMap (RatFunc ℚ) fRat.SplittingField r) =
      algebraMap (RatFunc ℂ) (Germs.Mer (base : ℂ)) (algebraMap (RatFunc ℚ) (RatFunc ℂ) r) := by
  obtain ⟨e, γ₁, γ₂, hp₁, hp₂, h₁, h₂, hdisc⟩ := meridian_monodromy_labelled
  have hM := monodromyGroup_eq_of e hp₁ hp₂ h₁ h₂
  have hbr := Bridge.bridge paperMonicFamily base _ Bridge.paper_hF e
  rw [← fCx_eq] at hbr
  obtain ⟨βC, -, heq, ιM, hιM⟩ := hbr
  have hβC : (Gal.galActionHom fCx fCx.SplittingField).range.map
      (Equiv.permCongrHom βC).toMonoidHom = G := (heq monodromy_converse).trans hM
  have : Fact ((fRat.map (algebraMap (RatFunc ℚ) fCx.SplittingField)).Splits) :=
    ⟨by rw [IsScalarTower.algebraMap_eq (RatFunc ℚ) (RatFunc ℂ) fCx.SplittingField,
      ← Polynomial.map_map, fRat_map_eq]; exact SplittingField.splits _⟩
  obtain ⟨β, ⟨hle, hnorm⟩, j, hj⟩ := GaloisDescent.geometric_normal_in_arithmetic_of_rel fRat fCx
    fRat_map_eq RelNormal.relNormal βC
  rw [hβC] at hle hnorm
  have himage : (Gal.galActionHom fRat fRat.SplittingField).range.map
      (Equiv.permCongrHom β).toMonoidHom = G := by
    refine le_antisymm (fun a ha => ?_) hle
    have : a ∈ Subgroup.normalizer (G : Set (Equiv.Perm (Fin 65))) := by
      rw [Subgroup.mem_normalizer_iff]
      intro g
      constructor
      · exact fun hg => hnorm a ha g hg
      · intro hg
        have h2 := hnorm a⁻¹ (inv_mem ha) _ hg
        simpa [mul_assoc] using h2
    rwa [normalizer_G] at this
  refine ⟨e, β, (ιM.toRingHom.comp j.toRingHom), himage, hdisc, fun i => ?_, fun r => ?_⟩
  · simp only [RingHom.coe_comp, Function.comp_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe]
    rw [hj, hιM]
  · simp only [RingHom.coe_comp, Function.comp_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe]
    rw [j.commutes, IsScalarTower.algebraMap_apply (RatFunc ℚ) (RatFunc ℂ) fCx.SplittingField,
      ιM.commutes]

theorem st0_cert : st0.Cert 40 20 := by
  have hb0 : ((⟨0, zero_regular⟩ : paperMonicFamily.Base) : ℂ) = ptC 40 (Meridian1.chain.wp 0) := by
    rw [Meridian1.wp_zero]; simp [ptC]
  obtain ⟨hc, -, -⟩ := Chain.loop_monodromy Meridian1.chain_steps_cert Meridian1.chain_legs_all
    (by rw [Meridian1.chain_n_eq]; norm_num) Meridian1.closed _ hb0 st0 rfl
  exact hc

theorem st0_tau : st0.τ = (0, 0) := by decide +kernel

theorem st0_S : st0.S = 2634246607 := by decide +kernel

theorem st0_ball {t : ℂ} (ht : ‖t‖ ≤ (st0.S : ℝ) / 2 ^ 40) :
    ‖t - GaussPoly.gc st0.τ / 2 ^ 40‖ ≤ (st0.S : ℝ) / 2 ^ 40 := by
  rw [st0_tau]; simpa [GaussPoly.gc] using ht

theorem st0_regular {t : ℂ} (ht : ‖t‖ ≤ (st0.S : ℝ) / 2 ^ 40) : t ∈ paperMonicFamily.regular :=
  (st0_cert.1 t (st0_ball ht)).2

/-- One root per disc on the ball. -/
theorem disc_root_unique {t : ℂ} (ht : ‖t‖ ≤ (st0.S : ℝ) / 2 ^ 40) {i : Fin 65} {x y : ℂ}
    (hx : (paperFamily t).eval x = 0) (hxi : InDisc 20 st0 i x)
    (hy : (paperFamily t).eval y = 0) (hyi : InDisc 20 st0 i y) : x = y := by
  let tb : paperMonicFamily.Base := ⟨t, st0_regular ht⟩
  have hPx : (paperMonicFamily.P tb.1).eval x = 0 := by rw [paperMonicFamily_P]; exact hx
  have hPy : (paperMonicFamily.P tb.1).eval y = 0 := by rw [paperMonicFamily_P]; exact hy
  have h := fiber_unique st0_cert (t := tb) (st0_ball ht) i.2
    (f := paperMonicFamily.mkFiber tb x hPx) (g := paperMonicFamily.mkFiber tb y hPy) hxi hyi
  simpa using congrArg MonicFamily.Fiber.root h

/-- **Product formula on the ball.** The family is the product over the 65 disc roots. -/
theorem norm_eval_eq_prod {t : ℂ} (_ht : ‖t‖ ≤ (st0.S : ℝ) / 2 ^ 40) {z : Fin 65 → ℂ}
    (hz : ∀ i, (paperFamily t).eval (z i) = 0 ∧ InDisc 20 st0 i (z i)) (c : ℂ) :
    ‖(paperFamily t).eval c‖ = ∏ j, ‖c - z j‖ := by
  have hm : (paperFamily t).Monic := by rw [← paperMonicFamily_P]; exact paperMonicFamily.monic t
  have hdeg : (paperFamily t).natDegree = Fintype.card (Fin 65) := by
    rw [← paperMonicFamily_P, paperMonicFamily.natDegree_eq]; rfl
  have hinj : Function.Injective z := fun i j h =>
    Fin.ext (label_unique st0_cert i.2 j.2 (hz i).2 (h ▸ (hz j).2))
  rw [Germs.eq_prod_of_roots hm hdeg z (fun i => (hz i).1) hinj, eval_prod, norm_prod]
  simp

/-- **Enclosure from one evaluation.** If every other disc root is at distance at least `ℓ j` from
`c`, then `‖c - z i‖ · ∏_{j ≠ i} ℓ j ≤ ‖f(c, t)‖`. -/
theorem enclose {t : ℂ} (ht : ‖t‖ ≤ (st0.S : ℝ) / 2 ^ 40) {z : Fin 65 → ℂ}
    (hz : ∀ i, (paperFamily t).eval (z i) = 0 ∧ InDisc 20 st0 i (z i)) (c : ℂ) (i : Fin 65)
    (ℓ : Fin 65 → ℝ) (hℓ : ∀ j ≠ i, 0 ≤ ℓ j ∧ ℓ j ≤ ‖c - z j‖) :
    ‖c - z i‖ * ∏ j ∈ Finset.univ.erase i, ℓ j ≤ ‖(paperFamily t).eval c‖ := by
  classical
  rw [norm_eval_eq_prod ht hz c, ← Finset.mul_prod_erase _ _ (Finset.mem_univ i)]
  exact mul_le_mul_of_nonneg_left (Finset.prod_le_prod (fun j hj => (hℓ j (Finset.ne_of_mem_erase hj)).1)
    fun j hj => (hℓ j (Finset.ne_of_mem_erase hj)).2) (norm_nonneg _)

/-- **Certified enclosures of the disc roots** from a passed `Enclose.encCheck`. -/
theorem enclose_disc_root {K J : ℕ} (hK : 20 ≤ K) {τ γ : GaussPoly.GI} {E : ℕ} {i : Fin 65}
    {L : Fin 65 → ℕ} (ht : ‖GaussPoly.gc τ / 2 ^ J‖ ≤ (st0.S : ℝ) / 2 ^ 40)
    (hshort : (Enclose.ocollapse τ (GaussPoly.oscale J 7 intCols)).length ≤ 66)
    (hcheck : Enclose.encCheck K J τ (fun j => st0.disc j) E γ i L = true) {z : Fin 65 → ℂ}
    (hz : ∀ j, (paperFamily (GaussPoly.gc τ / 2 ^ J)).eval (z j) = 0 ∧ InDisc 20 st0 j (z j)) :
    ‖GaussPoly.gc γ / 2 ^ K - z i‖ ≤ (E : ℝ) / 2 ^ K :=
  Enclose.encCheck_sound hK hshort hcheck (fun x => norm_eval_eq_prod ht hz x) (fun j => (hz j).2)

/-- A continuous root near `t₀` starting in disc `i` is the disc root near `t₀`. -/
theorem disc_root_eventually {i : Fin 65} {t₀ : ℂ} (ht₀ : ‖t₀‖ < (st0.S : ℝ) / 2 ^ 40)
    {r : ℂ → ℂ} (hr : ContinuousAt r t₀) (hrr : ∀ᶠ t in 𝓝 t₀, (paperFamily t).eval (r t) = 0)
    (hr0 : InDisc 20 st0 i (r t₀)) {w : ℂ → ℂ}
    (hw : ∀ t, ‖t‖ < (st0.S : ℝ) / 2 ^ 40 → (paperFamily t).eval (w t) = 0 ∧ InDisc 20 st0 i (w t)) :
    r =ᶠ[𝓝 t₀] w := by
  have hball : ∀ᶠ t in 𝓝 t₀, r t ∈ Metric.ball (discCentre 20 (st0.disc i)) (discRadius 20 (st0.disc i)) :=
    hr.eventually (Metric.isOpen_ball.mem_nhds hr0)
  have hin : ∀ᶠ t in 𝓝 t₀, ‖t‖ < (st0.S : ℝ) / 2 ^ 40 :=
    Filter.eventually_of_mem ((Metric.isOpen_ball (x := (0 : ℂ))).mem_nhds (by simpa using ht₀))
      fun t h => by simpa using h
  filter_upwards [hball, hin, hrr] with t h1 h2 h3
  exact disc_root_unique h2.le h3 h1 (hw t h2).1 (hw t h2).2

/-- The disc root is analytic on the ball. -/
theorem disc_root_analyticAt {i : Fin 65} {w : ℂ → ℂ}
    (hw : ∀ t, ‖t‖ < (st0.S : ℝ) / 2 ^ 40 → (paperFamily t).eval (w t) = 0 ∧ InDisc 20 st0 i (w t))
    {t₀ : ℂ} (ht₀ : ‖t₀‖ < (st0.S : ℝ) / 2 ^ 40) : AnalyticAt ℂ w t₀ := by
  let tb : paperMonicFamily.Base := ⟨t₀, st0_regular ht₀.le⟩
  have hP : (paperMonicFamily.P tb.1).eval (w t₀) = 0 := by
    rw [paperMonicFamily_P]; exact (hw t₀ ht₀).1
  obtain ⟨r, han, hr0, hrr⟩ := Germs.exists_root_branch paperMonicFamily tb
    (paperMonicFamily.mkFiber tb (w t₀) hP)
  have heq : r =ᶠ[𝓝 t₀] w := by
    refine disc_root_eventually ht₀ han.continuousAt ?_ ?_ hw
    · simpa [paperMonicFamily_P] using hrr
    · rw [hr0]; exact (hw t₀ ht₀).2
  exact han.congr heq

/-- The symmetric functions of `v 1, v σ₁, v σ₁²`. -/
def symOf {A : Type*} [CommRing A] (v : Equiv.Perm (Fin 65) → A) : Fin 3 → A :=
  ![v 1 + v σ₁ + v (σ₁ ^ 2), v 1 * v σ₁ + v 1 * v (σ₁ ^ 2) + v σ₁ * v (σ₁ ^ 2),
    v 1 * v σ₁ * v (σ₁ ^ 2)]

theorem symΘ_eq (β : fRat.rootSet fRat.SplittingField ≃ Fin 65) :
    symΘ β = symOf (Resolvent.Θ (yRoot β) N) := rfl

theorem map_symOf {A B : Type*} [CommRing A] [CommRing B] (φ : A →+* B)
    (v : Equiv.Perm (Fin 65) → A) (m : Fin 3) : φ (symOf v m) = symOf (fun π => φ (v π)) m := by
  fin_cases m <;> simp [symOf]

/-- The scaled variables. -/
noncomputable def Xs : Fin 65 → MvPolynomial (Fin 65) ℚ[X] := fun i => 13 ^ 3 * MvPolynomial.X i

/-- **Consumer of the germ link for (R3).** If the `m`-th symmetric function is `Q(t)`, then at
every parameter of the ball the same symmetric function of the certified roots (scaled by `13³`)
is `Q(t)`. -/
theorem sym_eval_of_link {β : fRat.rootSet fRat.SplittingField ≃ Fin 65} (hlink : GermLink β)
    (m : Fin 3) (Q : ℚ[X]) (hQ : symΘ β m = algebraMap ℚ[X] fRat.SplittingField Q) (t : ℂ)
    (ht : ‖t‖ < (st0.S : ℝ) / 2 ^ 40) (z : Fin 65 → ℂ)
    (hz : ∀ i, (paperFamily t).eval (z i) = 0 ∧ InDisc 20 st0 i (z i)) :
    symOf (Resolvent.Θ (fun i => 13 ^ 3 * z i) N) m = aeval t Q := by
  classical
  let φL := (MvPolynomial.aeval (fun i => (β.symm i : fRat.SplittingField)) :
    MvPolynomial (Fin 65) ℚ[X] →ₐ[ℚ[X]] fRat.SplittingField).toRingHom
  let φC := MvPolynomial.eval₂Hom (eval₂RingHom (algebraMap ℚ ℂ) t) z
  have hL : ∀ π, φL (Resolvent.Θ Xs N π) = Resolvent.Θ (yRoot β) N π := fun π => by
    have h := Resolvent.map_Θ φL Xs (yRoot β) 1 (fun i => by
      simp [φL, Xs, yRoot]) N π
    rwa [one_mul] at h
  have hC : ∀ π, φC (Resolvent.Θ Xs N π) = Resolvent.Θ (fun i => 13 ^ 3 * z i) N π := fun π => by
    have h := Resolvent.map_Θ φC Xs (fun i => 13 ^ 3 * z i) 1 (fun i => by
      simp [φC, Xs]) N π
    rwa [one_mul] at h
  have hrel := hlink (symOf (Resolvent.Θ Xs N) m - MvPolynomial.C Q) (by
    change φL (symOf (Resolvent.Θ Xs N) m - MvPolynomial.C Q) = 0
    rw [map_sub, map_symOf, show (fun π => φL (Resolvent.Θ Xs N π)) = Resolvent.Θ (yRoot β) N from
      funext hL, ← symΘ_eq, hQ]
    simp [φL]) t ht z hz
  change φC (symOf (Resolvent.Θ Xs N) m - MvPolynomial.C Q) = 0 at hrel
  rw [map_sub, map_symOf, show (fun π => φC (Resolvent.Θ Xs N π)) =
    Resolvent.Θ (fun i => 13 ^ 3 * z i) N from funext hC, sub_eq_zero] at hrel
  rw [hrel]
  simp [φC, aeval_def]

/-- **Non-vacuity of the germ link's hypotheses.** Every parameter of the ball carries a root in each
disc. -/
theorem exists_disc_roots (t : ℂ) (ht : ‖t‖ ≤ (st0.S : ℝ) / 2 ^ 40) :
    ∃ z : Fin 65 → ℂ, ∀ i, (paperFamily t).eval (z i) = 0 ∧ InDisc 20 st0 i (z i) := by
  have hb0 : ((⟨0, zero_regular⟩ : paperMonicFamily.Base) : ℂ) = ptC 40 (Meridian1.chain.wp 0) := by
    rw [Meridian1.wp_zero]; simp [ptC]
  obtain ⟨hc, -, -⟩ := Chain.loop_monodromy Meridian1.chain_steps_cert Meridian1.chain_legs_all
    (by rw [Meridian1.chain_n_eq]; norm_num) Meridian1.closed _ hb0 st0 rfl
  have hτ : st0.τ = (0, 0) := by decide +kernel
  have ht' : ‖t - GaussPoly.gc st0.τ / 2 ^ 40‖ ≤ (st0.S : ℝ) / 2 ^ 40 := by
    rw [hτ]; simpa [GaussPoly.gc] using ht
  let tb : paperMonicFamily.Base := ⟨t, (hc.1 t ht').2⟩
  have hfib : ∀ i : Fin 65, ∃ f : paperMonicFamily.Fiber tb, InDisc 20 st0 i f.root :=
    fun i => exists_fiber_in hc (t := tb) ht' i i.2
  choose f hf using hfib
  refine ⟨fun i => (f i).root, fun i => ⟨?_, hf i⟩⟩
  have h := MonicFamily.Fiber.isRoot (f i)
  rwa [paperMonicFamily_P] at h

/-- **The germ link**. Some labelling with image `G` satisfies `GermLink`.

Proof: a ring hom from the splitting field over `ℚ(t)` to germs at `t = 0`, compatible with
`ℚ(t) → ℂ(t)`, sends the root labelled `i` to the germ of the root branch starting in disc `i`
(`generic_galois_labelled`). A relation then holds for the root branches near `0`
(`GermEval.eventually_eval_eq_zero`); the branches continue analytically on
the ball, staying in their discs (`StepCertified`: one root per disc, none on the boundary), and the
identity theorem extends the relation to the whole ball. -/
theorem germ_link : ∃ β : fRat.rootSet fRat.SplittingField ≃ Fin 65,
    (Gal.galActionHom fRat fRat.SplittingField).range.map
      (Equiv.permCongrHom β).toMonoidHom = G ∧ GermLink β := by
  classical
  obtain ⟨e, β, Φ, himage, hdisc, hroot, hK⟩ := generic_galois_labelled
  refine ⟨β, himage, fun P hP t ht z hz => ?_⟩
  have hρ : (0 : ℝ) < (st0.S : ℝ) / 2 ^ 40 := by rw [st0_S]; norm_num
  -- the disc roots on the ball
  have hex : ∀ i : Fin 65, ∃ w : ℂ → ℂ, ∀ s, ‖s‖ < (st0.S : ℝ) / 2 ^ 40 →
      (paperFamily s).eval (w s) = 0 ∧ InDisc 20 st0 i (w s) := fun i => by
    refine ⟨fun s => if h : ‖s‖ ≤ (st0.S : ℝ) / 2 ^ 40 then (exists_disc_roots s h).choose i else 0,
      fun s hs => ?_⟩
    simp only [hs.le, ↓reduceDIte]
    exact (exists_disc_roots s hs.le).choose_spec i
  choose w hw using hex
  -- coefficients: `Φ` on `ℚ[t]` is the polynomial germ
  have hcoef : Φ.comp (algebraMap ℚ[X] fRat.SplittingField) =
      (algebraMap (Germs.anGerm (base : ℂ)) (Germs.Mer (base : ℂ))).comp
        ((Germs.polyGerm (base : ℂ)).comp GermEval.κ) := by
    refine Polynomial.ringHom_ext (fun q => ?_) ?_
    · exact congrArg (· q) (RingHom.ext_rat ((Φ.comp (algebraMap ℚ[X] fRat.SplittingField)).comp C)
        (((algebraMap (Germs.anGerm (base : ℂ)) (Germs.Mer (base : ℂ))).comp
          ((Germs.polyGerm (base : ℂ)).comp GermEval.κ)).comp C))
    · simp only [RingHom.coe_comp, Function.comp_apply]
      rw [IsScalarTower.algebraMap_apply ℚ[X] (RatFunc ℚ) fRat.SplittingField, RatFunc.algebraMap_X,
        hK, RelNormal.algebraMap_eq, RelNormal.φ_X, GermEval.κ, coe_mapRingHom, Polynomial.map_X,
        ← Germs.algebraMap_poly, RatFunc.algebraMap_X]
  -- the relation among germs, hence among root branches near `0`
  have hMer : MvPolynomial.eval₂ ((algebraMap (Germs.anGerm (base : ℂ)) (Germs.Mer (base : ℂ))).comp
      ((Germs.polyGerm (base : ℂ)).comp GermEval.κ))
      (fun i => Germs.rootGerm paperMonicFamily base (e.symm i)) P = 0 := by
    have h := congrArg Φ hP
    rw [map_zero, MvPolynomial.aeval_def, MvPolynomial.hom_eval₂] at h
    rw [← hcoef]
    simpa only [hroot] using h
  have hev := GermEval.eventually_eval_eq_zero paperMonicFamily base (fun i => e.symm i) P hMer
  have hrw : ∀ i, Germs.rootFun paperMonicFamily base (e.symm i) =ᶠ[𝓝 (0 : ℂ)] w i := fun i => by
    refine disc_root_eventually (by simpa using hρ) (Germs.rootFun_analyticAt _ _ _).continuousAt ?_ ?_
      (hw i)
    · simpa [paperMonicFamily_P] using Germs.rootFun_root paperMonicFamily base (e.symm i)
    · have := Germs.rootFun_base paperMonicFamily base (e.symm i)
      change InDisc 20 st0 i (Germs.rootFun paperMonicFamily base (e.symm i) (base : ℂ))
      rw [this]; exact hdisc i
  -- the relation among the disc roots, analytic on the ball
  let F : ℂ → ℂ := fun s => MvPolynomial.eval₂ (GermEval.evalAt s) (fun i => w i s) P
  have hFan : AnalyticOnNhd ℂ F (Metric.ball 0 ((st0.S : ℝ) / 2 ^ 40)) := fun s hs =>
    GermEval.analyticAt_eval₂ w (fun n => disc_root_analyticAt (hw n) (by simpa using hs)) P
  have hF0 : F =ᶠ[𝓝 (0 : ℂ)] 0 := by
    have hall : ∀ᶠ s in 𝓝 (0 : ℂ), ∀ i, Germs.rootFun paperMonicFamily base (e.symm i) s = w i s :=
      Filter.eventually_all.2 hrw
    filter_upwards [hev, hall] with s h1 h2
    show MvPolynomial.eval₂ (GermEval.evalAt s) (fun i => w i s) P = 0
    rw [← h1]
    congr 1
    funext i
    exact (h2 i).symm
  have hon := hFan.eqOn_zero_of_preconnected_of_eventuallyEq_zero
    (convex_ball (0 : ℂ) _).isPreconnected (Metric.mem_ball_self hρ) hF0
  have hFt : F t = 0 := hon (by simpa using ht)
  have hzw : z = fun i => w i t :=
    funext fun i => disc_root_unique ht.le (hz i).1 (hz i).2 (hw i t ht).1 (hw i t ht).2
  rw [hzw]
  exact hFt

/-- `N` is the certified chain group. -/
theorem N_eq_lclosure : N = lclosure Ngens0 := by
  show ⁅Subgroup.closure ({σ₁, σ₂} : Set (Equiv.Perm (Fin 65))),
    Subgroup.closure ({σ₁, σ₂} : Set (Equiv.Perm (Fin 65)))⁆ = _
  rw [Sz8.Monodromy.closure_sigma_eq, Sz8.Monodromy.commutator_eq]

/-- **The invariant through the chain**: `Θ` is a grouped sum over the transversals of `N`,
the form evaluated by the numerical certificate. -/
theorem Θ_eq_grouped {L : Type*} [CommRing L] (x : Fin 65 → L) (π : Equiv.Perm (Fin 65)) :
    Resolvent.Θ x N π =
      ∑ a : Fin 65, x (π (Ntv0.getD a 1 0)) ^ 2 *
        ∑ b : Fin 64, x (π (Ntv0.getD a 1 (Ntv1.getD b 1 1))) *
          ∑ c : Fin 7, x (π (Ntv0.getD a 1 (Ntv1.getD b 1 (Ntv2.getD c 1 3)))) := by
  classical
  rw [← NSum.sum_mono_grouped]
  unfold Resolvent.Θ Resolvent.mono
  rw [N_eq_lclosure]

/-- **Enclosures at `t = 1/2048`.** Every certified disc root lies within `2⁻³⁸⁰` of
the recorded centre. -/
theorem enclosures_point4 {z : Fin 65 → ℂ}
    (hz : ∀ j, (paperFamily (1 / 2048)).eval (z j) = 0 ∧ InDisc 20 st0 j (z j)) (i : Fin 65) :
    ‖GaussPoly.gc (EncData4.roots.getD i (0, 0)) / 2 ^ 420 - z i‖ ≤ ((2 ^ 40 : ℕ) : ℝ) / 2 ^ 420 := by
  have ht : GaussPoly.gc ((1 : ℤ), (0 : ℤ)) / 2 ^ 11 = (1 / 2048 : ℂ) := by
    simp [GaussPoly.gc]; norm_num
  refine enclose_disc_root (τ := (1, 0)) (J := 11) (by norm_num) ?_ EncData4.short
    (EncData4.checks i) (fun j => by rw [ht]; exact hz j)
  rw [ht, st0_S]; norm_num

set_option exponentiation.threshold 500 in
/-- **The value bound at one pinning point** (from the certified data of that point). For a
labelling with the germ link, if the `m`-th symmetric function is `Q(t)` then `Q` and `Z_m` differ by at
most `2⁻⁶⁹` at the point `t = τ / 2^11`. -/
theorem near_point {β : fRat.rootSet fRat.SplittingField ≃ Fin 65} (hlink : GermLink β)
    {τ : GaussPoly.GI} (ht : ‖GaussPoly.gc τ / 2 ^ 11‖ < (st0.S : ℝ) / 2 ^ 40)
    {roots : List GaussPoly.GI} {Ls : List (List ℕ)}
    (hshort : (Enclose.ocollapse τ (GaussPoly.oscale 11 7 intCols)).length ≤ 66)
    (henc : ∀ i : Fin 65, Enclose.encCheck 420 11 τ (fun j => st0.disc j) (2 ^ 40)
      (roots.getD i (0, 0)) i (fun j => (Ls.getD i []).getD j 0) = true)
    {G1 GS GSS : GaussPoly.GI}
    (h1 : ThetaEval.thetaGI (fun i => GaussPoly.gscale (13 ^ 3) (roots.getD i (0, 0))) (fun i => i) = G1)
    (hS : ThetaEval.thetaGI (fun i => GaussPoly.gscale (13 ^ 3) (roots.getD i (0, 0)))
      (fun i => σ₁ i) = GS)
    (hSS : ThetaEval.thetaGI (fun i => GaussPoly.gscale (13 ^ 3) (roots.getD i (0, 0)))
      (fun i => σ₁ (σ₁ i)) = GSS)
    (hy : ∀ i : Fin 65, GaussPoly.nsq (GaussPoly.gscale (13 ^ 3) (roots.getD i (0, 0))) ≤
      ((2 ^ 17 - 1) * 2 ^ 420 : ℤ) ^ 2)
    (hchk : ∀ m : Fin 3, PointBound.symCheck τ G1 GS GSS m (ZList.zl m) = true)
    (m : Fin 3) (Q : ℤ[X])
    (hQ : symΘ β m = algebraMap ℚ[X] fRat.SplittingField (Q.map (Int.castRingHom ℚ))) :
    ‖aeval (GaussPoly.gc τ / 2 ^ 11) Q - aeval (GaussPoly.gc τ / 2 ^ 11) (symZ m)‖ ≤ 1 / 2 ^ 69 := by
  set t : ℂ := GaussPoly.gc τ / 2 ^ 11 with htt
  set y : Fin 65 → GaussPoly.GI := fun i => GaussPoly.gscale (13 ^ 3) (roots.getD i (0, 0)) with hydef
  obtain ⟨z, hz⟩ := exists_disc_roots t ht.le
  -- enclosures of the certified roots
  have hzenc : ∀ i, ‖GaussPoly.gc (y i) / 2 ^ 420 - 13 ^ 3 * z i‖ ≤ 13 ^ 3 * (2 ^ 40 / 2 ^ 420) := by
    intro i
    have h := enclose_disc_root (K := 420) (J := 11) (by norm_num) ht.le hshort (henc i) hz
    have e : GaussPoly.gc (y i) / 2 ^ 420 - 13 ^ 3 * z i =
        13 ^ 3 * (GaussPoly.gc (roots.getD i (0, 0)) / 2 ^ 420 - z i) := by
      rw [hydef]; simp only [GaussPoly.gc_scale]; push_cast; ring
    rw [e, norm_mul, norm_pow, Complex.norm_ofNat]
    have h' : ‖GaussPoly.gc (roots.getD i (0, 0)) / 2 ^ 420 - z i‖ ≤ 2 ^ 40 / 2 ^ 420 :=
      h.trans (le_of_eq (by norm_num))
    gcongr
  -- the exact values of the invariant at the centres
  have hperm : ∀ (π : Equiv.Perm (Fin 65)) (πf : Fin 65 → Fin 65), (∀ i, π i = πf i) →
      Resolvent.Θ (fun i => GaussPoly.gc (y i)) N π = GaussPoly.gc (ThetaEval.thetaGI y πf) := by
    intro π πf hπ
    rw [Θ_eq_grouped, ThetaEval.gc_thetaGI]
    simp only [hπ]
  have hG1 := hperm 1 (fun i => i) (fun i => rfl)
  have hGS := hperm σ₁ (fun i => σ₁ i) (fun i => rfl)
  have hGSS := hperm (σ₁ ^ 2) (fun i => σ₁ (σ₁ i)) (fun i => by rw [sq, Equiv.Perm.mul_apply])
  rw [h1] at hG1; rw [hS] at hGS; rw [hSS] at hGSS
  have hb := PointBound.point_bound card_N hG1 hGS hGSS hy hzenc (hchk m)
  -- the germ link turns the symmetric function into `Q(t)`
  have hlk := sym_eval_of_link hlink m (Q.map (Int.castRingHom ℚ)) hQ t ht z hz
  have hQt : aeval t (Q.map (Int.castRingHom ℚ)) = aeval t Q := by
    rw [show Int.castRingHom ℚ = algebraMap ℤ ℚ from rfl, aeval_map_algebraMap]
  rw [hQt] at hlk
  have hZ : aeval t (symZ m) = PointBound.aevalList t (ZList.zl m) := ZList.aeval_Z t m
  rw [← hlk, hZ]
  exact hb

/-- **(R3) Certified approximate values.** For a labelling with the germ link, seven points
pin integer polynomials of degree `≤ 6`, and at each of them the value of the `m`-th symmetric
function is within the pinning bound of the claimed polynomial.

The points lie in the step-0 ball; `sym_eval_of_link` turns the value of `Q` there into the
same symmetric function of the certified roots (`exists_disc_roots`), which is enclosed by kernel
interval arithmetic from high-precision root enclosures inside the discs; `Pins` from a Lagrange
bound. -/
theorem sym_near (β : fRat.rootSet fRat.SplittingField ≃ Fin 65)
    (_hβ : (Gal.galActionHom fRat fRat.SplittingField).range.map
      (Equiv.permCongrHom β).toMonoidHom = G) (hlink : GermLink β) :
    ∃ p : Fin 7 → ℂ, ∀ m : Fin 3, ∃ δ : Fin 7 → ℝ, Resolvent.Pins 6 p δ ∧
      ∀ Q : ℤ[X], symΘ β m = algebraMap ℚ[X] fRat.SplittingField (Q.map (Int.castRingHom ℚ)) →
        ∀ k, ‖aeval (p k) Q - aeval (p k) (symZ m)‖ < δ k := by
  refine ⟨fun k => ((Pinning.r k : ℚ) : ℂ), fun m => ⟨fun _ => ((1 / 2 ^ 65 : ℚ) : ℝ), Pinning.pins,
    fun Q hQ k => ?_⟩⟩
  have hlt : (1 : ℝ) / 2 ^ 69 < ((1 / 2 ^ 65 : ℚ) : ℝ) := by norm_num
  refine lt_of_le_of_lt ?_ hlt
  fin_cases k
  · have hp : ((Pinning.r 0 : ℚ) : ℂ) = GaussPoly.gc ((-3 : ℤ), (0 : ℤ)) / 2 ^ 11 := by
      simp [Pinning.r, GaussPoly.gc]; norm_num
    show ‖aeval ((Pinning.r 0 : ℚ) : ℂ) Q - aeval ((Pinning.r 0 : ℚ) : ℂ) (symZ m)‖ ≤ _
    rw [hp]
    exact near_point hlink (by rw [st0_S]; simp [GaussPoly.gc]; norm_num) EncData0.short
      EncData0.checks ThetaData0.thetaGI_1 ThetaData0.thetaGI_S ThetaData0.thetaGI_SS
      ThetaData0.ybound ThetaData0.symChecks m Q hQ
  · have hp : ((Pinning.r 1 : ℚ) : ℂ) = GaussPoly.gc ((-2 : ℤ), (0 : ℤ)) / 2 ^ 11 := by
      simp [Pinning.r, GaussPoly.gc]; norm_num
    show ‖aeval ((Pinning.r 1 : ℚ) : ℂ) Q - aeval ((Pinning.r 1 : ℚ) : ℂ) (symZ m)‖ ≤ _
    rw [hp]
    exact near_point hlink (by rw [st0_S]; simp [GaussPoly.gc]; norm_num) EncData1.short
      EncData1.checks ThetaData1.thetaGI_1 ThetaData1.thetaGI_S ThetaData1.thetaGI_SS
      ThetaData1.ybound ThetaData1.symChecks m Q hQ
  · have hp : ((Pinning.r 2 : ℚ) : ℂ) = GaussPoly.gc ((-1 : ℤ), (0 : ℤ)) / 2 ^ 11 := by
      simp [Pinning.r, GaussPoly.gc]; norm_num
    show ‖aeval ((Pinning.r 2 : ℚ) : ℂ) Q - aeval ((Pinning.r 2 : ℚ) : ℂ) (symZ m)‖ ≤ _
    rw [hp]
    exact near_point hlink (by rw [st0_S]; simp [GaussPoly.gc]; norm_num) EncData2.short
      EncData2.checks ThetaData2.thetaGI_1 ThetaData2.thetaGI_S ThetaData2.thetaGI_SS
      ThetaData2.ybound ThetaData2.symChecks m Q hQ
  · have hp : ((Pinning.r 3 : ℚ) : ℂ) = GaussPoly.gc ((0 : ℤ), (0 : ℤ)) / 2 ^ 11 := by
      simp [Pinning.r, GaussPoly.gc]
    show ‖aeval ((Pinning.r 3 : ℚ) : ℂ) Q - aeval ((Pinning.r 3 : ℚ) : ℂ) (symZ m)‖ ≤ _
    rw [hp]
    exact near_point hlink (by rw [st0_S]; simp [GaussPoly.gc]) EncData3.short
      EncData3.checks ThetaData3.thetaGI_1 ThetaData3.thetaGI_S ThetaData3.thetaGI_SS
      ThetaData3.ybound ThetaData3.symChecks m Q hQ
  · have hp : ((Pinning.r 4 : ℚ) : ℂ) = GaussPoly.gc ((1 : ℤ), (0 : ℤ)) / 2 ^ 11 := by
      simp [Pinning.r, GaussPoly.gc]; norm_num
    show ‖aeval ((Pinning.r 4 : ℚ) : ℂ) Q - aeval ((Pinning.r 4 : ℚ) : ℂ) (symZ m)‖ ≤ _
    rw [hp]
    exact near_point hlink (by rw [st0_S]; simp [GaussPoly.gc]; norm_num) EncData4.short
      EncData4.checks ThetaData4.thetaGI_1 ThetaData4.thetaGI_S ThetaData4.thetaGI_SS
      ThetaData4.ybound ThetaData4.symChecks m Q hQ
  · have hp : ((Pinning.r 5 : ℚ) : ℂ) = GaussPoly.gc ((2 : ℤ), (0 : ℤ)) / 2 ^ 11 := by
      simp [Pinning.r, GaussPoly.gc]; norm_num
    show ‖aeval ((Pinning.r 5 : ℚ) : ℂ) Q - aeval ((Pinning.r 5 : ℚ) : ℂ) (symZ m)‖ ≤ _
    rw [hp]
    exact near_point hlink (by rw [st0_S]; simp [GaussPoly.gc]; norm_num) EncData5.short
      EncData5.checks ThetaData5.thetaGI_1 ThetaData5.thetaGI_S ThetaData5.thetaGI_SS
      ThetaData5.ybound ThetaData5.symChecks m Q hQ
  · have hp : ((Pinning.r 6 : ℚ) : ℂ) = GaussPoly.gc ((3 : ℤ), (0 : ℤ)) / 2 ^ 11 := by
      simp [Pinning.r, GaussPoly.gc]; norm_num
    show ‖aeval ((Pinning.r 6 : ℚ) : ℂ) Q - aeval ((Pinning.r 6 : ℚ) : ℂ) (symZ m)‖ ≤ _
    rw [hp]
    exact near_point hlink (by rw [st0_S]; simp [GaussPoly.gc]; norm_num) EncData6.short
      EncData6.checks ThetaData6.thetaGI_1 ThetaData6.thetaGI_S ThetaData6.thetaGI_SS
      ThetaData6.ybound ThetaData6.symChecks m Q hQ


/-- **The resolvent identity** (from (R1)–(R3)). For a labelling with image `G`, the three
values `θ_j = Θ(σ₁^j)` of the relative invariant `Θ π = Σ_{n ∈ N} y(πn 0)² y(πn 1) y(πn 3)` have
elementary symmetric functions `E1, E2, E3 ∈ ℚ[t]` (`Sz8.Galois.Resolvent`). Evidence for the data
(`galois/upstream/invariant`): power-series roots at `t = 0`, labelled by the certified discs, give integer
Taylor coefficients to `10⁻⁶¹¹` that stop in degrees `2, 4, 6`. -/
theorem resolvent_identity (β : fRat.rootSet fRat.SplittingField ≃ Fin 65)
    (hβ : (Gal.galActionHom fRat fRat.SplittingField).range.map
      (Equiv.permCongrHom β).toMonoidHom = G) (hlink : GermLink β) :
    Resolvent.Θ (yRoot β) N 1 + Resolvent.Θ (yRoot β) N σ₁ + Resolvent.Θ (yRoot β) N (σ₁ ^ 2) =
        algebraMap ℚ[X] fRat.SplittingField Resolvent.E1 ∧
      Resolvent.Θ (yRoot β) N 1 * Resolvent.Θ (yRoot β) N σ₁ +
          Resolvent.Θ (yRoot β) N 1 * Resolvent.Θ (yRoot β) N (σ₁ ^ 2) +
          Resolvent.Θ (yRoot β) N σ₁ * Resolvent.Θ (yRoot β) N (σ₁ ^ 2) =
        algebraMap ℚ[X] fRat.SplittingField Resolvent.E2 ∧
      Resolvent.Θ (yRoot β) N 1 * Resolvent.Θ (yRoot β) N σ₁ * Resolvent.Θ (yRoot β) N (σ₁ ^ 2) =
        algebraMap ℚ[X] fRat.SplittingField Resolvent.E3 := by
  obtain ⟨p, hp⟩ := sym_near β hβ hlink
  have key : ∀ m : Fin 3,
      symΘ β m = algebraMap ℚ[X] fRat.SplittingField ((symZ m).map (Int.castRingHom ℚ)) := by
    intro m
    obtain ⟨Q, hQ⟩ := sym_int β hβ m
    obtain ⟨δ, hpins, hnear⟩ := hp m
    have hdeg : Q.natDegree ≤ 6 := by
      have h := sym_natDegree_le β hβ m _ hQ
      rw [natDegree_map_eq_of_injective (RingHom.injective_int (Int.castRingHom ℚ))] at h
      have := m.isLt
      omega
    have hZ : (symZ m).natDegree ≤ 6 := by
      fin_cases m
      · exact Resolvent.Z1_natDegree.trans (by norm_num)
      · exact Resolvent.Z2_natDegree.trans (by norm_num)
      · exact Resolvent.Z3_natDegree
    rw [hQ, Resolvent.eq_of_pins hpins hdeg hZ (hnear Q hQ)]
  exact ⟨key 0, key 1, key 2⟩

/-- **The cubic input at `t = -7/5`** (from `resolvent_identity`). Every element of the
decomposition group of a prime of the integral closure over `t = -7/5` acts on the 65 roots, under
any labelling with image `G`, by an element of `N`.

Proof: `θ₀ = Θ(1)` is a root of the monic `Rs`, whose reduction at `t = -7/5` splits with distinct
rational roots (`Resolvent.Rs_fibre`), so `decomposition_le_of_split_witness` applies. For `hdetect`:
the discriminant `D ≠ 0` makes `θ₀, θ₁, θ₂` distinct, so `σ₁, σ₁² ∉ N` (`Θ_mul_mem`); every
labelled Galois element is `σ₁^j n` (`Resolvent.exists_pow_mul`, `|G| = 3|N|`) and sends `θ₀` to
`θ_j` (`Resolvent.map_Θ`), so fixing `θ₀` forces `j = 0`. -/
theorem decomposition_le_N (β : fRat.rootSet fRat.SplittingField ≃ Fin 65)
    (hβ : (Gal.galActionHom fRat fRat.SplittingField).range.map
      (Equiv.permCongrHom β).toMonoidHom = G) (hlink : GermLink β)
    (P : Ideal (integralClosure ℚ[X] fRat.SplittingField)) (hPmax : P.IsMaximal)
    (hP : P.comap (algebraMap ℚ[X] (integralClosure ℚ[X] fRat.SplittingField)) =
      RingHom.ker (evalRingHom (-7 / 5 : ℚ)))
    (g : Gal(fRat.SplittingField/RatFunc ℚ)) (hg : g ∈ MulAction.stabilizer _ P) :
    Equiv.permCongr β (Gal.galActionHom fRat _ (Gal.restrict fRat _ g)) ∈ N := by
  obtain ⟨h1, h2, h3⟩ := resolvent_identity β hβ hlink
  have := hPmax.isPrime
  set θ := Resolvent.Θ (yRoot β) N with hθ
  -- the three values are distinct
  have hinj : Function.Injective (algebraMap ℚ[X] fRat.SplittingField) := by
    rw [IsScalarTower.algebraMap_eq ℚ[X] (RatFunc ℚ) fRat.SplittingField]
    exact (algebraMap (RatFunc ℚ) fRat.SplittingField).injective.comp
      (IsFractionRing.injective ℚ[X] (RatFunc ℚ))
  have hD : algebraMap ℚ[X] fRat.SplittingField Resolvent.D ≠ 0 := by
    rw [map_ne_zero_iff _ hinj]
    intro h; exact Resolvent.disc_eval_zero_ne (by rw [h, eval_zero])
  have hdisc : ((θ 1 - θ σ₁) * (θ 1 - θ (σ₁ ^ 2)) * (θ σ₁ - θ (σ₁ ^ 2))) ^ 2 =
      algebraMap ℚ[X] fRat.SplittingField Resolvent.D := by
    rw [← Resolvent.disc_eq, h1, h2, h3]
    simp only [Resolvent.D, map_sub, map_add, map_mul, map_pow, map_ofNat]
  rw [← hdisc] at hD
  have hprod := pow_ne_zero_iff (n := 2) (by norm_num) |>.1 hD
  have h01 : θ 1 ≠ θ σ₁ := fun h => hprod (by rw [h]; ring)
  have h02 : θ 1 ≠ θ (σ₁ ^ 2) := fun h => hprod (by rw [h]; ring)
  have h12 : θ σ₁ ≠ θ (σ₁ ^ 2) := fun h => hprod (by rw [h]; ring)
  have hmemN : ∀ m, m ∈ N → θ m = θ 1 := fun m hm => by
    simpa using Resolvent.Θ_mul_mem (yRoot β) N 1 hm
  have hs1 : σ₁ ∉ N := fun h => h01 (hmemN _ h).symm
  have hs2 : σ₁ ^ 2 ∉ N := fun h => h02 (hmemN _ h).symm
  have hNG : N ≤ G := by
    rw [N, Subgroup.commutator_le]
    intro g₁ hg₁ g₂ hg₂
    rw [commutatorElement_def]
    exact G.mul_mem (G.mul_mem (G.mul_mem hg₁ hg₂) (G.inv_mem hg₁)) (G.inv_mem hg₂)
  have hcard : Nat.card G = 3 * Nat.card N := by rw [card_G, card_N]
  have hσ₁G : σ₁ ∈ G := Subgroup.subset_closure (by simp)
  -- the witness
  have hrootL : aeval (θ 1) Resolvent.Rs = 0 := by
    simp only [Resolvent.Rs, map_sub, map_add, map_mul, map_pow, aeval_X, aeval_C]
    rw [← h1, ← h2, ← h3]
    exact Resolvent.vieta_root _ _ _
  have hint : θ 1 ∈ integralClosure ℚ[X] fRat.SplittingField := by
    rw [mem_integralClosure_iff]; exact ⟨_, Resolvent.Rs_monic, hrootL⟩
  let θB : integralClosure ℚ[X] fRat.SplittingField := ⟨θ 1, hint⟩
  have hroot : aeval θB Resolvent.Rs = 0 :=
    FaithfulSMul.algebraMap_injective _ fRat.SplittingField (by
      rw [← aeval_algebraMap_apply, map_zero]; exact hrootL)
  refine decomposition_le_of_split_witness β θB Resolvent.Rs Resolvent.a Resolvent.a_injective
    hroot Resolvent.Rs_fibre (fun g' hg' => ?_) P hP g hg
  -- `hdetect`
  set ρ := Equiv.permCongr β (Gal.galActionHom fRat _ (Gal.restrict fRat _ g')) with hρ
  have hρG : ρ ∈ G := by
    rw [← hβ]; exact ⟨_, ⟨Gal.restrict fRat _ g', rfl⟩, rfl⟩
  have hfix : g' (θ 1) = θ 1 := by
    have := congrArg Subtype.val hg'
    rwa [Specialize.coe_smul] at this
  have hmap : g' (θ 1) = θ ρ := by
    have h := Resolvent.map_Θ (g' : fRat.SplittingField →+* fRat.SplittingField) (yRoot β) (yRoot β)
      ρ (fun i => ?_) N 1
    · simpa using h
    · simp only [yRoot, RingHom.coe_coe, map_mul, map_pow, map_ofNat, hρ, Equiv.permCongr_apply,
        Equiv.symm_apply_apply]
      rw [Gal.galActionHom_restrict]
  obtain ⟨j, hj, n, hn, hρeq⟩ := Resolvent.exists_pow_mul hNG hcard hσ₁G hs1 hs2 hρG
  have hθj : θ (σ₁ ^ j) = θ 1 := by
    rw [← hfix, hmap, hρeq]
    exact (Resolvent.Θ_mul_mem (yRoot β) N _ hn).symm
  interval_cases j
  · simpa [hρeq] using hn
  · exact absurd (by simpa using hθj) h01.symm
  · exact absurd hθj h02.symm

/-- The specialization `t = -7/5` embeds `Gal(h/ℚ)` into `N` (from
`specialization_le_decomposition`, `generic_galois` and `decomposition_le_N`). -/
theorem specialization_embeds : ∃ β : paperSpecialization.rootSet ℂ ≃ Fin 65,
    (Gal.galActionHom paperSpecialization ℂ).range.map
      (Equiv.permCongrHom β).toMonoidHom ≤ N := by
  obtain ⟨β, hβ, hlink⟩ := germ_link
  obtain ⟨P, hPmax, hP, β₀, hle⟩ := specialization_le_decomposition β
  refine ⟨β₀, hle.trans ?_⟩
  rintro _ ⟨g, hg, rfl⟩
  exact decomposition_le_N β hβ hlink P hPmax hP g hg

/-! ## Final assembly -/

/-- The paper's Section 6: the Galois group of `f(X, -7/5)` over `ℚ` is all of `N`. -/
theorem gal_specialization_eq_N : ∃ β : paperSpecialization.rootSet ℂ ≃ Fin 65,
    (Gal.galActionHom paperSpecialization ℂ).range.map
      (Equiv.permCongrHom β).toMonoidHom = N := by
  obtain ⟨β, hle⟩ := specialization_embeds
  refine ⟨β, eq_N_of_ninetyOne_dvd hle ?_⟩
  rw [Subgroup.card_map_of_injective (Equiv.permCongrHom β).injective, MonoidHom.range_eq_map,
    Subgroup.card_map_of_injective (Gal.galActionHom_injective _ _), Subgroup.card_top]
  exact ninetyOne_dvd_card_gal

/-- In particular `|Gal(f(X, -7/5)/ℚ)| = 29120 = |Sz(8)|`. -/
theorem card_gal_specialization : Nat.card paperSpecialization.Gal = 29120 := by
  obtain ⟨β, hβ⟩ := gal_specialization_eq_N
  have := congrArg (fun H : Subgroup (Equiv.Perm (Fin 65)) => Nat.card H) hβ
  rw [Subgroup.card_map_of_injective (Equiv.permCongrHom β).injective, MonoidHom.range_eq_map,
    Subgroup.card_map_of_injective (Gal.galActionHom_injective _ _), Subgroup.card_top] at this
  rw [this, card_N]

end Sz8.Galois
