import Mathlib.FieldTheory.RatFunc.AsPolynomial
import Mathlib.FieldTheory.Normal.Basic
import Mathlib.FieldTheory.Minpoly.Field
import Mathlib.RingTheory.Polynomial.RationalRoot
import Mathlib.RingTheory.Polynomial.IntegralNormalization
import Mathlib.RingTheory.Localization.Integral
import Mathlib.LinearAlgebra.Lagrange
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# Relative normality of `ℂ(t)` over `ℚ(t)`

`relNormal`: every rational function over `ℂ` that is algebraic over `ℚ(t)` has its
`ℚ(t)`-minimal polynomial split in `ℂ(t)`. This is the hypothesis `hrel` of
`GaloisDescent.geometric_normal_in_arithmetic_of_rel`.

Proof: clearing denominators and normalizing, a multiple `y = d z` (`d ∈ ℚ[t]`) is a root of a
monic polynomial over `ℚ[t]`, hence a polynomial `Y ∈ ℂ[t]` (rational root theorem). Evaluating at
rational points, every value `Y(j)` is an algebraic number, and Lagrange interpolation at
`0, …, deg Y` writes `Y` from those values and rational data. So `z` lies in the subfield of `ℂ(t)`
generated over `ℚ(t)` by algebraic constants and `t`, whose generators have split minimal
polynomials (`IntermediateField.splits_of_mem_adjoin`).
-/

open Polynomial
open scoped nonZeroDivisors

namespace Sz8.Galois.RelNormal

/-- `ℚ[t] → ℂ(t)`. -/
noncomputable abbrev ψ₀ : ℚ[X] →+* RatFunc ℂ :=
  (algebraMap ℂ[X] (RatFunc ℂ)).comp (mapRingHom (algebraMap ℚ ℂ))

theorem ψ₀_injective : Function.Injective ψ₀ :=
  (IsFractionRing.injective ℂ[X] (RatFunc ℂ)).comp
    (map_injective _ (algebraMap ℚ ℂ).injective)

theorem ψ₀_le : ℚ[X]⁰ ≤ (RatFunc ℂ)⁰.comap ψ₀ :=
  nonZeroDivisors_le_comap_nonZeroDivisors_of_injective _ ψ₀_injective

/-- The inclusion `ℚ(t) → ℂ(t)`. -/
noncomputable def φ : RatFunc ℚ →+* RatFunc ℂ := RatFunc.liftRingHom ψ₀ ψ₀_le

noncomputable instance : Algebra (RatFunc ℚ) (RatFunc ℂ) := φ.toAlgebra

theorem algebraMap_eq : algebraMap (RatFunc ℚ) (RatFunc ℂ) = φ := rfl

theorem φ_algebraMap (P : ℚ[X]) : φ (algebraMap ℚ[X] (RatFunc ℚ) P) = ψ₀ P :=
  RatFunc.liftRingHom_algebraMap _ _ P

theorem φ_comp_rat :
    φ.comp (algebraMap ℚ (RatFunc ℚ)) = (algebraMap ℂ (RatFunc ℂ)).comp (algebraMap ℚ ℂ) :=
  RingHom.ext_rat _ _

/-- The generators: `t` and the algebraic constants. -/
def gens : Set (RatFunc ℂ) :=
  insert RatFunc.X {x | ∃ a : ℂ, IsAlgebraic ℚ a ∧ x = algebraMap ℂ (RatFunc ℂ) a}

theorem φ_X : φ RatFunc.X = RatFunc.X := by
  rw [← RatFunc.algebraMap_X, φ_algebraMap]
  simp [RatFunc.algebraMap_X]

theorem gens_splits :
    ∀ x ∈ gens, IsIntegral (RatFunc ℚ) x ∧
      ((minpoly (RatFunc ℚ) x).map (algebraMap (RatFunc ℚ) (RatFunc ℂ))).Splits := by
  rintro x (rfl | ⟨a, ha, rfl⟩)
  · rw [← φ_X, ← algebraMap_eq]
    refine ⟨isIntegral_algebraMap, ?_⟩
    rw [minpoly.eq_X_sub_C, Polynomial.map_sub, map_X, map_C]
    exact Splits.X_sub_C _
  · set m := minpoly ℚ a with hm
    have hm0 : m ≠ 0 := minpoly.ne_zero ha.isIntegral
    have hmap : ∀ g : RatFunc ℚ →+* RatFunc ℂ, g = φ →
        (m.map (algebraMap ℚ (RatFunc ℚ))).map g =
          (m.map (algebraMap ℚ ℂ)).map (algebraMap ℂ (RatFunc ℂ)) := by
      rintro g rfl
      rw [Polynomial.map_map, Polynomial.map_map, φ_comp_rat]
    have hroot : aeval (algebraMap ℂ (RatFunc ℂ) a) (m.map (algebraMap ℚ (RatFunc ℚ))) = 0 := by
      rw [aeval_def, eval₂_eq_eval_map, hmap _ algebraMap_eq, eval_map, eval₂_at_apply,
        eval_map_algebraMap, hm, minpoly.aeval, map_zero]
    have hmon : (m.map (algebraMap ℚ (RatFunc ℚ))).Monic := (minpoly.monic ha.isIntegral).map _
    refine ⟨⟨_, hmon, hroot⟩, ?_⟩
    have hdvd := minpoly.dvd (RatFunc ℚ) _ hroot
    have hs : ((m.map (algebraMap ℚ (RatFunc ℚ))).map (algebraMap (RatFunc ℚ) (RatFunc ℂ))).Splits := by
      rw [hmap _ algebraMap_eq]
      exact (IsAlgClosed.splits _).map _
    exact hs.of_dvd (Polynomial.map_ne_zero hmon.ne_zero) (Polynomial.map_dvd _ hdvd)

/-- Polynomials whose image in `ℂ(t)` lies in the subfield generated by `gens`. -/
noncomputable def Rsub : Subring ℂ[X] :=
  (IntermediateField.adjoin (RatFunc ℚ) gens).toSubalgebra.toSubring.comap
    (algebraMap ℂ[X] (RatFunc ℂ))

theorem mem_Rsub {P : ℂ[X]} :
    P ∈ Rsub ↔ algebraMap ℂ[X] (RatFunc ℂ) P ∈ IntermediateField.adjoin (RatFunc ℚ) gens :=
  Iff.rfl

theorem C_mem_Rsub {a : ℂ} (ha : IsAlgebraic ℚ a) : C a ∈ Rsub := by
  rw [mem_Rsub, RatFunc.algebraMap_C]
  exact IntermediateField.subset_adjoin _ _ (Or.inr ⟨a, ha, rfl⟩)

theorem X_mem_Rsub : (X : ℂ[X]) ∈ Rsub := by
  rw [mem_Rsub, RatFunc.algebraMap_X]
  exact IntermediateField.subset_adjoin _ _ (Or.inl rfl)

theorem ratCast_isAlgebraic (q : ℚ) : IsAlgebraic ℚ (q : ℂ) := by
  simpa using isAlgebraic_algebraMap (R := ℚ) (A := ℂ) q

theorem map_mem_Rsub (q : ℚ[X]) : q.map (algebraMap ℚ ℂ) ∈ Rsub := by
  induction q using Polynomial.induction_on with
  | C a => rw [map_C]; exact C_mem_Rsub (by simpa using ratCast_isAlgebraic a)
  | add p q hp hq => rw [Polynomial.map_add]; exact add_mem hp hq
  | monomial n a h =>
    rw [pow_succ, ← mul_assoc, Polynomial.map_mul, map_X]
    exact mul_mem h X_mem_Rsub

/-- A complex polynomial taking algebraic values at all rational points. -/
theorem mem_Rsub_of_eval {Y : ℂ[X]} (hY : ∀ c : ℚ, IsAlgebraic ℚ (Y.eval (c : ℂ))) : Y ∈ Rsub := by
  classical
  set s := Finset.range (Y.natDegree + 1)
  set v : ℕ → ℂ := fun j => (j : ℂ)
  have hinj : Set.InjOn v s := fun i _ j _ h => by simpa [v] using h
  have hdeg : Y.degree < s.card := by
    rw [Finset.card_range]
    exact degree_le_natDegree.trans_lt (by exact_mod_cast Nat.lt_succ_self _)
  rw [Lagrange.eq_interpolate hinj hdeg, Lagrange.interpolate_apply]
  refine sum_mem fun i _ => mul_mem (C_mem_Rsub ?_) (prod_mem fun j _ => ?_)
  · simpa [v] using hY i
  · rw [Lagrange.basisDivisor]
    refine mul_mem (C_mem_Rsub ?_) (sub_mem X_mem_Rsub (C_mem_Rsub ?_))
    · simpa [v] using ratCast_isAlgebraic ((i - j : ℚ)⁻¹)
    · simpa [v] using ratCast_isAlgebraic j

theorem evalRingHom_comp (c : ℚ) :
    (evalRingHom (c : ℂ)).comp (mapRingHom (algebraMap ℚ ℂ)) =
      (algebraMap ℚ ℂ).comp (evalRingHom c) :=
  Polynomial.ringHom_ext (fun a => by simp) (by simp)

/-- **Coefficient lemma.** An element of `ℂ(t)` algebraic over `ℚ(t)` lies in the subfield
generated by `t` and the algebraic constants. -/
theorem mem_adjoin {z : RatFunc ℂ} (hz : IsAlgebraic (RatFunc ℚ) z) :
    z ∈ IntermediateField.adjoin (RatFunc ℚ) gens := by
  obtain ⟨p, hp0, hpz⟩ := hz
  set P0 := IsLocalization.integerNormalization ℚ[X]⁰ p with hP0def
  have hψ : φ.comp (algebraMap ℚ[X] (RatFunc ℚ)) = ψ₀ := RingHom.ext φ_algebraMap
  have h1 : eval₂ ψ₀ z P0 = 0 := by
    rw [← hψ]
    exact IsLocalization.integerNormalization_eval₂_eq_zero _ φ p (by rwa [aeval_def] at hpz)
  have hP0 : P0 ≠ 0 := by
    rw [hP0def, Ne, IsFractionRing.integerNormalization_eq_zero_iff]; exact hp0
  set d := P0.leadingCoeff with hd
  have hd0 : d ≠ 0 := leadingCoeff_ne_zero.2 hP0
  set Q0 := integralNormalization P0 with hQ0
  have hQmon : Q0.Monic := monic_integralNormalization hP0
  have h2 : eval₂ ψ₀ (ψ₀ d * z) Q0 = 0 :=
    integralNormalization_eval₂_eq_zero ψ₀ h1 fun x hx => ψ₀_injective (by rw [hx, map_zero])
  -- `y = d z` is a polynomial
  have h3 : aeval (ψ₀ d * z) (Q0.map (mapRingHom (algebraMap ℚ ℂ))) = 0 := by
    rw [aeval_def, eval₂_map]; exact h2
  obtain ⟨Y, hY⟩ := isInteger_of_is_root_of_monic (hQmon.map _) h3
  have h4 : eval₂ (mapRingHom (algebraMap ℚ ℂ)) Y Q0 = 0 := by
    apply IsFractionRing.injective ℂ[X] (RatFunc ℂ)
    rw [hom_eval₂, map_zero, hY]; exact h2
  -- its values at rational points are algebraic
  have h5 : ∀ c : ℚ, IsAlgebraic ℚ (Y.eval (c : ℂ)) := by
    intro c
    have h := congrArg (evalRingHom (c : ℂ)) h4
    rw [hom_eval₂, evalRingHom_comp, map_zero, ← eval₂_map] at h
    exact ⟨_, (hQmon.map _).ne_zero, by rw [aeval_def]; exact h⟩
  have hYmem := mem_Rsub_of_eval h5
  have hdmem := map_mem_Rsub d
  have hz : z = algebraMap ℂ[X] (RatFunc ℂ) Y / ψ₀ d := by
    rw [hY, mul_div_cancel_left₀ _ (by
      intro h; exact hd0 (ψ₀_injective (by rw [h, map_zero])))]
  rw [hz]
  exact div_mem hYmem hdmem

/-- **Relative normality.** -/
theorem relNormal (z : RatFunc ℂ) (hz : IsAlgebraic (RatFunc ℚ) z) :
    ((minpoly (RatFunc ℚ) z).map (algebraMap (RatFunc ℚ) (RatFunc ℂ))).Splits :=
  IntermediateField.splits_of_mem_adjoin (F := RatFunc ℚ) (K := RatFunc ℂ) (L := RatFunc ℂ)
    (splits := gens_splits) (mem_adjoin hz)

end Sz8.Galois.RelNormal
