import Sz8.Galois.SuzukiData

/-!
# `Sz(8) ≅ N`

`φ : Suzuki 𝔽₈ θ8 →* Perm (Fin 65)` is the action on the labelled ovoid (`ψ` restricted along
`Suzuki ≤ PresSub`). It is injective (`ψ_injective`, the frame argument), and its range is the
chain group `lclosure Ngens0`:

* `≤`: the range is generated by the generator images (closure induction), and every recorded image
  sifts into `N` (`siftOK`);
* `≥`: `Nc1` and `Nc2` are words in four generator images (`word1OK`, `word2OK`).
-/

namespace Sz8.Galois.Suzuki

open Matrix Sz8.Monodromy

local notation "SL" => Matrix.SpecialLinearGroup (Fin 4) F8

/-! ## From the Boolean checks to image equations -/

theorem img_of_imgAt {k : ℕ} {G : Matrix (Fin 4) (Fin 4) F8} (h : imgAt k G = true) (i : Fin 65) :
    normalize (G *ᵥ ov i) = ov (gp k i) := by
  simp only [imgAt, List.all_eq_true, List.mem_finRange, true_implies] at h
  rw [← mv_eq]; exact (veq_iff _ _).1 (h i)

theorem pres_of_img {g : SL} {f : Fin 65 → Fin 65}
    (h : ∀ i, normalize ((↑g : Matrix (Fin 4) (Fin 4) F8) *ᵥ ov i) = ov (f i)) : g ∈ PresSub :=
  fun i => ⟨f i, h i⟩

theorem coe_ψ_of_img {g : SL} {f : Fin 65 → Fin 65}
    (h : ∀ i, normalize ((↑g : Matrix (Fin 4) (Fin 4) F8) *ᵥ ov i) = ov (f i)) :
    ⇑(ψ ⟨g, pres_of_img h⟩) = f :=
  funext fun i => σ_eq (h i)

theorem checkT (a : F8) : checkTa a = true := by
  rcases a with ⟨a⟩
  fin_cases a
  exacts [checkT0, checkT1, checkT2, checkT3, checkT4, checkT5, checkT6, checkT7]

theorem img_T (a b : F8) (i : Fin 65) :
    normalize ((↑(T θ8 a b) : Matrix (Fin 4) (Fin 4) F8) *ᵥ ov i) = ov (gp (8 * a.v.val + b.v.val) i) := by
  have h := checkT a
  simp only [checkTa, List.all_eq_true] at h
  exact img_of_imgAt (h b (mem_allF8 b)) i

theorem img_M (κ : F8ˣ) (i : Fin 65) :
    normalize ((↑(M θ8 κ) : Matrix (Fin 4) (Fin 4) F8) *ᵥ ov i) =
      ov (gp (63 + (κ : F8).v.val) i) := by
  have h := checkM
  simp only [List.all_eq_true, Bool.or_eq_true, beq_iff_eq] at h
  exact img_of_imgAt ((h κ (mem_allF8 _)).resolve_left κ.ne_zero) i

theorem img_W (i : Fin 65) :
    normalize ((↑(W : SL) : Matrix (Fin 4) (Fin 4) F8) *ᵥ ov i) = ov (gp 71 i) :=
  img_of_imgAt checkW i

/-- **`Sz(8)` stabilizes the ovoid.** -/
theorem suzuki_le_presSub : Suzuki θ8 ≤ PresSub := by
  rw [Suzuki, Subgroup.closure_le]
  rintro g ((⟨⟨a, b⟩, rfl⟩ | ⟨κ, rfl⟩) | rfl)
  · exact pres_of_img (img_T a b)
  · exact pres_of_img (img_M κ)
  · exact pres_of_img img_W

/-- **The action homomorphism** `Sz(8) → S₆₅` on the labelled ovoid. -/
noncomputable def φ : Suzuki θ8 →* Equiv.Perm (Fin 65) :=
  ψ.comp (Subgroup.inclusion suzuki_le_presSub)

theorem φ_apply (g : Suzuki θ8) : φ g = ψ ⟨g, suzuki_le_presSub g.2⟩ := rfl

/-- **Injectivity** of the ovoid action. -/
theorem φ_injective : Function.Injective φ :=
  ψ_injective.comp (Subgroup.inclusion_injective _)

/-! ## Generator image equations -/

theorem coe_φ_T (a b : F8) (h : T θ8 a b ∈ Suzuki θ8) :
    ⇑(φ ⟨_, h⟩) = gp (8 * a.v.val + b.v.val) :=
  coe_ψ_of_img (img_T a b)

theorem coe_φ_M (κ : F8ˣ) (h : M θ8 κ ∈ Suzuki θ8) : ⇑(φ ⟨_, h⟩) = gp (63 + (κ : F8).v.val) :=
  coe_ψ_of_img (img_M κ)

theorem coe_φ_W (h : (W : SL) ∈ Suzuki θ8) : ⇑(φ ⟨_, h⟩) = gp 71 :=
  coe_ψ_of_img img_W

theorem T_mem (a b : F8) : T θ8 a b ∈ Suzuki θ8 :=
  Subgroup.subset_closure (Or.inl (Or.inl ⟨(a, b), rfl⟩))

theorem M_mem (κ : F8ˣ) : M θ8 κ ∈ Suzuki θ8 :=
  Subgroup.subset_closure (Or.inl (Or.inr ⟨κ, rfl⟩))

theorem W_mem : (W : SL) ∈ Suzuki θ8 :=
  Subgroup.subset_closure (Or.inr rfl)

/-! ## The range -/

theorem gp_mem {k : ℕ} (hk : k < 72) : ∃ p ∈ lclosure Ngens0, ⇑p = gp k := by
  have h := siftOK
  simp only [List.all_eq_true, List.mem_range, List.mem_finRange, true_implies, beq_iff_eq] at h
  exact ⟨_, NSum.tprod_mem _ _ _, funext fun i => (h k hk i).symm⟩

theorem mem_of_coe {q : Equiv.Perm (Fin 65)} {k : ℕ} (hk : k < 72) (h : ⇑q = gp k) :
    q ∈ lclosure Ngens0 := by
  obtain ⟨p, hp, hpk⟩ := gp_mem hk
  rwa [show q = p from Equiv.ext fun i => by rw [h, hpk]]

theorem range_le : φ.range ≤ lclosure Ngens0 := by
  rintro _ ⟨⟨g, hg⟩, rfl⟩
  induction hg using Subgroup.closure_induction with
  | mem x hx =>
    rcases hx with (⟨⟨a, b⟩, rfl⟩ | ⟨κ, rfl⟩) | rfl
    · exact mem_of_coe (by have := a.v.isLt; have := b.v.isLt; omega) (coe_φ_T a b _)
    · exact mem_of_coe (by have := (κ : F8).v.isLt; omega) (coe_φ_M κ _)
    · exact mem_of_coe (by norm_num) (coe_φ_W _)
  | one =>
    convert one_mem (lclosure Ngens0) using 1
    rw [← map_one φ]; congr 1
  | mul x y hx hy ihx ihy =>
    convert mul_mem ihx ihy using 1
    rw [← map_mul]; congr 1
  | inv x hx ihx =>
    convert inv_mem ihx using 1
    rw [← map_inv]; congr 1

/-- The four letters of the words. -/
theorem letter_mem {k : ℕ} (hk : k ∈ [9, 1, 65, 71]) : ∃ g : Suzuki θ8, ⇑(φ g) = gp k := by
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hk
  rcases hk with rfl | rfl | rfl | rfl
  · exact ⟨_, coe_φ_T ⟨1⟩ ⟨1⟩ (T_mem _ _)⟩
  · exact ⟨_, coe_φ_T ⟨0⟩ ⟨1⟩ (T_mem _ _)⟩
  · exact ⟨_, coe_φ_M (Units.mk0 ⟨2⟩ (by decide)) (M_mem _)⟩
  · exact ⟨_, coe_φ_W W_mem⟩

theorem word_mem : ∀ w : List ℕ, (∀ k ∈ w, k ∈ [9, 1, 65, 71]) → ∃ g : Suzuki θ8, ⇑(φ g) = wfun w
  | [], _ => ⟨1, by rw [map_one]; rfl⟩
  | k :: w, hw => by
    obtain ⟨g, hg⟩ := letter_mem (hw k List.mem_cons_self)
    obtain ⟨h, hh⟩ := word_mem w fun j hj => hw j (List.mem_cons_of_mem _ hj)
    refine ⟨g * h, funext fun i => ?_⟩
    rw [map_mul, Equiv.Perm.coe_mul, Function.comp_apply, hg, hh]
    rfl

theorem mem_range_of_word {q : Equiv.Perm (Fin 65)} {w : List ℕ}
    (hw : (w.all fun k => k ∈ [9, 1, 65, 71]) = true)
    (h : ((List.finRange 65).all fun i => q i == wfun w i) = true) : q ∈ φ.range := by
  simp only [List.all_eq_true, decide_eq_true_eq] at hw
  obtain ⟨g, hg⟩ := word_mem w hw
  simp only [List.all_eq_true, List.mem_finRange, true_implies, beq_iff_eq] at h
  exact ⟨g, Equiv.ext fun i => by rw [hg, h]⟩

theorem le_range : lclosure Ngens0 ≤ φ.range := by
  apply lclosure_le
  simp only [Ngens0, List.mem_cons, List.not_mem_nil, or_false]
  rintro x (rfl | rfl)
  · exact mem_range_of_word (by decide) word1OK
  · exact mem_range_of_word (by decide) word2OK

/-- **The ovoid action identifies Suzuki's matrix group with the chain group.** -/
theorem range_φ : φ.range = lclosure Ngens0 := le_antisymm range_le le_range

/-- **`Sz(8) ≅ N`** (as `lclosure Ngens0`). -/
noncomputable def suzukiEquiv : Suzuki θ8 ≃* lclosure Ngens0 :=
  (MonoidHom.ofInjective φ_injective).trans (MulEquiv.subgroupCongr range_φ)

theorem suzukiEquiv_apply (g : Suzuki θ8) : (suzukiEquiv g : Equiv.Perm (Fin 65)) = φ g := rfl

end Sz8.Galois.Suzuki
