import Mathlib.GroupTheory.GroupAction.Quotient
import Mathlib.GroupTheory.Index
import Mathlib.GroupTheory.Perm.Basic
import Mathlib.Tactic.Group
import Mathlib.Data.Set.Card
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.Algebra.Group.Commutator

/-!
# Verified stabilizer-chain order certificates

One step of a base-and-strong-generating-set (BSGS) certificate for a permutation group,
proved from Mathlib's orbit-stabilizer theorem.

Given a list `S` of permutations, a base point `b`, the orbit `O` of `b` under `⟨S⟩` as an
explicit list, a transversal `t` (with `t o • b = o`), and a list `S'` of generators of the
point stabilizer, `card_lclosure_eq` gives

  `Nat.card ⟨S⟩ = O.length * Nat.card ⟨S'⟩`.

The two nontrivial hypotheses are that `O` is closed under `S` (so it really is the orbit)
and that every Schreier generator `(t (s o))⁻¹ * s * t o` lies in `⟨S'⟩` (so `S'` really
generates the stabilizer). Both are checkable by kernel reduction on concrete data.

`tv` builds the transversal from a breadth-first tree, so that its elements lie in `⟨S⟩`
by construction rather than by certificate.
-/

namespace Sz8.Monodromy

open Equiv Subgroup MulAction
open scoped commutatorElement

variable {α : Type*} [DecidableEq α] [Fintype α]

/-- The subgroup generated by the entries of a list. -/
def lclosure (S : List (Equiv.Perm α)) : Subgroup (Equiv.Perm α) := Subgroup.closure {x | x ∈ S}

theorem mem_lclosure {S : List (Equiv.Perm α)} {x : Equiv.Perm α} (h : x ∈ S) : x ∈ lclosure S :=
  Subgroup.subset_closure h

theorem lclosure_le {S : List (Equiv.Perm α)} {H : Subgroup (Equiv.Perm α)}
    (h : ∀ x ∈ S, x ∈ H) : lclosure S ≤ H :=
  Subgroup.closure_le H |>.2 h

theorem getD_mem_of {l : List (Equiv.Perm α)} {H : Subgroup (Equiv.Perm α)}
    (h : ∀ x ∈ l, x ∈ H) (i : ℕ) : l.getD i 1 ∈ H := by
  rw [List.getD_eq_getElem?_getD]
  rcases hi : l[i]? with _ | x
  · simpa using one_mem H
  · obtain ⟨hlt, heq⟩ := List.getElem?_eq_some_iff.mp hi
    exact h x (heq ▸ List.getElem_mem hlt)

theorem getD_mem_self {l : List (Equiv.Perm α)} {i : ℕ} (h : i < l.length) : l.getD i 1 ∈ l := by
  rw [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem h]
  exact List.getElem_mem h

theorem getD_lclosure (S : List (Equiv.Perm α)) (i : ℕ) : S.getD i 1 ∈ lclosure S :=
  getD_mem_of (fun _ hx => mem_lclosure hx) i

/-- The transversal element attached to a point, by its position in the orbit list. -/
def getAt (TV : List (Equiv.Perm α)) (O : List α) (o : α) : Equiv.Perm α :=
  TV.getD (O.idxOf o) 1

/-- The product of a word in the generators. -/
def wordProd (S : List (Equiv.Perm α)) : List ℕ → Equiv.Perm α
  | [] => 1
  | i :: w => S.getD i 1 * wordProd S w

theorem wordProd_mem (S : List (Equiv.Perm α)) (w : List ℕ) : wordProd S w ∈ lclosure S := by
  induction w with
  | nil => exact one_mem _
  | cons i w ih => exact mul_mem (getD_lclosure S i) ih

/-- A transversal given as explicit data lies in the generated group, once every entry is
certified by a word in the generators. The certificate is one flat list, so the kernel walks
it in constant space per entry. -/
theorem tvWords_mem {S TV : List (Equiv.Perm α)} {cert : List (Equiv.Perm α × List ℕ)}
    (hmap : cert.map Prod.fst = TV) (hword : ∀ z ∈ cert, z.1 = wordProd S z.2) :
    ∀ i, TV.getD i 1 ∈ lclosure S := by
  refine getD_mem_of ?_
  intro x hx
  rw [← hmap] at hx
  obtain ⟨z, hz, rfl⟩ := List.mem_map.mp hx
  rw [hword z hz]
  exact wordProd_mem S z.2

/-- Every pair of a generator index and an orbit point. Indices, rather than the
permutations themselves, keep the coverage check purely numeric. -/
def idxPairs (n : ℕ) (O : List α) : List (ℕ × α) :=
  (List.range n).flatMap fun i => O.map fun o => (i, o)

theorem mem_idxPairs {n : ℕ} {O : List α} {i : ℕ} {o : α} (hi : i < n) (ho : o ∈ O) :
    (i, o) ∈ idxPairs n O := by
  simp only [idxPairs, List.mem_flatMap, List.mem_map, List.mem_range]
  exact ⟨i, hi, o, ho, rfl⟩

/-- An orbit list closed under `S` is invariant under all of `⟨S⟩`. -/
theorem mem_of_lclosure_apply {S : List (Equiv.Perm α)} {O : List α}
    (hclosed : ∀ s ∈ S, ∀ o ∈ O, s o ∈ O) :
    ∀ k ∈ lclosure S, ∀ o ∈ O, k o ∈ O := by
  intro k hk
  induction hk using Subgroup.closure_induction with
  | mem s hs => exact hclosed s hs
  | one => intro o ho; simpa using ho
  | mul x y _ _ ihx ihy => intro o ho; rw [Equiv.Perm.mul_apply]; exact ihx _ (ihy o ho)
  | inv x _ ihx =>
    intro o ho
    -- `x` maps the finite set `O` into itself injectively, hence onto itself.
    have himg : O.toFinset.image (fun y => x y) ⊆ O.toFinset := by
      intro z hz
      simp only [Finset.mem_image, List.mem_toFinset] at hz ⊢
      obtain ⟨y, hy, rfl⟩ := hz
      exact ihx y hy
    have hcard : O.toFinset.card ≤ (O.toFinset.image (fun y => x y)).card := by
      rw [Finset.card_image_of_injective _ (Equiv.injective x)]
    have heq : O.toFinset.image (fun y => x y) = O.toFinset :=
      Finset.eq_of_subset_of_card_le himg hcard
    have : o ∈ O.toFinset.image (fun y => x y) := by rw [heq]; simpa using ho
    simp only [Finset.mem_image, List.mem_toFinset] at this
    obtain ⟨y, hy, hxy⟩ := this
    have : x⁻¹ o = y := by rw [← hxy]; simp
    rwa [this]

/-- **Schreier's coset decomposition.** Every element of `⟨S⟩` is a transversal element times
an element of `⟨S'⟩`, provided every Schreier generator lies in `⟨S'⟩`. -/
theorem schreier_coset {S : List (Equiv.Perm α)} {O : List α} {t : α → Equiv.Perm α}
    {S' : List (Equiv.Perm α)}
    (hclosed : ∀ s ∈ S, ∀ o ∈ O, s o ∈ O)
    (hsch : ∀ s ∈ S, ∀ o ∈ O, (t (s o))⁻¹ * s * t o ∈ lclosure S') :
    ∀ k ∈ lclosure S, ∀ o ∈ O, (t (k o))⁻¹ * k * t o ∈ lclosure S' := by
  have hinv := mem_of_lclosure_apply hclosed
  intro k hk
  induction hk using Subgroup.closure_induction with
  | mem s hs => exact hsch s hs
  | one => intro o ho; simp
  | mul x y hx hy ihx ihy =>
    intro o ho
    have hyo : y o ∈ O := hinv y hy o ho
    have h := mul_mem (ihx (y o) hyo) (ihy o ho)
    have hxy : (x * y) o = x (y o) := Equiv.Perm.mul_apply x y o
    rw [hxy]
    convert h using 1
    group
  | inv x hx ihx =>
    intro o ho
    have h1 : x⁻¹ o ∈ O := hinv x⁻¹ (inv_mem hx) o ho
    have h := inv_mem (ihx (x⁻¹ o) h1)
    have hx1 : x (x⁻¹ o) = o := by simp
    rw [hx1] at h
    convert h using 1
    group

/-- **One step of a stabilizer chain.** -/
theorem card_lclosure_eq
    {S : List (Equiv.Perm α)} {b : α} {O : List α} {t : α → Equiv.Perm α}
    {S' : List (Equiv.Perm α)}
    (hnd : O.Nodup) (hb : b ∈ O) (htb : t b = 1)
    (hclosed : ∀ s ∈ S, ∀ o ∈ O, s o ∈ O)
    (hto : ∀ o ∈ O, t o b = o)
    (htmem : ∀ o ∈ O, t o ∈ lclosure S)
    (hsch : ∀ s ∈ S, ∀ o ∈ O, (t (s o))⁻¹ * s * t o ∈ lclosure S')
    (hS'stab : ∀ x ∈ S', x b = b)
    (hS'mem : ∀ x ∈ S', x ∈ lclosure S) :
    Nat.card (lclosure S) = O.length * Nat.card (lclosure S') := by
  classical
  set K := lclosure S with hK
  have hinv := mem_of_lclosure_apply hclosed
  have hcoset := schreier_coset hclosed hsch
  have hS'le : lclosure S' ≤ K := lclosure_le hS'mem
  -- every element of `⟨S'⟩` fixes `b`
  have hS'fix : ∀ x ∈ lclosure S', x b = b := by
    intro x hx
    have : lclosure S' ≤ MulAction.stabilizer (Equiv.Perm α) b :=
      lclosure_le (fun y hy => by simpa [MulAction.mem_stabilizer_iff] using hS'stab y hy)
    simpa [MulAction.mem_stabilizer_iff] using this hx
  -- the stabilizer of `b` in `K` is `⟨S'⟩`
  have hstab : MulAction.stabilizer K b = (lclosure S').subgroupOf K := by
    ext k
    simp only [MulAction.mem_stabilizer_iff, Subgroup.mem_subgroupOf]
    constructor
    · intro hkb
      have h := hcoset k.1 k.2 b hb
      rw [show (k : Equiv.Perm α) b = b from hkb, htb] at h
      simpa using h
    · intro hk
      exact hS'fix _ hk
  -- the orbit of `b` in `K` is `O`
  have horb : MulAction.orbit K b = {x | x ∈ O} := by
    ext o
    constructor
    · rintro ⟨k, rfl⟩
      exact hinv k.1 k.2 b hb
    · intro ho
      exact ⟨⟨t o, htmem o ho⟩, hto o ho⟩
  -- cardinalities
  have hset : {x | x ∈ O} = (O.toFinset : Set α) := by ext x; simp
  have hcardorb : Nat.card (MulAction.orbit K b) = O.length := by
    rw [horb, hset, Nat.card_coe_set_eq, Set.ncard_coe_finset, List.toFinset_card_of_nodup hnd]
  have hcardstab : Nat.card (MulAction.stabilizer K b) = Nat.card (lclosure S') := by
    rw [hstab]
    exact Nat.card_congr (Subgroup.subgroupOfEquivOfLe hS'le).toEquiv
  have hidx : (MulAction.stabilizer K b).index = Nat.card (MulAction.orbit K b) :=
    (Nat.card_congr (MulAction.orbitEquivQuotientStabilizer K b)).symm
  have := Subgroup.index_mul_card (MulAction.stabilizer K b)
  rw [hidx, hcardorb, hcardstab] at this
  exact this.symm

theorem getD_mem {β : Type*} {l : List β} {d : β} {i : ℕ} (h : i < l.length) : l.getD i d ∈ l := by
  rw [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem h]
  exact List.getElem_mem h

theorem getD_of_mem {β : Type*} {l : List β} {x : β} (d : β) (h : x ∈ l) :
    ∃ i, i < l.length ∧ l.getD i d = x := by
  obtain ⟨i, hi, hget⟩ := List.mem_iff_getElem.mp h
  exact ⟨i, hi, by rw [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem hi, hget]; rfl⟩

/-- The trivial group closes a chain. -/
theorem card_lclosure_nil : Nat.card (lclosure ([] : List (Equiv.Perm α))) = 1 := by
  have h : lclosure ([] : List (Equiv.Perm α)) = ⊥ := by
    rw [lclosure, ← Subgroup.closure_empty]
    congr 1
    ext x
    simp
  rw [h]
  simp

/-- A Schreier generator lies in the group its level generates. -/
theorem schreier_mem {S TV : List (Equiv.Perm α)} (O : List α)
    (hTV : ∀ i, TV.getD i 1 ∈ lclosure S) {s : Equiv.Perm α} (hs : s ∈ S) (o : α) :
    (getAt TV O (s o))⁻¹ * s * getAt TV O o ∈ lclosure S :=
  mul_mem (mul_mem (inv_mem (hTV _)) (mem_lclosure hs)) (hTV _)

/-- **The Schreier generators lie in `⟨S'⟩`**, read off the index certificate: each one is
the product of the two deeper transversal entries named by `cert`. -/
theorem sch_of_cert {S : List (Equiv.Perm α)} {O : List α} {TV S' W₁ W₂ : List (Equiv.Perm α)}
    {cert : List (ℕ × α × ℕ × ℕ)}
    (hW₁ : ∀ i, W₁.getD i 1 ∈ lclosure S') (hW₂ : ∀ i, W₂.getD i 1 ∈ lclosure S')
    (hcov : cert.map (fun z => (z.1, z.2.1)) = idxPairs S.length O)
    (hcheck : ∀ z ∈ cert, getAt TV O (S.getD z.1 1 z.2.1) *
        (W₁.getD z.2.2.1 1 * W₂.getD z.2.2.2 1) = S.getD z.1 1 * getAt TV O z.2.1) :
    ∀ s ∈ S, ∀ o ∈ O, (getAt TV O (s o))⁻¹ * s * getAt TV O o ∈ lclosure S' := by
  intro s hs o ho
  obtain ⟨si, hsi, rfl⟩ := getD_of_mem 1 hs
  have hmem : (si, o) ∈ cert.map (fun z => (z.1, z.2.1)) := by
    rw [hcov]; exact mem_idxPairs hsi ho
  obtain ⟨z, hz, hzeq⟩ := List.mem_map.mp hmem
  obtain ⟨h1, h2⟩ := Prod.mk.inj hzeq
  have h := hcheck z hz
  rw [h1, h2] at h
  have hrw : (getAt TV O (S.getD si 1 o))⁻¹ * S.getD si 1 * getAt TV O o
      = W₁.getD z.2.2.1 1 * W₂.getD z.2.2.2 1 := by
    rw [mul_assoc, ← h, inv_mul_cancel_left]
  rw [hrw]
  exact mul_mem (hW₁ _) (hW₂ _)

/-- **One certified chain step, from concrete data.** The transversal `TV` is explicit data
tied to the generators by the breadth-first tree `tree`; each Schreier generator is certified
by a pair of indices into two lists `W₁`, `W₂` of elements already known to lie in `⟨S'⟩` (in
the application, the transversals of the two deeper levels). Every hypothesis except the two
`W` memberships is decidable. -/
theorem card_step
    {S : List (Equiv.Perm α)} {b : α} {O : List α}
    {TV S' W₁ W₂ : List (Equiv.Perm α)} {cert : List (ℕ × α × ℕ × ℕ)}
    (hTV : ∀ i, TV.getD i 1 ∈ lclosure S)
    (hW₁ : ∀ i, W₁.getD i 1 ∈ lclosure S') (hW₂ : ∀ i, W₂.getD i 1 ∈ lclosure S')
    (h0 : TV.getD 0 1 = 1)
    (hnd : O.Nodup) (hidx : O.idxOf b = 0) (hbmem : b ∈ O)
    (hclosed : (S.all fun s => O.all fun o => decide (s o ∈ O)) = true)
    (hto : ∀ o ∈ O, getAt TV O o b = o)
    (hcov : cert.map (fun z => (z.1, z.2.1)) = idxPairs S.length O)
    (hcheck : ∀ z ∈ cert, getAt TV O (S.getD z.1 1 z.2.1) *
        (W₁.getD z.2.2.1 1 * W₂.getD z.2.2.2 1) = S.getD z.1 1 * getAt TV O z.2.1)
    (hS'stab : (S'.all fun x => decide (x b = b)) = true)
    (hS'mem : ∀ x ∈ S', x ∈ lclosure S) :
    Nat.card (lclosure S) = O.length * Nat.card (lclosure S') := by
  -- `∀ s ∈ S, …` over a list of permutations would be decided by enumerating `Perm α`;
  -- the certificates state these two checks as `List.all` computations instead.
  have hclosed' : ∀ s ∈ S, ∀ o ∈ O, s o ∈ O := fun s hs o ho => by
    simpa using (List.all_eq_true.mp ((List.all_eq_true.mp hclosed) s hs)) o ho
  have hS'stab' : ∀ x ∈ S', x b = b := fun x hx => by
    simpa using (List.all_eq_true.mp hS'stab) x hx
  refine card_lclosure_eq hnd hbmem ?_ hclosed' hto (fun o _ => hTV _)
    (sch_of_cert hW₁ hW₂ hcov hcheck) hS'stab' hS'mem
  rw [getAt, hidx, h0]

/-- **The point stabiliser is the next level of the chain.** Anything in `⟨S⟩` fixing the base
point is already in `⟨S'⟩`; the same certificate that proves the order formula proves this. -/
theorem mem_of_fix {S : List (Equiv.Perm α)} {b : α} {O : List α}
    {TV S' W₁ W₂ : List (Equiv.Perm α)} {cert : List (ℕ × α × ℕ × ℕ)}
    (hW₁ : ∀ i, W₁.getD i 1 ∈ lclosure S') (hW₂ : ∀ i, W₂.getD i 1 ∈ lclosure S')
    (h0 : TV.getD 0 1 = 1) (hidx : O.idxOf b = 0) (hbmem : b ∈ O)
    (hclosed : (S.all fun s => O.all fun o => decide (s o ∈ O)) = true)
    (hcov : cert.map (fun z => (z.1, z.2.1)) = idxPairs S.length O)
    (hcheck : ∀ z ∈ cert, getAt TV O (S.getD z.1 1 z.2.1) *
        (W₁.getD z.2.2.1 1 * W₂.getD z.2.2.2 1) = S.getD z.1 1 * getAt TV O z.2.1) :
    ∀ k ∈ lclosure S, k b = b → k ∈ lclosure S' := by
  have hclosed' : ∀ s ∈ S, ∀ o ∈ O, s o ∈ O := fun s hs o ho => by
    simpa using (List.all_eq_true.mp ((List.all_eq_true.mp hclosed) s hs)) o ho
  have htb : getAt TV O b = 1 := by rw [getAt, hidx, h0]
  intro k hk hkb
  have h := schreier_coset hclosed' (sch_of_cert hW₁ hW₂ hcov hcheck) k hk b hbmem
  rw [hkb, htb] at h
  simpa using h

/-- **One chain step, both conclusions from one certificate.** The order formula and the
identification of the point stabiliser are proved from the same data, so the kernel replays
the certificate once. -/
theorem chain_step
    {S : List (Equiv.Perm α)} {b : α} {O : List α}
    {TV S' W₁ W₂ : List (Equiv.Perm α)} {cert : List (ℕ × α × ℕ × ℕ)}
    (hTV : ∀ i, TV.getD i 1 ∈ lclosure S)
    (hW₁ : ∀ i, W₁.getD i 1 ∈ lclosure S') (hW₂ : ∀ i, W₂.getD i 1 ∈ lclosure S')
    (h0 : TV.getD 0 1 = 1)
    (hnd : O.Nodup) (hidx : O.idxOf b = 0) (hbmem : b ∈ O)
    (hclosed : (S.all fun s => O.all fun o => decide (s o ∈ O)) = true)
    (hto : ∀ o ∈ O, getAt TV O o b = o)
    (hcov : cert.map (fun z => (z.1, z.2.1)) = idxPairs S.length O)
    (hcheck : ∀ z ∈ cert, getAt TV O (S.getD z.1 1 z.2.1) *
        (W₁.getD z.2.2.1 1 * W₂.getD z.2.2.2 1) = S.getD z.1 1 * getAt TV O z.2.1)
    (hS'stab : (S'.all fun x => decide (x b = b)) = true)
    (hS'mem : ∀ x ∈ S', x ∈ lclosure S) :
    Nat.card (lclosure S) = O.length * Nat.card (lclosure S') ∧
      ∀ k ∈ lclosure S, k b = b → k ∈ lclosure S' :=
  ⟨card_step hTV hW₁ hW₂ h0 hnd hidx hbmem hclosed hto hcov hcheck hS'stab hS'mem,
    mem_of_fix hW₁ hW₂ h0 hidx hbmem hclosed hcov hcheck⟩

/-- Membership certified by a sift through a three-level chain. -/
theorem mem_of_sift₃ {H : Subgroup (Equiv.Perm α)} {x a b c : Equiv.Perm α}
    (ha : a ∈ H) (hb : b ∈ H) (hc : c ∈ H) (h : x = a * (b * c)) : x ∈ H := by
  rw [h]; exact mul_mem ha (mul_mem hb hc)

/-! ## Normalizers and commutator subgroups

For the derived subgroup we need the group generated by a list to be normalized by another
such group. Both directions of conjugation are certified on generators only. -/

/-- Conjugation stability spreads from the generators to the whole group. -/
theorem conj_mem_of_gens {S : List (Equiv.Perm α)} {s : Equiv.Perm α}
    (hs : ∀ x ∈ S, s * x * s⁻¹ ∈ lclosure S) :
    ∀ n ∈ lclosure S, s * n * s⁻¹ ∈ lclosure S := by
  intro n hn
  induction hn using Subgroup.closure_induction with
  | mem x hx => exact hs x hx
  | one => simpa using one_mem _
  | mul x y _ _ ihx ihy =>
    have h : s * (x * y) * s⁻¹ = (s * x * s⁻¹) * (s * y * s⁻¹) := by group
    rw [h]; exact mul_mem ihx ihy
  | inv x _ ihx =>
    have h : s * x⁻¹ * s⁻¹ = (s * x * s⁻¹)⁻¹ := by group
    rw [h]; exact inv_mem ihx

/-- A permutation normalizing the generated group, certified by conjugating the generators
in both directions. -/
theorem mem_normalizer_of {S : List (Equiv.Perm α)} {s : Equiv.Perm α}
    (h₁ : ∀ x ∈ S, s * x * s⁻¹ ∈ lclosure S)
    (h₂ : ∀ x ∈ S, s⁻¹ * x * s ∈ lclosure S) : s ∈ Subgroup.normalizer (lclosure S : Set (Equiv.Perm α)) := by
  rw [Subgroup.mem_normalizer_iff]
  intro h
  constructor
  · exact fun hh => conj_mem_of_gens h₁ h hh
  · intro hh
    have h2 : ∀ x ∈ S, s⁻¹ * x * s⁻¹⁻¹ ∈ lclosure S := by
      intro x hx; simpa using h₂ x hx
    have := conj_mem_of_gens h2 _ hh
    have e : s⁻¹ * (s * h * s⁻¹) * s⁻¹⁻¹ = h := by group
    rwa [e] at this

theorem conj_mem_of_normalizer {S T : List (Equiv.Perm α)}
    (hnorm : ∀ s ∈ S, s ∈ Subgroup.normalizer (lclosure T : Set (Equiv.Perm α))) :
    ∀ g ∈ lclosure S, ∀ n ∈ lclosure T, g * n * g⁻¹ ∈ lclosure T := by
  intro g hg n hn
  exact (Subgroup.mem_normalizer_iff.mp (lclosure_le hnorm hg) n).mp hn

/-- **The commutator subgroup is contained in a normalized subgroup** whenever the
commutators of the generators are. -/
theorem commutator_lclosure_le {S T : List (Equiv.Perm α)}
    (hnorm : ∀ s ∈ S, s ∈ Subgroup.normalizer (lclosure T : Set (Equiv.Perm α)))
    (hbase : ∀ a ∈ S, ∀ b ∈ S, ⁅a, b⁆ ∈ lclosure T) :
    ⁅lclosure S, lclosure S⁆ ≤ lclosure T := by
  have hconj := conj_mem_of_normalizer hnorm
  rw [Subgroup.commutator_le]
  intro g hg h hh
  induction hg, hh using Subgroup.closure_induction₂ with
  | mem a b ha hb => exact hbase a ha b hb
  | one_left x _ => simpa using one_mem _
  | one_right x _ => simpa using one_mem _
  | mul_left x y z hx hy hz ihx ihy =>
    have e : ⁅x * y, z⁆ = x * ⁅y, z⁆ * x⁻¹ * ⁅x, z⁆ := by
      simp only [commutatorElement_def]; group
    rw [e]
    exact mul_mem (hconj x hx _ ihy) ihx
  | mul_right y z x hy hz hx ihy ihz =>
    have e : ⁅x, y * z⁆ = ⁅x, y⁆ * (y * ⁅x, z⁆ * y⁻¹) := by
      simp only [commutatorElement_def]; group
    rw [e]
    exact mul_mem ihy (hconj y hy _ ihz)
  | inv_left x y hx hy ih =>
    have e : ⁅x⁻¹, y⁆ = x⁻¹ * ⁅x, y⁆⁻¹ * x⁻¹⁻¹ := by
      simp only [commutatorElement_def]; group
    rw [e]
    exact hconj x⁻¹ (inv_mem hx) _ (inv_mem ih)
  | inv_right x y hx hy ih =>
    have e : ⁅x, y⁻¹⁆ = y⁻¹ * ⁅x, y⁆⁻¹ * y⁻¹⁻¹ := by
      simp only [commutatorElement_def]; group
    rw [e]
    exact hconj y⁻¹ (inv_mem hy) _ (inv_mem ih)

end Sz8.Monodromy
