#!/usr/bin/env python3
"""Generate root-enclosure certificates at the dyadic pinning points t = (k-3)/2048.

Roots from PARI (160 digits), matched to the step-0 disc labels; exact checks replayed in Python
before writing. Output: the text of Sz8/Galois/EncData{k}.lean (written by export_galois.py)."""
import ast, json, subprocess
from fractions import Fraction
from math import isqrt

from paths import F_JSON, MERIDIAN1_JSON
K, J, E = 420, 11, 2 ** 40

def f_gp():
    """f(x, t) as a PARI expression, from data/f.json."""
    d = json.loads(F_JSON.read_text())["coefficients"]
    keys = sorted(d, key=lambda k: tuple(map(int, k.split(","))))
    return "+".join(f"({d[k]})*x^{k.split(',')[0]}*t^{k.split(',')[1]}" for k in keys)

def centers_gp():
    """The certified step-0 disc centres of certs/meridian1.json as PARI complex numbers."""
    m = json.loads(MERIDIAN1_JSON.read_text())
    return "[" + ",".join(f"{a / 2 ** 20}+{b / 2 ** 20}*I" for (a, b), r in m["steps"][0]["discs"]) + "]"

def roots_at(num):
    gp = f'''default(realprecision, 160);
F = {f_gp()};
centers = {centers_gp()};
Ft = subst(F, t, {num}/2048);
rr = polroots(Ft);
c0 = vector(65, i, my(best = 1); for(j = 2, 65, if(abs(rr[j] - centers[i]) < abs(rr[best] - centers[i]), best = j)); rr[best]);
print(vector(65, i, [round(real(c0[i]) * 2^{K}), round(imag(c0[i]) * 2^{K})]));
'''
    out = subprocess.run(["gp", "-q"], input=gp, capture_output=True, text=True, check=True).stdout
    return [tuple(r) for r in ast.literal_eval(out.strip())]

def generate(k):
    num = k - 3
    m = json.loads(MERIDIAN1_JSON.read_text())
    discs = [(tuple(c), r) for c, r in m["steps"][0]["discs"]]
    d = json.loads(F_JSON.read_text())["coefficients"]
    cols = [[0] * 66 for _ in range(8)]
    for key, v in d.items():
        i, j = map(int, key.split(","))
        x = Fraction(v) * 13 ** 182
        assert x.denominator == 1
        cols[j][i] = int(x)
    roots = roots_at(num)
    assert len(set(roots)) == 65
    tau = (num, 0)
    def gmul(a, b): return (a[0] * b[0] - a[1] * b[1], a[0] * b[1] + a[1] * b[0])
    P = [(0, 0)] * 66
    for j in range(8):
        tj = (1, 0)
        for _ in range(j): tj = gmul(tj, tau)
        s = 2 ** (J * (7 - j))
        for i in range(66):
            v = gmul((cols[j][i] * s, 0), tj)
            P[i] = (P[i][0] + v[0], P[i][1] + v[1])
    PS = [(P[i][0] * 2 ** (K * (65 - i)), P[i][1] * 2 ** (K * (65 - i))) for i in range(66)]
    def horner(ps, x):
        g = (0, 0)
        for a in reversed(ps):
            g = gmul(g, x); g = (g[0] + a[0], g[1] + a[1])
        return g
    Ls = []
    for i, g in enumerate(roots):
        G = horner(PS, g)
        Li, prod = [], 1
        for j, (C, R) in enumerate(discs):
            if j == i:
                Li.append(0); prod *= 2 ** 20; continue
            dx = g[0] - C[0] * 2 ** (K - 20); dy = g[1] - C[1] * 2 ** (K - 20)
            L = isqrt(dx * dx + dy * dy) // 2 ** (K - 20) - R - 1
            assert L > 0 and (L + R) ** 2 * 2 ** (2 * (K - 20)) <= dx * dx + dy * dy
            Li.append(L); prod *= L
        lhs = (G[0] ** 2 + G[1] ** 2) * 2 ** (2 * (K + 20 * 65))
        rhs = (E * prod) ** 2 * 13 ** 364 * 2 ** (2 * (65 * K + 7 * J))
        assert lhs <= rhs, (k, i)
        Ls.append(Li)
    src = f"-- Generated by galois/enc.py; do not edit.\nimport Sz8.Galois.Enclose\nimport Sz8.Monodromy.Meridian.Gamma1\n\n"
    src += f"namespace Sz8.Galois.EncData{k}\n\nopen Sz8.Monodromy Sz8.Monodromy.GaussPoly\n\nset_option maxRecDepth 100000\n\n"
    src += "def roots : List GI := [" + ", ".join(f"({a}, {b})" for a, b in roots) + "]\n\n"
    for i in range(65):
        src += f"def L{i} : List ℕ := [" + ", ".join(map(str, Ls[i])) + "]\n"
    src += "def Ls : List (List ℕ) := [" + ", ".join(f"L{i}" for i in range(65)) + "]\n\n"
    src += f"""theorem short : (Enclose.ocollapse ({num}, 0) (oscale {J} 7 intCols)).length ≤ 66 := by decide +kernel

"""
    for c in range(5):
        src += f"""theorem checks{c} : ∀ i : Fin 65, {13 * c} ≤ i.val → i.val < {13 * (c + 1)} →
    Enclose.encCheck {K} {J} ({num}, 0) (fun j => Meridian1.s0.disc j) {E}
      (roots.getD i (0, 0)) i (fun j => (Ls.getD i []).getD j 0) = true := by
  decide +kernel

"""
    src += f"""theorem checks : ∀ i : Fin 65, Enclose.encCheck {K} {J} ({num}, 0) (fun j => Meridian1.s0.disc j) {E}
    (roots.getD i (0, 0)) i (fun j => (Ls.getD i []).getD j 0) = true := by
  intro i
  have h := i.isLt
  rcases Nat.lt_or_ge i.val 13 with h0 | h0
  · exact checks0 i (Nat.zero_le _) h0
  rcases Nat.lt_or_ge i.val 26 with h1 | h1
  · exact checks1 i h0 h1
  rcases Nat.lt_or_ge i.val 39 with h2 | h2
  · exact checks2 i h1 h2
  rcases Nat.lt_or_ge i.val 52 with h3 | h3
  · exact checks3 i h2 h3
  · exact checks4 i h3 h

end Sz8.Galois.EncData{k}
"""
    return src
