#!/usr/bin/env python3
"""The text of Sz8/Galois/SepData.lean: Bézout certificates modulo 1000003 for (S̄, S̄') and (S̄, t² + t + 1),
from the node polynomial recorded in NodeData.lean. Needs python-flint."""
import re
import sys

import flint

sys.set_int_max_str_digits(10**8)

def generate(txt):
    """`txt`: the text of NodeData.lean."""
    p = 1000003
    sl = txt[txt.index('def Slist : List Int := ['):]
    St = [int(v) for v in re.findall(r'-?\d+', sl[len('def Slist : List Int := ['):sl.index(']')])]
    N = flint.nmod_poly
    Sb = N([v % p for v in St], p)
    Db = N([((i+1)*St[i+1]) % p for i in range(len(St)-1)], p)
    qb = N([1,1,1], p)
    assert Db == Sb.derivative()
    SB=64; WS=700
    def pack1(l):
        v=0
        for a in reversed(l): v=(v<<SB)|a
        return v
    def unpack1(n):
        out=[]; m=(1<<SB)-1
        for _ in range(WS): out.append(n&m); n>>=SB
        assert n==0
        return out
    def cert(P, Q):
        g, A, B = P.xgcd(Q)
        assert g == N([1],p)
        An=pack1([int(x) for x in A.coeffs()]); Bn=pack1([int(x) for x in B.coeffs()])
        Pn=pack1([int(x) for x in P.coeffs()]); Qn=pack1([int(x) for x in Q.coeffs()])
        lhs=unpack1(An*Pn + Bn*Qn); rhs=unpack1(1)
        Gm=[];Gp=[]
        for j in range(WS):
            d=lhs[j]-rhs[j]; assert d%p==0; gq=d//p
            Gp.append(max(gq,0)); Gm.append(max(-gq,0))
        assert An*Pn + Bn*Qn + p*pack1(Gm) == 1 + p*pack1(Gp)
        return An, Bn, pack1(Gm), pack1(Gp), A.degree(), B.degree(), max(max(Gm),max(Gp)).bit_length()
    a1,b1,gm1,gp1,da1,db1,gb1 = cert(Sb, Db)
    a2,b2,gm2,gp2,da2,db2,gb2 = cert(Sb, qb)
    def rows(n, w=16):
        RW=SB*w; out=[]
        while n: out.append(n&((1<<RW)-1)); n>>=RW
        return out or [0]
    L=["import Sz8.Galois.NodeData","","/-! Generated by `galois/sepdata.py`: Bézout certificates modulo `1000003` for",
       "`(S̄, S̄')` and `(S̄, t² + t + 1)`, packed in 64-bit slots. -/","","namespace Sz8.Galois.NodeData",""]
    for k,v in dict(A1=a1,B1=b1,Gm1=gm1,Gp1=gp1,A2=a2,B2=b2,Gm2=gm2,Gp2=gp2).items():
        L.append(f"def {k}R : List Nat := [\n  " + ",\n  ".join(f"0x{r:x}" for r in rows(v)) + "]")
        L.append(f"def {k} : Nat := join (64 * 16) {k}R")
    L.append("\nend Sz8.Galois.NodeData")
    return "\n".join(L)+"\n"
