#!/usr/bin/env python3
"""The text of Sz8/Galois/Stab13Data.lean.

For the five orbits O_k of c = σ₂σ₁ (Lean order) on Fin 65: a pair (a,b) in O_k, the 21 elements
of the pointwise stabilizer G_(a,b) as words in σ₁, σ₂, and words taking (0,1) to every ordered pair.
Words are naturals with a leading sentinel bit; bit 0 = σ₁, bit 1 = σ₂; the lowest bit acts last."""
import json
from collections import deque

from paths import MONODROMY_JSON

def generate():
    d = json.loads(MONODROMY_JSON.read_text())
    s1, s2 = tuple(d['permutations']['gamma_1']), tuple(d['permutations']['gamma_2'])
    gens = [s1, s2]
    comp = lambda g, h: tuple(g[h[i]] for i in range(65))      # (g * h) i = g (h i)
    ident = tuple(range(65))
    c = comp(s2, s1)
    seen, orbs = set(), []
    for i in range(65):
        if i in seen: continue
        o, j = [], i
        while j not in o: o.append(j); j = c[j]
        seen |= set(o); orbs.append(sorted(o))
    def enc(path):              # path: generators in application order
        w = 1
        for gi in path: w = 2 * w + gi
        return w
    # BFS over the group: element -> path (application order)
    paths = {ident: []}; q = deque([ident])
    while q:
        g = q.popleft()
        for gi, s in enumerate(gens):
            h = comp(s, g)
            if h not in paths: paths[h] = paths[g] + [gi]; q.append(h)
    assert len(paths) == 87360
    pairs = [(0, 45), (1, 3), (2, 4), (5, 10), (6, 9)]
    out = ["-- Generated by galois/stab13.py from data/monodromy.json; do not edit.",
           "import Mathlib.Data.Fin.Basic", "", "namespace Sz8.Galois.Stab13", "",
           "set_option maxRecDepth 100000", ""]
    for k, (o, (a, b)) in enumerate(zip(orbs, pairs), 1):
        assert a in o and b in o
        Oset = set(o)
        stab_ab = [g for g in paths if g[a] == a and g[b] == b]
        assert len(stab_ab) == 21
        assert [g for g in stab_ab if set(g[i] for i in o) == Oset] == [ident]
        stab_ab.sort(key=lambda g: (g != ident, len(paths[g])))
        # two points whose images separate the 21 elements
        sep = next((p, q) for p in range(65) for q in range(65)
                   if len({(g[p], g[q]) for g in stab_ab}) == 21)
        out += [f"def O{k} : List (Fin 65) := {o}", f"def a{k} : Fin 65 := {a}", f"def b{k} : Fin 65 := {b}",
                f"def p{k} : Fin 65 := {sep[0]}", f"def q{k} : Fin 65 := {sep[1]}",
                f"def H{k} : List ℕ := {[enc(paths[g]) for g in stab_ab]}", ""]
    # words for all ordered pairs, from (0,1), in lexicographic order of the target
    pw = {(0, 1): []}; q = deque([(0, 1)])
    while q:
        x, y = q.popleft()
        for gi, s in enumerate(gens):
            t = (s[x], s[y])
            if t not in pw: pw[t] = pw[(x, y)] + [gi]; q.append(t)
    assert len(pw) == 4160
    out += [f"def pairWords : List ℕ := {[enc(pw[(x, y)]) for x in range(65) for y in range(65) if x != y]}", ""]
    out.append("end Sz8.Galois.Stab13")
    return "\n".join(out) + "\n"
