#!/usr/bin/env python3
"""Exact grouped invariant values at the enclosure centres: the text of Sz8/Galois/ThetaData{k}.lean."""
import ast, json, re

from paths import INPUTS, PROJECT
CHUNK = 5

def perms():
    g = (PROJECT / "Sz8/Monodromy/GroupCerts.lean").read_text()
    packed = {m.group(1): int(m.group(2)) for m in re.finditer(r"def (N\w+) : Equiv\.Perm \(Fin 65\) := ofPacked (\d+) (\d+)", g)}
    def app(name): p = packed[name]; return [((p >> (7 * i)) % 128) % 65 for i in range(65)]
    def tv(level):
        m = re.search(r"def Ntvw%d : List \(Equiv\.Perm \(Fin 65\) × List ℕ\) := \[(.*?)\]\n" % level, g, re.S)
        names = re.findall(r"\((Nt%d_\d+), \[" % level, m.group(1))
        return [app(n) for n in names]
    return tv(0), tv(1), tv(2)

def sigma1():
    s = (PROJECT / "Sz8/Monodromy/MonodromyData.lean").read_text()
    m = re.search(r"def σ₁ : Equiv\.Perm \(Fin 65\) where\n  toFun := !\[(.*?)\]", s)
    return [int(x) for x in m.group(1).split(",")]

def num_of(k): return k - 3

def gmul(a, b): return (a[0] * b[0] - a[1] * b[1], a[0] * b[1] + a[1] * b[0])
def gadd(a, b): return (a[0] + b[0], a[1] + b[1])

def generate(k, src):
    """`src`: the text of EncData{k}.lean (its enclosure centres)."""
    roots = ast.literal_eval("[" + re.search(r"def roots : List GI := \[(.*?)\]\n", src).group(1) + "]")
    y = [(13 ** 3 * a, 13 ** 3 * b) for a, b in roots]
    T0, T1, T2 = perms()
    assert len(T0) == 65 and len(T1) == 64 and len(T2) == 7
    s1 = sigma1()
    pis = {"1": list(range(65)), "s": s1, "ss": [s1[s1[i]] for i in range(65)]}
    vals = {}
    for key, pi in pis.items():
        V = []
        for a in range(65):
            t0 = T0[a]
            ya = y[pi[t0[0]]]
            inner = (0, 0)
            for b in range(64):
                t1 = T1[b]
                cs = (0, 0)
                for c in range(7):
                    cs = gadd(cs, y[pi[t0[t1[T2[c][3]]]]])
                inner = gadd(inner, gmul(y[pi[t0[t1[1]]]], cs))
            V.append(gmul(gmul(ya, ya), inner))
        vals[key] = V
    out = f"-- Generated by galois/theta.py; do not edit.\nimport Sz8.Galois.PointBound\nimport Sz8.Galois.EncData{k}\n\n"
    out += f"namespace Sz8.Galois.ThetaData{k}\n\nopen Sz8.Monodromy Sz8.Monodromy.GaussPoly\n\nset_option maxRecDepth 100000\n\n"
    out += f"def y (i : Fin 65) : GI := gscale (13 ^ 3) (EncData{k}.roots.getD i (0, 0))\n\n"
    out += "def perm1 (i : Fin 65) : Fin 65 := i\ndef permS (i : Fin 65) : Fin 65 := σ₁ i\ndef permSS (i : Fin 65) : Fin 65 := σ₁ (σ₁ i)\n\n"
    coeffs = json.loads((INPUTS / "resolvent_coefficients.json").read_text())
    Z = [coeffs["Z1"], coeffs["Z2"], coeffs["Z3"]]
    nchunks = (65 + CHUNK - 1) // CHUNK
    out += f"theorem ybound : ∀ i : Fin 65, nsq (y i) ≤ ((2 ^ 17 - 1) * 2 ^ 420 : ℤ) ^ 2 := by\n  decide +kernel\n\n"
    for key, nm in [("1", "1"), ("s", "S"), ("ss", "SS")]:
        out += f"def V{nm} : List GI := [" + ", ".join(f"({a}, {b})" for a, b in vals[key]) + "]\n\n"
        for c in range(nchunks):
            lo, hi = CHUNK * c, min(CHUNK * (c + 1), 65)
            out += (f"theorem A{nm}_{c} : ∀ a : Fin 65, {lo} ≤ a.val → a.val < {hi} →\n"
                    f"    ThetaEval.thetaA y perm{nm} a = V{nm}.getD a (0, 0) := by\n  decide +kernel\n\n")
        out += f"def G{nm} : GI := ThetaEval.gsum fun a : Fin 65 => V{nm}.getD a (0, 0)\n\n"
        out += f"theorem thetaGI_{nm} : ThetaEval.thetaGI y perm{nm} = G{nm} := by\n"
        out += f"  unfold ThetaEval.thetaGI G{nm}\n  congr 1\n  funext a\n  have h := a.isLt\n"
        for c in range(nchunks):
            lo, hi = CHUNK * c, min(CHUNK * (c + 1), 65)
            if c < nchunks - 1:
                out += f"  rcases Nat.lt_or_ge a.val {hi} with h{c} | h{c}\n  · exact A{nm}_{c} a (by omega) h{c}\n"
            else:
                out += f"  exact A{nm}_{c} a (by omega) h\n"
        out += "\n"
    out += "def zl : Fin 3 → List ℤ := ![" + ", ".join("[" + ", ".join(map(str, z)) + "]" for z in Z) + "]\n\n"
    out += f"theorem symChecks : ∀ m : Fin 3, PointBound.symCheck ({num_of(k)}, 0) G1 GS GSS m (zl m) = true := by\n  decide +kernel\n\n"
    out += f"end Sz8.Galois.ThetaData{k}\n"
    return out
