#!/usr/bin/env python3
"""Regenerate the generated data files of `Sz8.Galois` from tracked inputs.

Artifacts (all under Sz8/Galois/): EncData0–6 (PARI/GP root enclosures), ThetaData0–6 (exact invariant
values at the enclosure centres), Resolvent (template + recorded coefficients), Stab13Data (stabilizer words),
NodeData and SepData (residue and Bézout certificates; python-flint), SuzukiData (ovoid action data).
Inputs: data/f.json, data/monodromy.json, certificate/results/discriminant.pkl (digest from
certificate/manifest.json), certs/meridian1.json, Sz8/Monodromy/GroupCerts.lean, Sz8/Monodromy/MonodromyData.lean and
galois/inputs/. Suzuki.lean's hand-written field tables and ovoid list are checked against the same computation.

--check compares every artifact byte for byte without modifying it, and checks provenance/export_galois.json.
Every Sz8.Galois file with a `Generated by` header must be produced here. Needs `gp` (PARI/GP) and python-flint;
about one minute, dominated by NodeData.
"""
import argparse
from hashlib import sha256
import json
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / 'galois'))

from export_provenance import export_outputs  # noqa: E402
import enc, nodedata, resolvent, sepdata, stab13, suzuki, theta  # noqa: E402
from paths import DISCRIMINANT_PKL, F_JSON, GENERATORS, INPUTS, MERIDIAN1_JSON, MONODROMY_JSON, REPO  # noqa: E402

GALOIS_LEAN = HERE / 'Sz8/Galois'


def sources():
    files = [F_JSON, MONODROMY_JSON, DISCRIMINANT_PKL, MERIDIAN1_JSON,
             HERE / 'Sz8/Monodromy/GroupCerts.lean', HERE / 'Sz8/Monodromy/MonodromyData.lean', HERE / 'export_galois.py']
    files += sorted(INPUTS.iterdir()) + sorted(GENERATORS.glob('*.py'))
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = json.loads((REPO / 'certificate/manifest.json').read_text())['discriminant']['uncompressed_sha256']
    if not DISCRIMINANT_PKL.exists() or sha256(DISCRIMINANT_PKL.read_bytes()).hexdigest() != expected:
        raise SystemExit(f'{DISCRIMINANT_PKL} missing or stale: run scripts/restore_discriminant.py in {REPO}')
    outputs = {}
    for k in range(7):
        outputs[GALOIS_LEAN / f'EncData{k}.lean'] = enc.generate(k)
        outputs[GALOIS_LEAN / f'ThetaData{k}.lean'] = theta.generate(k, outputs[GALOIS_LEAN / f'EncData{k}.lean'])
    outputs[GALOIS_LEAN / 'Resolvent.lean'] = resolvent.generate()
    outputs[GALOIS_LEAN / 'Stab13Data.lean'] = stab13.generate()
    outputs[GALOIS_LEAN / 'NodeData.lean'] = nodedata.generate()
    outputs[GALOIS_LEAN / 'SepData.lean'] = sepdata.generate(outputs[GALOIS_LEAN / 'NodeData.lean'])
    data = suzuki.iso_data()
    outputs[GALOIS_LEAN / 'SuzukiData.lean'] = suzuki.generate(data)
    suzuki.check_suzuki_lean((GALOIS_LEAN / 'Suzuki.lean').read_text(), data)
    generated = {p for p in GALOIS_LEAN.glob('*.lean') if 'Generated by' in ''.join(p.read_text().splitlines(True)[:6])
                 or 'generated by' in ''.join(p.read_text().splitlines(True)[:6])}
    missing = generated - set(outputs)
    if missing:
        raise SystemExit(f'Generated files without an exporter: {sorted(map(str, missing))}')
    export_outputs(outputs, check=args.check, root=HERE, exporter='export_galois', sources=sources())
    print(f"{'Checked' if args.check else 'Exported'} {len(outputs)} Sz8.Galois data files and Suzuki.lean tables")


if __name__ == '__main__':
    main()
