#!/usr/bin/env python3
"""Export the stored meridian permutations (data/monodromy.json) as Lean permutations.

Run from any directory; --check compares the generated file without modifying it.
"""
import argparse
from hashlib import sha256
from export_provenance import export_outputs
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "data/monodromy.json"
F_SOURCE = HERE.parent / "data/f.json"


def vec(xs):
    return "![" + ", ".join(map(str, xs)) + "]"


def perm(name, images, doc):
    inverse = [0] * len(images)
    for i, j in enumerate(images):
        inverse[j] = i
    assert sorted(images) == list(range(65))
    return (f"/-- {doc} -/\ndef {name} : Equiv.Perm (Fin 65) where\n"
            f"  toFun := {vec(images)}\n  invFun := {vec(inverse)}\n"
            f"  left_inv := by decide +kernel\n  right_inv := by decide +kernel\n\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = SOURCE.read_bytes()
    data = json.loads(raw)
    assert data["indexing"] == "zero-based image lists"
    assert data["source_f_sha256"] == sha256(F_SOURCE.read_bytes()).hexdigest()
    s1, s2 = data["permutations"]["gamma_1"], data["permutations"]["gamma_2"]
    out = ("-- Generated by export_monodromy.py; do not edit.\n"
           f"-- data/monodromy.json SHA-256: {sha256(raw).hexdigest()}\n"
           "import Mathlib.GroupTheory.Perm.Basic\nimport Mathlib.Data.Fintype.Perm\n"
           "import Mathlib.Data.Fin.VecNotation\n\n"
           "/-!\nThe stored meridian permutations of the 65 roots over `t = 0`, as recorded by the\n"
           "paper's certificate (`data/monodromy.json`, zero-based image lists: `σ i` is the\n"
           "image of root `i`). Lean composes right to left, so the paper's left-to-right\n"
           "product `σ₁σ₂` is `σ₂ * σ₁` here.\n\n"
           "These are data. That they are the monodromy of the paper's family is not yet\n"
           "proved; see `Sz8.Galois`.\n-/\n\nnamespace Sz8.Monodromy\n\nset_option maxRecDepth 100000\n\n")
    out += perm("σ₁", s1, "Monodromy around `ζ₃`, as recorded.")
    out += perm("σ₂", s2, "Monodromy around `ζ₃²`, as recorded.")
    out += """/-- Order 3 with five fixed points: cycle type `3^20 1^5`. -/
theorem σ₁_pow_three : σ₁ ^ 3 = 1 := by decide +kernel
theorem σ₁_fixed : (Finset.univ.filter fun i => σ₁ i = i).card = 5 := by decide +kernel

theorem σ₂_pow_three : σ₂ ^ 3 = 1 := by decide +kernel
theorem σ₂_fixed : (Finset.univ.filter fun i => σ₂ i = i).card = 5 := by decide +kernel

/-- The paper's `σ₁σ₂` (left to right) has order 13 and no fixed points: type `13^5`. -/
theorem σ₁σ₂_pow_thirteen : (σ₂ * σ₁) ^ 13 = 1 := by decide +kernel
theorem σ₁σ₂_fixed : (Finset.univ.filter fun i => (σ₂ * σ₁) i = i).card = 0 := by decide +kernel

end Sz8.Monodromy
"""
    path = HERE / "Sz8/Monodromy/MonodromyData.lean"
    export_outputs({path: out}, check=args.check, root=HERE, exporter='export_monodromy',
                   sources=[F_SOURCE, SOURCE])
    print(f"{'Checked' if args.check else 'Exported'} two meridian permutations of degree 65")


if __name__ == "__main__":
    main()
