#!/usr/bin/env python3
"""Export an exact, conservative continuation certificate around X=20, t=0.

No numerical roots are trusted: every coefficient shift and the rational bound
are replayed in Lean. --check only checks deterministic regeneration.
"""
import argparse
from fractions import Fraction as Q
from hashlib import sha256
from export_provenance import export_outputs
import json
from math import comb
from pathlib import Path

HERE = Path(__file__).resolve().parent


def rat(a):
    return f"({a.numerator} / {a.denominator})"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    raw = (HERE.parent / "data/f.json").read_bytes()
    source = json.loads(raw)
    original = [[Q(0) for _ in range(66)] for _ in range(8)]
    for ij, a in source["coefficients"].items():
        i, j = map(int, ij.split(","))
        original[j][i] = Q(a)
    shifted = [[sum(original[j][i] * comb(i, k) * 20 ** (i-k)
                    for i in range(k, 66)) for k in range(66)] for j in range(8)]
    scale = shifted[0][1]
    assert scale != 0
    errors = [[a / scale for a in cs] for cs in shifted]
    errors[0][1] -= 1
    R, H = Q(1, 10), Q(1, 1000000)
    bound = sum(abs(a) * R**i * H**j for j, cs in enumerate(errors) for i, a in enumerate(cs))
    assert bound < R
    header = ("-- Generated by export_step.py; do not edit.\n"
              f"-- data/f.json SHA-256: {sha256(raw).hexdigest()}\n")
    out = header + "import Sz8.Monodromy.Bounds\n\nnamespace Sz8.Monodromy\n"
    out += "set_option maxRecDepth 100000\nset_option maxHeartbeats 20000000\n\n"
    out += f"def stepScale : ℚ := {rat(scale)}\n\n"
    for j in range(8):
        for name, cols in [("original", original), ("error", errors)]:
            cs = cols[j][:]
            while cs and cs[-1] == 0:
                cs.pop()
            out += f"def {name}Column{j} : List ℚ := [\n"
            out += ",\n".join("  " + rat(a) for a in cs) + "]\n\n"
    out += "def originalColumns : List (List ℚ) := [" + ", ".join(f"originalColumn{j}" for j in range(8)) + "]\n"
    out += "def errorColumns : List (List ℚ) := [" + ", ".join(f"errorColumn{j}" for j in range(8)) + "]\n\n"
    out += "end Sz8.Monodromy\n"
    # Separate modules allow independent checking and keep the large certificates isolated.
    outputs = {HERE / "Sz8/Monodromy/StepData.lean": out}
    for j in range(8):
        cert = header + "import Sz8.Monodromy.StepData\n\nnamespace Sz8.Monodromy\n"
        cert += "set_option maxRecDepth 100000\nset_option maxHeartbeats 20000000\n\n"
        cert += f"""theorem shift_certificate_{j} :
    (denseHorner originalColumn{j}).compose
        (Hex.DensePoly.C 20 + Hex.DensePoly.monomial 1 1) =
      Hex.DensePoly.C stepScale * (denseHorner errorColumn{j} +
        if {str(j == 0).lower()} then Hex.DensePoly.monomial 1 1 else 0) := by
  decide +kernel

end Sz8.Monodromy
"""
        outputs[HERE / f"Sz8/Monodromy/Shift{j}.lean"] = cert
    report = {"source_sha256": sha256(raw).hexdigest(), "center_X": "20", "center_t": "0",
        "radius_X": str(R), "radius_t": str(H), "normalization": str(scale),
        "error_bound_exact": str(bound), "error_bound_approx": float(bound),
        "strict_gap_exact": str(R - bound),
        "statement": "For every complex t with |t| <= 1/1000000, f(X,t) has exactly one root, counted with multiplicity, in |X-20| < 1/10."}
    outputs[HERE / "step-report.json"] = json.dumps(report, indent=2) + "\n"
    export_outputs(outputs, check=args.check, root=HERE, exporter='export_step',
                   sources=[HERE.parent / 'data/f.json'])
    print(f"{'Checked' if args.check else 'Exported'} step: error bound {float(bound):.12g} < radius {float(R)}")


if __name__ == "__main__":
    main()
