"""Keep historical Lean headers while checking current exports and source provenance.

Only the digest in the second-line, generated SHA-256 comment may differ.
Every other byte must match deterministic regeneration. Separate manifests bind
the current source bytes to the exact retained artifacts, including their headers.
"""
from hashlib import sha256
import json
import os
from pathlib import Path
import re


HEADER = re.compile(r"(-- (data/(?:f|monodromy)\.json) SHA-256: )([0-9a-f]{64})(\n)")


def retain_header(actual, generated):
    """Return the expected artifact, retaining an existing historical digest only."""
    old = actual.splitlines(keepends=True)
    new = generated.splitlines(keepends=True)
    if len(old) < 2 or len(new) < 2:
        return generated
    a, b = HEADER.fullmatch(old[1]), HEADER.fullmatch(new[1])
    if (a and b and a.group(2) == b.group(2)
            and old[0] == new[0] and old[2:] == new[2:]
            and new[0].startswith('-- Generated by ')):
        new[1] = old[1]
    return ''.join(new)


def recorded_manifest(root, exporter):
    """The committed provenance manifest of an exporter, or None."""
    path = Path(root) / 'provenance' / f'{exporter}.json'
    return json.loads(path.read_text()) if path.exists() else None


def restore_recorded_header(generated, entry):
    """A stand-in for a missing artifact: the generated text with the recorded historical digest."""
    lines = generated.splitlines(keepends=True)
    if not entry or 'generation_source_sha256' not in entry or len(lines) < 2:
        return ''
    match = HEADER.fullmatch(lines[1])
    if not match or match.group(2) != entry.get('generation_source'):
        return ''
    lines[1] = match.group(1) + entry['generation_source_sha256'] + match.group(4)
    return ''.join(lines)


def export_outputs(outputs, *, check, root, exporter, sources, pinned=None):
    """Check/write artifacts without touching files whose generated body is unchanged.

The manifest is checked strictly, including the full artifact hash. This means
even a change to a historical header requires an explicit manifest refresh.
JSON reports remain byte-for-byte checks, with current source hashes.

A missing Lean artifact takes its historical digest from the committed manifest, so a checkout
without generated files regenerates the recorded bytes. With `pinned` (default: environment
variable SZ8_PINNED_PROVENANCE=1), writing is refused unless the resulting manifest equals the
committed one; nothing is written in that case.
"""
    root = Path(root)
    if pinned is None:
        pinned = os.environ.get('SZ8_PINNED_PROVENANCE') == '1'
    recorded = recorded_manifest(root, exporter)
    recorded_artifacts = (recorded or {}).get('artifacts', {})
    artifacts = {}
    writes = []
    for path, generated in outputs.items():
        path = Path(path)
        actual = path.read_bytes().decode('utf-8') if path.exists() else ''
        basis = actual
        if not path.exists() and path.suffix == '.lean':
            basis = restore_recorded_header(generated, recorded_artifacts.get(str(path.relative_to(root))))
        expected = retain_header(basis, generated) if path.suffix == '.lean' else generated
        if check:
            if actual != expected:
                raise ValueError(f'Stale generated file: {path}')
        elif actual != expected or not path.exists():
            writes.append((path, expected))
        entry = {'sha256': sha256(expected.encode('utf-8')).hexdigest()}
        lines = expected.splitlines(keepends=True)
        header = HEADER.fullmatch(lines[1]) if path.suffix == '.lean' and len(lines) > 1 else None
        if header:
            entry['generation_source'] = header.group(2)
            entry['generation_source_sha256'] = header.group(3)
        artifacts[str(path.relative_to(root))] = entry
    manifest = {
        'schema': 1,
        'exporter': exporter,
        'comparison': 'Exact generated bytes except the historical SHA-256 digest in the second-line Lean header.',
        'current_sources': {
            str(Path(source).relative_to(root.parent)): sha256(Path(source).read_bytes()).hexdigest()
            for source in sources
        },
        'artifacts': artifacts,
    }
    path = root / 'provenance' / f'{exporter}.json'
    expected = json.dumps(manifest, indent=2, sort_keys=True) + '\n'
    if check:
        if not path.exists() or path.read_bytes() != expected.encode('utf-8'):
            raise ValueError(f'Stale provenance manifest: {path}; rerun {exporter}.py')
    else:
        if pinned and (not path.exists() or path.read_bytes() != expected.encode('utf-8')):
            raise ValueError(f'Regeneration would change the committed provenance manifest {path}')
        for artifact, text in writes:
            artifact.parent.mkdir(parents=True, exist_ok=True)
            artifact.write_bytes(text.encode('utf-8'))
        path.parent.mkdir(exist_ok=True)
        if not path.exists() or path.read_bytes() != expected.encode('utf-8'):
            path.write_bytes(expected.encode('utf-8'))
