#!/usr/bin/env python3
"""Deterministically export exact paper inputs; FLINT proposes factors and certificates, Lean checks them.

Run from any directory. --check compares generated files without modifying them.
"""
import argparse
from fractions import Fraction as Q
from hashlib import sha256
from export_provenance import export_outputs
import json
from pathlib import Path

import flint

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "data/f.json"


def array(xs):
    return "#[" + ", ".join(map(str, xs)) + "]"


def lst(xs):
    return "[" + ", ".join(map(str, xs)) + "]"


def rabin_cert(p, cs):
    """Rabin certificate for the monic factor with ascending coefficients cs.

    FLINT proposes X^p mod P, the powers (X^p)^i mod P and all quotients; Lean's
    kernel only multiplies and compares. Linear factors carry no certificate.
    """
    n = len(cs) - 1
    assert n >= 1 and cs[-1] == 1
    if n == 1:
        return f"{{ low := {lst(cs[:-1])}, qB := [], B := [], Ms := [], qs := [] }}"
    coeffs = lambda poly: [int(c) for c in poly.coeffs()]
    P = flint.nmod_poly(cs, p)
    qB, B = divmod(flint.nmod_poly([0] * p + [1], p), P)
    Ms, qs, M = [], [], flint.nmod_poly([1], p)
    for _ in range(1, n):
        q, M = divmod(M * B, P)
        Ms.append(M)
        qs.append(q)
    # Self-check of the same Frobenius iteration the kernel replays.
    rows, r = [flint.nmod_poly([1], p)] + Ms, flint.nmod_poly([0, 1], p)
    for _ in range(n):
        rc = coeffs(r)
        r = sum((rows[i] * rc[i] for i in range(len(rc))), flint.nmod_poly([], p))
    assert r == flint.nmod_poly([0, 1], p) and all(int(P(a)) for a in range(p))
    return (f"{{ low := {lst(cs[:-1])}\n    qB := {lst(coeffs(qB))}\n    B := {lst(coeffs(B))}\n"
            f"    Ms := [{', '.join(lst(coeffs(m)) for m in Ms)}]\n"
            f"    qs := [{', '.join(lst(coeffs(q)) for q in qs)}] }}")


SPEC_DEN = 13 ** 182          # common denominator of the input coefficients
SPEC_SCALE = 5 ** 7 * SPEC_DEN  # leading coefficient of the integral model


def term_int(n, d, j):
    """Mirror of Lean's termInt: SPEC_SCALE * (n/d) * (-7/5)^j as an integer."""
    return n * (SPEC_DEN // d) * (-7) ** j * 5 ** (7 - j)


def model_factors(p, int_terms):
    """Reduce the monic model integralNormalization(SPEC_SCALE * h) mod p as Lean does,
    and return its monic irreducible factors (ascending coefficients, with repetition)."""
    g = [0] * 66
    for i, j, n, d in int_terms:
        g[i] = (g[i] + term_int(n, d, j) % p) % p
    c = SPEC_SCALE % p
    hbar = [g[i] * pow(c, 64 - i) % p for i in range(65)] + [1]
    poly = flint.nmod_poly(hbar, p)
    _, pairs = poly.factor()
    factors = sorted((list(map(int, q.coeffs())) for q, e in pairs for _ in range(e)),
                     key=lambda cs: (len(cs), cs))
    prod = flint.nmod_poly([1], p)
    for cs in factors:
        prod *= flint.nmod_poly(cs, p)
    assert prod == poly
    return factors


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = SOURCE.read_bytes()
    data = json.loads(raw)
    terms = sorted((int(k.split(",")[0]), int(k.split(",")[1]), Q(v))
                   for k, v in data["coefficients"].items() if Q(v))
    h = [Q(0)] * 66
    for i, j, a in terms:
        h[i] += a * Q(-7, 5) ** j
    assert h[65] == 1
    source_hash = sha256(raw).hexdigest()
    header = ("-- Generated by export_inputs.py; do not edit.\n"
              f"-- data/f.json SHA-256: {source_hash}\n")
    inputs = header + "import HexBerlekampMathlib\n\nnamespace Sz8.Monodromy\nset_option maxHeartbeats 20000000\nset_option maxRecDepth 100000\n\ninstance : Hex.ZMod64.Bounds 11 := ⟨by decide, by decide⟩\ninstance : Hex.ZMod64.Bounds 31 := ⟨by decide, by decide⟩\ninstance : Fact (Nat.Prime 11) := ⟨by decide⟩\ninstance : Fact (Nat.Prime 31) := ⟨by decide⟩\n\n"
    inputs += "def inputTerms : List (Nat × Nat × Int × Nat) := [\n"
    inputs += ",\n".join(f"  ({i}, {j}, {a.numerator}, {a.denominator})"
                         for i, j, a in terms)
    inputs += "]\n\n"
    inputs += """/-- Specialize the exact rational coefficient encoding at -7/5 modulo p.
The separate denominator checks exclude undefined reductions. -/
noncomputable def paperFp (p : Nat) [Hex.ZMod64.Bounds p] : Hex.FpPoly p :=
  inputTerms.foldr (fun a acc =>
    Hex.DensePoly.C ((a.2.2.1 : Hex.ZMod64 p) / (a.2.2.2 : Hex.ZMod64 p) *
      ((-7 : Hex.ZMod64 p) / 5) ^ a.2.1) * Hex.DensePoly.monomial a.1 1 + acc) 0

def denominatorsOK (p : Nat) : Bool :=
  p % 5 != 0 && inputTerms.all (fun a => a.2.2.2 % p != 0)

"""
    report = {"source": "../data/f.json", "sha256": source_hash,
              "specialization": "-7/5", "nonzero_terms": len(terms), "primes": {}}
    certs = header + "import Sz8.Monodromy.ListPoly\n\nnamespace Sz8.Monodromy\nopen ListPoly\n\n"
    int_terms = [(i, j, a.numerator, a.denominator) for i, j, a in terms]
    assert all(SPEC_DEN % d == 0 and j <= 7 and i <= 65 for i, j, _, d in int_terms)
    spec = header + "import Sz8.Monodromy.ListPoly\n\nnamespace Sz8.Monodromy\nopen ListPoly\n\n"
    modular = header + "import Sz8.Monodromy.Inputs\nimport Sz8.Monodromy.IrredCerts\n\nopen Polynomial HexBerlekampMathlib\n\n"
    modular += "namespace Sz8.Monodromy\nset_option maxRecDepth 100000\nset_option maxHeartbeats 20000000\n\n"
    for p, wanted in [(11, [1, 1] + [7] * 9), (31, [13] * 5)]:
        coeffs = [a.numerator % p * pow(a.denominator % p, -1, p) % p for a in h]
        f = flint.nmod_poly(coeffs, p)
        scalar, factor_pairs = f.factor()
        fs = sorted((list(map(int, g.coeffs())) for g, e in factor_pairs for _ in range(e)),
                    key=lambda cs: (len(cs), cs))
        assert sorted(len(cs) - 1 for cs in fs) == wanted
        assert int(scalar) == 1 and f.gcd(f.derivative()).degree() == 0
        report["primes"][str(p)] = {"coefficients_ascending": coeffs,
            "factors_ascending": fs, "factor_degrees": wanted, "squarefree": True}
        degree_primes = sorted({len(cs) - 1 for cs in fs} - {1})
        certs += f"/-- Rabin certificates proposed by FLINT for the factors modulo {p}. -/\n"
        certs += f"def certs{p} : List RabinCert := [\n"
        certs += ",\n".join("  " + rabin_cert(p, cs) for cs in fs) + "]\n\n"
        inputs += f"def reduced{p} : Hex.FpPoly {p} := Hex.DensePoly.ofCoeffs {array(coeffs)}\n\n"
        inputs += f"def factors{p} : List (Hex.FpPoly {p}) := [\n"
        inputs += ",\n".join(f"  Hex.DensePoly.ofCoeffs {array(cs)}" for cs in fs) + "]\n\n"
        model = model_factors(p, int_terms)
        # The monic model is a unit rescaling X -> cX of h mod p, so the pattern must agree.
        assert sorted(len(cs) - 1 for cs in model) == sorted(wanted), p
        report["primes"][str(p)]["model_factors_ascending"] = model
        spec += (f"/-- Certified irreducible factorization of the monic integral model "
                 f"modulo {p}. -/\n"
                 f"def hbarCerts{p} : List RabinCert := [\n"
                 + ",\n".join("  " + rabin_cert(p, cs) for cs in model) + "]\n\n")
        gcd, ba, bb = f.xgcd(f.derivative())
        assert gcd == 1
        for name, poly in [("bezoutA", ba), ("bezoutB", bb)]:
            inputs += f"def {name}{p} : Hex.FpPoly {p} := Hex.DensePoly.ofCoeffs {array(map(int, poly.coeffs()))}\n\n"
        modular += f"""theorem denominators_ok_{p} : denominatorsOK {p} = true := by decide +kernel

theorem reduction_{p} : paperFp {p} = reduced{p} := by decide +kernel

theorem product_{p} : factors{p}.prod = reduced{p} := by decide +kernel

theorem degrees_{p} : factors{p}.map Hex.DensePoly.natDegree = {str(wanted)} := by
  decide +kernel

theorem bezout_{p} :
    bezoutA{p} * reduced{p} + bezoutB{p} * Hex.DensePoly.derivative reduced{p} = 1 := by
  decide +kernel

theorem squarefree_{p} :
    IsCoprime (toMathlibPolynomial reduced{p}) (toMathlibPolynomial reduced{p}).derivative := by
  refine ⟨toMathlibPolynomial bezoutA{p}, toMathlibPolynomial bezoutB{p}, ?_⟩
  have h := congrArg toMathlibPolynomial bezout_{p}
  simpa only [toMathlibPolynomial_add, toMathlibPolynomial_mul,
    toMathlibPolynomial_derivative, toMathlibPolynomial_one] using h

theorem certs_match_{p} :
    factors{p}.map ListPoly.natCoeffs = certs{p}.map (fun c => c.low ++ [1]) := by
  decide +kernel

/-- Kernel replay of the Rabin certificates: X^({p}^n) ≡ X and no roots in F_{p}. -/
theorem certs_check_{p} : ListPoly.checkCerts {p} {lst(degree_primes)} certs{p} = true := by
  decide +kernel

theorem irreducible_{p} :
    ∀ q ∈ factors{p}, Irreducible (toMathlibPolynomial q) :=
  ListPoly.irreducible_of_checkCerts {lst(degree_primes)} (by decide) factors{p} certs{p}
    certs_match_{p} certs_check_{p}

theorem factorization_{p} :
    (factors{p}.map toMathlibPolynomial).prod = toMathlibPolynomial (paperFp {p}) := by
  rw [reduction_{p}, ← toMathlibPolynomial_listProd, product_{p}]

"""
    inputs += "end Sz8.Monodromy\n"
    certs += "end Sz8.Monodromy\n"
    spec += "end Sz8.Monodromy\n"
    modular += "end Sz8.Monodromy\n"
    outputs = {HERE / "Sz8/Monodromy/Inputs.lean": inputs,
               HERE / "Sz8/Monodromy/IrredCerts.lean": certs,
               HERE / "Sz8/Monodromy/SpecCerts.lean": spec,
               HERE / "Sz8/Monodromy/Modular.lean": modular,
               HERE / "input-report.json": json.dumps(report, indent=2) + "\n"}
    export_outputs(outputs, check=args.check, root=HERE, exporter='export_inputs', sources=[SOURCE])
    print(f"{'Checked' if args.check else 'Exported'} {len(terms)} terms; factorizations: 11 -> {report['primes']['11']['factor_degrees']}; 31 -> {report['primes']['31']['factor_degrees']}")


if __name__ == "__main__":
    main()
