#!/usr/bin/env python3
"""Export integer columns and Rouché step certificates for certified continuation.

For each step the certificate is a parameter disc |t - t0| <= h (t0 = tau/2^J,
h = S/2^J) and 65 root discs |x - c| < R (c = gamma/2^K, R = W/2^K). Lean's kernel
recomputes the exact Taylor expansion of f around every (c, t0) (Kronecker-packed)
and checks one Rouché inequality per disc. Numerical root finding (python-flint)
only proposes the centres; the exact replica here mirrors the Lean check so that
S can be chosen maximal.

Run from any directory; --check compares generated files without modifying them.
"""
import argparse
from fractions import Fraction as Q
from hashlib import sha256
from export_provenance import export_outputs
import json
import math
from pathlib import Path

import flint

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "data/f.json"
L = 13 ** 182           # common denominator of the input coefficients
N = 65
K, J = 20, 40           # root-variable and parameter scaling exponents


def load_columns():
    raw = SOURCE.read_bytes()
    data = json.loads(raw)
    rat = [[Q(0)] * 66 for _ in range(8)]
    for ij, a in data["coefficients"].items():
        i, j = map(int, ij.split(","))
        rat[j][i] = Q(a)
    cols = []
    for c in rat:
        c = c[:]
        while c and c[-1] == 0:
            c.pop()
        ints = []
        for a in c:
            v = a * L
            assert v.denominator == 1
            ints.append(v.numerator)
        cols.append(ints)
    return raw, cols


# ---- exact replica of the Lean check (Sz8/Monodromy/DiscRouche.lean, PackedCheck.lean) ----

def gmul(a, b): return (a[0] * b[0] - a[1] * b[1], a[0] * b[1] + a[1] * b[0])


def padd(p, q):
    n = max(len(p), len(q))
    p = p + [(0, 0)] * (n - len(p)); q = q + [(0, 0)] * (n - len(q))
    return [(a[0] + b[0], a[1] + b[1]) for a, b in zip(p, q)]


def pshift(g, p):
    S = []
    for a in reversed(p):
        S = padd(padd([a], [gmul(g, s) for s in S]), [(0, 0)] + S)
    return S


def scale_up(p):
    return [(a[0] << (K * (N - i)), a[1] << (K * (N - i))) for i, a in enumerate(p)]


def step_rows(tau, cols):
    """oshift tau (oscale J 7 cols): rows of 2^(7J) f(x, (tau + sigma)/2^J) in sigma."""
    rows = [[(a << (J * (7 - j)), 0) for a in c] for j, c in enumerate(cols)]
    S = []
    for P in reversed(rows):
        new = [padd(P, [gmul(tau, a) for a in S[0]] if S else [])]
        for l in range(1, len(S)):
            new.append(padd([gmul(tau, a) for a in S[l]], S[l - 1]))
        if S:
            new.append(S[-1])
        S = new
    return S


def n1(a): return abs(a[0]) + abs(a[1])


def maj(W, p):
    r = 0
    for a in reversed(p):
        r = n1(a) + W * r
    return r


def omaj(S, W, rows):
    r = 0
    for P in reversed(rows):
        r = maj(W, P) + S * r
    return r


def disc_ok(D, g, W, S):
    E = [pshift(g, scale_up(P)) for P in D]
    e = E[0][1] if len(E[0]) > 1 else (0, 0)
    killed = [[E[0][0], (0, 0)] + E[0][2:]] + E[1:]
    M = omaj(S, W, killed)
    return W > 0 and M * M < (e[0] ** 2 + e[1] ** 2) * W * W


def digit_bits(D, wmax):
    lam = max(maj(wmax, scale_up(P)) for P in D)
    return lam.bit_length() + 2


# ---- step construction ----

def roots_at(cols, t):
    flint.ctx.prec = 300
    tt = flint.acb(t)
    coeffs = [sum(flint.acb(cols[j][i]) * tt ** j for j in range(8) if i < len(cols[j]))
              for i in range(66)]
    return flint.acb_poly(coeffs).roots()


def make_discs(roots):
    cent = [(round(float(r.real.mid()) * 2 ** K), round(float(r.imag.mid()) * 2 ** K))
            for r in roots]
    discs = []
    for i, c in enumerate(cent):
        hsum = sum(1 / math.hypot(c[0] - e[0], c[1] - e[1]) for j, e in enumerate(cent) if j != i)
        discs.append((c, int(0.3 / hsum)))
    return discs


def max_step(D, discs):
    lo, hi = 0, 2 ** J
    while hi - lo > 2 ** J >> 24:
        mid = (lo + hi) // 2
        if all(disc_ok(D, g, W, mid) for g, W in discs):
            lo = mid
        else:
            hi = mid
    return lo


def gi(a): return f"({a[0]}, {a[1]})"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw, cols = load_columns()
    header = ("-- Generated by export_continuation.py; do not edit.\n"
              f"-- data/f.json SHA-256: {sha256(raw).hexdigest()}\n")
    colsrc = header + """import Sz8.Monodromy.GaussPoly

/-! `13^182` times the continuation columns, as Gaussian integers. -/

namespace Sz8.Monodromy
open GaussPoly

def intCols : List (List GI) := [
""" + ",\n".join("  [" + ", ".join(f"({a}, 0)" for a in c) + "]" for c in cols) + "]\n\nend Sz8.Monodromy\n"

    # Step 0: the parameter disc around t = 0.
    tau = (0, 0)
    D = step_rows(tau, cols)
    discs = make_discs(roots_at(cols, 0))
    S = max_step(D, discs)
    assert S > 0
    wmax = 1 + max(n1(g) for g, _ in discs)
    b = digit_bits(D, wmax)
    SLICE = 13
    slices = [discs[i:i + SLICE] for i in range(0, len(discs), SLICE)]
    stepsrc = header + f"""import Sz8.Monodromy.StepCheck

/-! One certified continuation step with all 65 roots.

For every complex `t` with `|t| ≤ {S}/2^{J}` (about {S / 2 ** J:.5f}), each of the 65 discs
contains exactly one root of `f(X, t)` and none on its boundary; in particular every such
`t` is a regular parameter. -/

namespace Sz8.Monodromy
open GaussPoly

set_option maxRecDepth 100000

""" + "".join(f"""def step0Slice{k} : List (GI × ℕ) :=
  [""" + ", ".join(f"({gi(g)}, {W})" for g, W in sl) + """]

""" for k, sl in enumerate(slices)) + f"""def step0Slices : List (List (GI × ℕ)) :=
  [""" + ", ".join(f"step0Slice{k}" for k in range(len(slices))) + f"""]

theorem step0_pre : stepPre {J} {K} {b} {gi(tau)} {wmax} step0Slices.flatten = true := by
  decide +kernel

""" + "".join(f"""theorem step0_slice{k} : sliceCheck {J} {K} {b} {gi(tau)} {S} step0Slice{k} = true := by
  decide +kernel

""" for k in range(len(slices))) + f"""/-- The certified step: every `|t| ≤ h` is regular, with one root in each disc. -/
theorem step0_certified : StepCertified {J} {K} {gi(tau)} {S} step0Slices.flatten :=
  stepCertified_of_checks step0_pre (by
    simp only [step0Slices, List.forall_mem_cons, List.not_mem_nil, IsEmpty.forall_iff,
      implies_true, and_true]
    exact ⟨""" + ", ".join(f"step0_slice{k}" for k in range(len(slices))) + """⟩)

end Sz8.Monodromy
"""
    outputs = {HERE / "Sz8/Monodromy/IntColumns.lean": colsrc,
               HERE / "Sz8/Monodromy/ContinuationStep0.lean": stepsrc}
    export_outputs(outputs, check=args.check, root=HERE, exporter='export_continuation', sources=[SOURCE])
    print(f"{'Checked' if args.check else 'Exported'} step 0: h = {S / 2 ** J:.6f}, "
          f"digit bits {b}, {len(discs)} discs")


if __name__ == "__main__":
    main()
