"""Exercise the provenance exception without weakening generated-content checks."""
from hashlib import sha256
import json
from pathlib import Path
import tempfile
import unittest

from export_provenance import export_outputs


class ProvenanceTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        base = Path(self.temp.name)
        self.root = base / 'lean'
        self.root.mkdir()
        (base / 'data').mkdir()
        self.source = base / 'data/f.json'
        self.source.write_text('{"coefficients":{"0,0":"1"}}\n')
        self.lean = self.root / 'Input.lean'
        self.report = self.root / 'report.json'
        self.run_export(check=False)

    def outputs(self):
        digest = sha256(self.source.read_bytes()).hexdigest()
        coefficient = json.loads(self.source.read_text())['coefficients']['0,0']
        return {
            self.lean: '-- Generated by fixture.py; do not edit.\n'
                       f'-- data/f.json SHA-256: {digest}\n'
                       f'def coefficient : Nat := {coefficient}\n',
            self.report: json.dumps({'sha256': digest}) + '\n',
        }

    def run_export(self, *, check):
        export_outputs(self.outputs(), check=check, root=self.root,
                       exporter='fixture', sources=[self.source])

    def test_provenance_refresh_preserves_lean_bytes_and_mtime(self):
        before = self.lean.read_bytes(), self.lean.stat().st_mtime_ns
        self.source.write_text('{ "coefficients": {"0,0": "1"}, "note": "renamed" }\n')
        with self.assertRaises(ValueError):
            self.run_export(check=True)
        self.run_export(check=False)
        self.assertEqual(before, (self.lean.read_bytes(), self.lean.stat().st_mtime_ns))
        self.run_export(check=True)
        manifest = json.loads((self.root / 'provenance/fixture.json').read_text())
        self.assertEqual(manifest['current_sources']['data/f.json'],
                         sha256(self.source.read_bytes()).hexdigest())
        self.assertEqual(manifest['artifacts']['Input.lean']['sha256'],
                         sha256(self.lean.read_bytes()).hexdigest())

    def test_coefficient_change_rejected_and_regenerates_new_header(self):
        before = self.lean.read_bytes()
        self.source.write_text('{"coefficients":{"0,0":"2"}}\n')
        with self.assertRaises(ValueError):
            self.run_export(check=True)
        self.run_export(check=False)
        self.assertNotEqual(before, self.lean.read_bytes())
        self.assertEqual(self.lean.read_text(), self.outputs()[self.lean])
        self.run_export(check=True)

    def test_content_corruption_rejected(self):
        self.lean.write_text(self.lean.read_text().replace(':= 1', ':= 2'))
        with self.assertRaises(ValueError):
            self.run_export(check=True)

    def test_historical_digest_tampering_rejected_by_manifest(self):
        lines = self.lean.read_text().splitlines(keepends=True)
        lines[1] = '-- data/f.json SHA-256: ' + '0' * 64 + '\n'
        self.lean.write_text(''.join(lines))
        with self.assertRaisesRegex(ValueError, 'provenance manifest'):
            self.run_export(check=True)

    def test_exception_does_not_cover_other_header_changes(self):
        original = self.lean.read_text()
        for bad in [original.replace('data/f.json', 'data/monodromy.json'),
                    original.replace('-- Generated by fixture.py', '-- Generated by other.py'),
                    original.replace('SHA-256:', 'SHA-256: invalid'),
                    original + '-- an extra comment\n',
                    original.replace('\n', '\r\n')]:
            with self.subTest(bad=bad):
                self.lean.write_bytes(bad.encode())
                with self.assertRaises(ValueError):
                    self.run_export(check=True)

    def test_report_corruption_rejected(self):
        self.report.write_text('{}\n')
        with self.assertRaises(ValueError):
            self.run_export(check=True)

    def test_missing_manifest_rejected(self):
        (self.root / 'provenance/fixture.json').unlink()
        with self.assertRaises(ValueError):
            self.run_export(check=True)

    def test_check_is_read_only(self):
        before = {p: (p.read_bytes(), p.stat().st_mtime_ns)
                  for p in self.root.rglob('*') if p.is_file()}
        self.run_export(check=True)
        self.assertEqual(before, {p: (p.read_bytes(), p.stat().st_mtime_ns) for p in before})


    def test_missing_artifact_regenerates_recorded_historical_header(self):
        lines = self.lean.read_text().splitlines(keepends=True)
        lines[1] = '-- data/f.json SHA-256: ' + '1' * 64 + '\n'
        self.lean.write_text(''.join(lines))
        export_outputs(self.outputs(), check=False, root=self.root, exporter='fixture',
                       sources=[self.source], pinned=False)
        recorded = self.lean.read_bytes()
        self.lean.unlink()
        export_outputs(self.outputs(), check=False, root=self.root, exporter='fixture',
                       sources=[self.source], pinned=True)
        self.assertEqual(recorded, self.lean.read_bytes())
        self.run_export(check=True)

    def test_pinned_refuses_manifest_change_and_writes_nothing(self):
        self.lean.unlink()
        self.source.write_text('{"coefficients":{"0,0":"2"}}\n')
        with self.assertRaisesRegex(ValueError, 'committed provenance'):
            export_outputs(self.outputs(), check=False, root=self.root, exporter='fixture',
                           sources=[self.source], pinned=True)
        self.assertFalse(self.lean.exists())


if __name__ == '__main__':
    unittest.main()
